docs/src/apimanual.md
docs/src/apireference.md
docs/src/index.md
src/MathOptInterface.jl
src/attributes.jl
src/constraints.jl
src/objectives.jl
src/references.jl
src/sets.jl
src/variables.jl

to be resolved: separate model and solver attributes for clarity?

WIP: reorganize API file, make it more consistent

---

docs/src/apireference.md
src/MathOptInterface.jl
src/attributes.jl
src/constraints.jl
src/functions.jl
src/objectives.jl
src/references.jl

@blegat's comment [here](https://github.com/JuliaOpt/MathOptInterface.jl/issues/9#issuecomment-312516818) exposes the fact that we currently have 6 types of functions with different representations, between the combinations of variablewise, affine, quadratic, and scalar-valued, and vector-valued. Instead of enumerating all of these combinations in ``addconstraint!``, I think it makes sense to encode these with function objects. 
With this, the signatures of ``addconstraint!`` and ``setobjective!`` become:
```julia
addconstraint!(m::AbstractSolverInstance, func::F, set::S)::ConstraintReference{F,S}
setobjective!(m::AbstractSolverInstance, func::F, N::Int=1)
```
where `func` is a simple `struct` with the corresponding data.
``func`` could be, e.g.:
```julia
""" …
```

introduce a function concept

---

docs/src/apimanual.md
docs/src/apireference.md
src/attributes.jl
src/functions.jl
src/sets.jl

Worth looking at the ~`mixintopt`~ `solveintegerlinear` code example to see if we're happy with the final result. ~There's a small awkwardness in that we have the ``LessThan`` and ``GreatThan`` sets but no set representing equality with a constant, so for equality constraints we have to move the right-hand side into the constant of the affine expression.~ I added the ``EqualTo`` set for consistency.

more work on the manual

---

src/attributes.jl
test/contlinear.jl
test/function_utilities.jl
test/runtests.jl

@joaquimg, what do you think of this? For comparisons we canonicalize using a dictionary, so no order is required. Quadratic would look very similar.

fix comparisons of variablewise and affine functions

---

test/function_utilities.jl

I realized this is incorrect because the order of the variables matters here. The default equality comparison should be fine.

remove incorrect equality definition for VectorVariablewiseFunction

---

docs/src/apimanual.md
docs/src/apireference.md
src/sets.jl

For consistency with the convention that `s` implies a multidimensional set (https://github.com/JuliaOpt/MathOptInterface.jl/pull/52).

rename Integers set to Integer

---

src/functions.jl
src/sets.jl

Trying this out to see if it's a useful concept. Is it the case that we would only want to allow constraints of the form "vector-valued function" in "vector-input set" and "scalar-valued function" in "scalar-input set"?
This is a revival and extension of @blegat's https://github.com/JuliaOpt/MathOptInterface.jl/pull/44.

segregate scalar and vector sets and functions

---

test/contconic.jl

The duals needs to be flipped according to the convention written in the docs (which makes sense since conic dual do not match LPQP duals in MPB and they match in MOI).
I haven't checked in the SOC and SDP tests yet but I will do that in a later PR.

Fix conic duals

---

docs/src/apimanual.md
docs/src/apireference.md
src/MathOptInterface.jl
src/constraints.jl
src/functions.jl
test/contconic.jl
test/contlinear.jl
test/contquadratic.jl
test/intlinear.jl

`ScalarVariablewiseFunction` is renamed to `SingleVariable`, `VectorVariablewiseFunction` is renamed to `VectorOfVariables`. In a second PR I'll add the shorthand proposed [here](https://github.com/JuliaOpt/MathOptInterface.jl/issues/60#issuecomment-316474508).
Closes #60

rename variablewise functions

---

docs/src/apimanual.md

I believe we had a consensus on this, although it may keep @blegat up at night thinking about the extra copies. This doesn't prohibit a performance hint letting the solver know that copies are not needed.
Closes #73

explicit discussion of data ownership

---

test/contconic.jl

Since x does not appear in the objective the sum of the duals * coefficients of x should be 0.

Fix dual for SOC1

---

test/contlinear.jl

Any solution such that x+y = 2, x >= 0, y >= 0 (i.e. the simplex scaled by 2) is optimal. For instance, CSDP returns [1.3095908090667123, 0.6904091909332876] which is optimal but wasn't passing the test :(

Accept more solution for linear5

---

docs/src/apireference.md
src/attributes.jl

This is particularly useful if you only have an instance object and want to extract data from it (e.g., in JuMP). Right now you're forced to keep track of the variable and constraint references separately.

attributes to access list of references present in an instance

---

docs/src/apireference.md
src/attributes.jl
src/objectives.jl
test/contlinear.jl
test/contquadratic.jl

rename Sense attribute to ObjectiveSense

---

.travis.yml
appveyor.yml
test/REQUIRE
test/runtests.jl

There's no reason to have MOI failing on travis when we don't even test anything at all.
This closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/102 as far as I'm concerned. When solvers run the MOI tests they need to call MOIU, but that's less of an issue because many solvers will depend on MOIU anyway.
Ref https://github.com/JuliaOpt/MathOptInterface.jl/pull/96

clear out runtests.jl

---

test/contconic.jl
test/contlinear.jl
test/contquadratic.jl
test/intlinear.jl

Port some of the MPB tests from linprog (1 c,d,e from https://github.com/JuliaOpt/MathOptInterface.jl/issues/23) and add tests for the result count attribute https://github.com/JuliaOpt/MathOptInterface.jl/issues/99#issuecomment-319501666
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/105

WIP: More tests

---

test/contconic.jl
test/contlinear.jl
test/intlinear.jl

Disable SOS tests for non-SOS solvers. Absense of SOS support should not produce a test fail.
I have added `NearlyFeasible` as an acceptable result for some tests.

Fix test args, test for SOS-constraint suppoort

---

test/contconic.jl

adds **conicinterface.jl** 3a and 3c from #23 
not sure how to do 3b:
```
```

Rotated SOC tests

---

docs/src/apireference.md
src/constraints.jl
src/objectives.jl
src/references.jl
test/contlinear.jl
test/intlinear.jl

So far only added to contlinear and intlinear. There should be more modification tests in conic and quadratic...
I also reverted https://github.com/JuliaOpt/MathOptInterface.jl/pull/121 to default to the boolean `false` rather than throw an error which seems like the better thing to do.

Add tests for candelete and canmodify

---

test/contlinear.jl

Less changes than in #127 
We can decide later to merge that one.

fix ray in contlin8

---

docs/src/apimanual.md
docs/src/apireference.md
src/MathOptInterface.jl
src/attributes.jl
src/constraints.jl
src/objectives.jl
src/references.jl
src/variables.jl

Following up on https://github.com/JuliaOpt/MathOptInterface.jl/pull/131, this PR updates the type hierarchy to allow for a standalone instance that's not attached to a solver.
- `AbstractSolverInstance` and `AbstractStandaloneInstance` inherit from `AbstractInstance`.
- Attributes are split into `AbstractSolverInstanceAttribute` and `AbstractInstanceAttribute`. There are no attributes specific to a standalone instance.
- No change to variable and constraint attributes, standalone instances can just implement `cangetattribute` appropriately.
I'm heading in the direction of making a simple reader/writer for MOI instances that we can use in JuMP's unit tests to check if JuMP generates the problem correctly. After this PR we can just call these objects standalone instances, as a first-class …

Update abstraction to make room for standalone instances

---

src/sets.jl

As proposed in #137, some fields within sets are renamed for greater consistency. 
They are
- `dim` to `dimension` for vector sets
- `l` and `u` to `lower` and `upper` for semicontinuous and semi-integer sets
- `a` to `exponent` for power cones
Closes #137

Rename fields within sets

---

docs/src/apimanual.md
docs/src/apireference.md
src/attributes.jl
src/constraints.jl
test/contconic.jl
test/contlinear.jl
test/contquadratic.jl
test/intconic.jl
test/intlinear.jl

The tests and examples seem to look pretty clean now. This should be fine as along as we never plan on exporting these names.
Will allow us to use `MOI.get` to look up variables and constraints by name (#151). I'll merge this automatically if the following conditions hold:
- 24 hours have passed
- No objections
- At least three thumbs up

rename getattribute to get and setattribute! to set!

---

src/attributes.jl
test/instance.jl

Overload `get` and `canget` to look up a variable or constraint reference by name as proposed in #151.

define lookup by name 

---

test/contlinear.jl

added a new test of infeas. prob. with 2 constraints

---

docs/src/apireference.md
src/MathOptInterface.jl

This PR renames `writeinstance` to `write` and adds two new methods:
`MathOptInstance.read!(instance::AbstractInstance, filename::String)`
and
`MathOptInstance.copy!(dest::AbstractInstance, src::AbstractInstance)`
We use `MathOptInstance.copy!` over `Base.copy!` for consistency with other MathOptInterface methods that have identical names (i.e. `get`) but do not overload the Base version.
For example:
```julia
grb = MOI.SolverInstance(GurobiSolver())
MOI.write(grb, "test.mps")
cpx = MOI.SolverInstance(CPLEXSolver())
MOI.read!(cpx, "test.mps")
xpr = MOI.SolverInstance(XpressSolver())
MOI.copy!(xpr, cpx)
```
<s>Another option is
```julia
"""
SolverInstance(solver::AbstractSolver)
Create a solver instance from the given solver.
SolverInstance(solver::AbstractSolver, filename::String)
Create …
```

Add function readinstance

---

src/sets.jl
test/contconic.jl

Comparisons between the storage formats can be found [here](http://www.netlib.org/lapack/lug/node123.html) or [here](https://software.intel.com/en-us/mkl-developer-reference-c-matrix-storage-schemes-for-lapack-routines).
The mapping is a lot easier with the `'U'` storage format and it does not depend on the dimension of the matrices. For this reason, I think we should pick this one.

Change packed storage format for PSD cone

---

docs/src/apireference.md
src/sets.jl

I have also defined `dimension` for PSD cones since `s.dimension` is not the dimension of the cone.

Add PSDSquare + LogDet + RootDet + GeometricMean cones

---

src/MathOptInterface.jl

* `isempty` is needed in https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/32#issuecomment-350852899
* `empty!` is needed in https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/pull/47

Add isempty and empty!

---

docs/src/apireference.md
src/MathOptInterface.jl
src/attributes.jl

It seems to me that *copyable* attribute is vague but it corresponds precisely to non-solver specific attributes that were set.

Add list of attributes set

---

src/attributes.jl

Should we set `mustcopy` to `true` or `false` by default or no no default ?
If we set it to `true`, it may mean more work from the wrapper since most of their attributes will need to return `false` but it may be safer.

Implements mustcopy for MOI attributes

---

docs/src/apireference.md
src/attributes.jl
src/constraints.jl

Follow up of #188, alternative of `supportsproblem` that was axed in #170

Add supportconstraint and supportattribute

---

src/objectives.jl

I guess it wasn't intentional to use `AbstractSolverInstance` here.

AbstractInstance for canmodifyobjective fallback

---

src/functions.jl
test/isapprox.jl
test/runtests.jl

Closes https://github.com/JuliaOpt/MathOptInterfaceTests.jl/issues/33.
MOIU used to implements indexing, copy and comparison of MOI types. Thanks to `eachscalar`, it does not directly define Base methods on MOI types. With https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/pull/72, it does not implement copy anymore.
The last remaining type piracy is with `isapprox`.
Adding a method define externally with arguments having only external types should be avoided in Julia. Here `isapprox` is defined in Base so MOIU shouldn't define it for MOI types.
If MOIT defines it, that automatically makes it impossible to use by another package without adding MOIT in its requirement. If it doesn't know about it, it might give a weird failure, the first time sometime try to load the package with …

Implements Base.isapprox

---

docs/src/apireference.md
src/variables.jl

As raised here:
https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/blob/85d2d0d7ff71a81172a464a0adbfaa893c208147/src/instancemanager.jl#L150-L151
If a solver does not support `addvariable!` (which is the case of SCS, ECOS, CSDP, SDPA, ...), the instance manager needs to know it and switch to the `EmptySolver` state in automatic mode.
This PR fixes the issue.

Add canaddvariable function

---

src/attributes.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/212
We need to decide whether we want to split it for variable and constraints, the issue if we split is that we do not allow `get(::SomeInstance, ::AnyProperty, ::Vector)` as explained in the comment, is it a big issue ?

Add vector fallback for get/set!

---

docs/src/apimanual.md
docs/src/apireference.md
src/MathOptInterface.jl
src/attributes.jl
src/constraints.jl
src/indextypes.jl
src/nlp.jl
src/objectives.jl
src/variables.jl

`AbstractInstance` -> `ModelLike`
`AbstractStandaloneInstance` -> gone
`AbstractSolverInstance` -> `AbstractOptimizer`
`AbstractInstanceAttribute` -> `AbstractModelAttribute`
`AbstractSolverParameter` -> `AbstractOptimizerAttribute`
Updated the discussion in the manual, let me know if it reads well. If there's consensus on this renaming, I'll queue up PRs on the downstream packages and merge all at once.
Closes #203

Last big renaming

---

src/MathOptInterface.jl

Things missed in the Last Big Renaming (#217).

More instance->model

---

src/MathOptInterface.jl
src/Test/Test.jl
src/Test/config.jl
src/Test/contconic.jl
src/Test/contlinear.jl
src/Test/contquadratic.jl
src/Test/intconic.jl
src/Test/intlinear.jl
src/Test/modellike.jl

See https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/89
I run a few benchmarks with Julia v0.6.2, ses the results below.
Currently, we have
```julia
julia> @time using MathOptInterface
0.458081 seconds (431.28 k allocations: 22.743 MiB, 1.22% gc time)
julia> @time using MathOptInterfaceTests
1.685874 seconds (600.04 k allocations: 34.764 MiB, 0.50% gc time)
```
The long time for MOIT is due to the fact that it is not precompiled. If we add `__precompile__()` in `MathOptInterfaceTests.jl`, we get
```julia
julia> @time using MathOptInterface
0.452718 seconds (431.28 k allocations: 22.739 MiB, 1.25% gc time)
julia> @time using MathOptInterfaceTests
0.003029 seconds (3.56 k allocations: 889.141 KiB)
```
With this PR, we have
```julia
julia> @time using MathOptInterface
0.456814 …
```

Add MOIT as a submodule

---

src/Test/contlinear.jl

... by adding some redundant zero terms.
Replaces https://github.com/JuliaOpt/MathOptInterfaceTests.jl/pull/59.

Test handling of duplicate ScalarAffine coeffs

---

src/sets.jl

While `LessThan`, `GreaterThan`, `Interval` requires an ordering, `EqualTo` also makes sense for e.g. complex numbers.

EqualTo for Number not Real

---

src/Utilities/functions.jl
src/Utilities/mockoptimizer.jl
src/Utilities/model.jl
test/mockoptimizer.jl
test/model.jl

Adds support for automatically computing ConstraintPrimal and ObjectiveFunction based on the variable primal values. This is tested with a test of MOIT hence it also checks that ConstraintPrimal and ObjectiveFunction is consistent with variable primal for this test.
It also updates MOIU model so that variable indices are sorted in order of creation as required by https://github.com/JuliaOpt/MathOptInterface.jl/issues/230. It helps for setting variable primal in `test/mockoptimizer.jl`

Add support for ConstraintPrimal for MockOptimizer

---

.gitignore

These are just the standard ignored file types in `.gitignore` from `PkgDev.jl`: https://github.com/JuliaLang/PkgDev.jl/blob/cf855d420a4a1cf9c97d270dbf5da4f63d0a8519/src/generate.jl#L344-L346.

Add .cov and .mem to .gitignore.

---

src/Utilities/model.jl

This allows to catch the bug fixed by https://github.com/JuliaOpt/MathOptInterfaceBridges.jl/pull/100

More accurate canget for MOIU model

---

src/Test/contlinear.jl

This test is the only one which tests `Interval` so we should also add query tests to make sure solvers also implement queries correctly with `Interval`.

Test ConstraintSet after Interval is modified

---

docs/src/apireference.md
src/attributes.jl

This is needed to solve https://github.com/JuliaOpt/JuMP.jl/issues/1092

Add SolverName

---

src/nlp.jl

We can simplify things a bit now that `ListOfVariableIndices()` has a defined order (order of variable creation).

tweak how variable order is handled in the NLP interface

---

src/Utilities/cachingoptimizer.jl
test/cachingoptimizer.jl

The optimizer and model need to be empty in order to be in sync at the start.
This has the additional advantage that if solvers use this constructor for testing, they will be tested with `isempty` so that they will also work when they will be used with `resetsolver!` which calls `isempty` (issue raised by @joaquimg on Gitter).

Check that optimizer is empty in constructor

---

src/MathOptInterface.jl
src/Test/modellike.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/mockoptimizer.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
test/cachingoptimizer.jl

Add copynames argument to copy

---

src/Utilities/copy.jl

This makes the warning print only once and shows a stacktrace to help fix the deprecation.

Use Base.depwarn for defaultcopy! deprecation

---

src/Test/contquadratic.jl

They seem to be correct in other places, but these two qcp tests have terms that don't match the math description. The tests pass with Ipopt after this change.
@joaquimg @blegat

fix scale of diagonal terms in ScalarQuadraticFunction

---

src/Test/contquadratic.jl

Fix qcp1 and add ConstraintPrimal to qcp tests

---

src/Utilities/functions.jl

`coalesce(i::Int, 0)` returns i and `coalesce(nothing, 0)` returns 0, this is the new way to deal with the deprecation recommended by the warning on nightly.

Update findfirst for Julia v0.7

---

NEWS.md
src/Bridges/Bridges.jl
src/Bridges/bridge.jl
src/Bridges/detbridge.jl
src/Bridges/geomeanbridge.jl
src/Bridges/intervalbridge.jl
src/Bridges/soctopsdbridge.jl
src/MathOptInterface.jl
test/bridge.jl
test/runtests.jl

Add Bridges submodule

---

src/MathOptInterface.jl

Suggested by @tkoolen in the Gitter chat

Improve wording in copy doc

---

src/Bridges/Bridges.jl
test/bridge.jl

Discussed in https://github.com/JuliaOpt/MathOptInterface.jl/pull/320#discussion_r182412047
There is a slight increase in loading time but it does not seem significant. As JuMP might define these bridges anyway, it should affect JuMP's loading time.
Before this PR:
```julia
$ julia
julia> @time using MathOptInterface
0.547734 seconds (460.14 k allocations: 25.334 MiB, 10.26% gc time)
$ julia
julia> @time using MathOptInterface
0.548062 seconds (460.14 k allocations: 25.335 MiB, 9.92% gc time)
```
After this PR:
```julia
$ julia
julia> @time using MathOptInterface
0.593794 seconds (513.22 k allocations: 27.837 MiB, 9.64% gc time)
$ julia
julia> @time using MathOptInterface
0.591734 seconds (513.22 k allocations: 27.837 MiB, 9.62% gc time)
```

Define bridge in MOIB

---

perf/cachingoptimizer.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/mockoptimizer.jl

Initial benchmark:
```
v0.6
126.218 ns (7 allocations: 176 bytes)
452.726 ns (17 allocations: 416 bytes)
23.927 ns (3 allocations: 96 bytes)
40.416 ns (5 allocations: 144 bytes)
v0.7
105.262 ns (5 allocations: 128 bytes)
414.565 ns (12 allocations: 304 bytes)
9.623 ns (1 allocation: 48 bytes)
29.113 ns (3 allocations: 96 bytes)
```
After parametrization of the MockOptimizer:
```
v0.6
121.149 ns (7 allocations: 176 bytes)
357.014 ns (14 allocations: 352 bytes)
24.722 ns (3 allocations: 96 bytes)
24.712 ns (3 allocations: 96 bytes)
v0.7
104.708 ns (5 allocations: 128 bytes)
311.206 ns (9 allocations: 240 bytes)
9.306 ns (1 allocation: 48 bytes)
9.400 ns (1 allocation: 48 bytes)
```
After parametrization of CachingOptimizer
```
v0.6
38.889 ns (4 allocations: 112 bytes)
252.048 ns (11 …
```

Parametrize CachingOptimizer and MockOptimizer on model type

---

src/Utilities/functions.jl

It was added in Compat v0.49 and we have a lower bound on Compat v0.51 so it does not need a bump

find -> findall

---

src/Utilities/parser.jl

This was causing a warning in Julia v0.7

Remove space between docstring and function

---

src/Utilities/model.jl

This was causing a warning in Julia v0.7

Change for variable name to avoid conflict with macro argument

---

src/Utilities/parser.jl

Compat v0.43 is needed and we have a lower bound on Compat v0.51 so no bump needed

Update replace call for Julia v0.7

---

REQUIRE
src/Utilities/functions.jl

It requires Compat v0.59 hence the bump of the lower bound

 Explicit initialization of vector with undef

---

src/Utilities/functions.jl

repeat already exists in Julia v0.6 so no need for Compat

repmat -> repeat

---

src/Utilities/model.jl
test/Test/unit.jl

Unit tests allowed to find a few bugs in the names implementation of `MOIU.@model`

Fix Model names using unit tests

---

src/attributes.jl

Document constraint primal better

---

src/Bridges/Bridges.jl
src/Bridges/bridgeoptimizer.jl
src/Bridges/singlebridgeoptimizer.jl

* Defines an documented interface for `AbstractBridgeOptimizer` and implements the MOI interface using this interface.
* Defines the `SingleBridgeOptimizer` concrete subtype of `AbstractBridgeOptimizer`.
* The `@bridge` macro now simply creates specifies a `SingleBridgeOptimizer` instead of creating a new concrete subtype of `AbstractBridgeOptimizer`.

Refactor bridge optimizer

---

src/Test/UnitTests/basic_constraint_tests.jl
src/Test/UnitTests/unit_tests.jl
src/sets.jl
test/Test/unit.jl
test/runtests.jl

At the moment it is pretty hard from the solver's point-of-view to check that they are implementing the full MOI API correctly (e.g., LQOI). This PR attempts to test this.
For every constraint type supported by the solver, it tests the basic usage of the MOI API. It does not test corner cases. That can come later. In most cases, checking that the solver implemented something correctly will involve forming the problem, modifying, solving, and then checking the solution. This PR just tries to ensure that the methods are implemented.
It has exposed a number of bugs an un-implemented stuff in LQOI (ref https://github.com/JuliaOpt/LinQuadOptInterface.jl/pull/10).
See [the tests in Gurobi.jl](https://github.com/JuliaOpt/Gurobi.jl/blob/2033629e3a67d72cbfb99ac68fbc417f9c7d2b8e/test/MOIWrapper.jl#L …

RFC: Comprehensive testing of basic constraint functionality

---

src/Utilities/parser.jl
test/parser.jl
test/runtests.jl

The `Parsed*` function have also been updated to match the MOI versions.
The `parsedtoMOI` strategy is now a bit different, it recursively call `parsedtoMOI` to its field instead of `variabletoindex` so that `Parsed*Term` also get called `parsedtoMOI`.

[array_of_tuples] Fix parser

---

src/Bridges/Bridges.jl
src/Bridges/bridgeoptimizer.jl
test/bridge.jl

This would allow JuMP to transform
https://github.com/JuliaOpt/JuMP.jl/blob/a59a431419f885a0e11c2838b50bea0e63061647/src/JuMP.jl#L164
into
```julia
m.moibackend = MOIB.fullbridgeoptimizer(MOIU.CachingOptimizer(MOIU.UniversalFallback(JuMPMOIModel{Float64}()), mode == Automatic ? MOIU.Automatic : MOIU.Manual), Float64)
```
and not have to explicitly add each MOI bridge.
It would be nice if this could also be part of MOI v0.3 :)

Add fullbridgeoptimizer function

---

src/Test/UnitTests/constraints.jl
src/Test/UnitTests/objectives.jl
src/Test/UnitTests/variables.jl
test/Test/unit.jl

- Relating to ScalarQuadraticFunctions:
(1) duplicate terms on the diagonal; and
(2) duplicate terms on the off-diagonal, including duplicates of elements at locations (i,j) and (j,i).
- Deleting mixtures of scalaraffine and vectoraffine functions.

Basic tests to catch edge cases

---

src/functions.jl

`ScalarAffineFunction` and `ScalarQuadraticFunction` are not `isbits` types due to their `Vector` fields, which means that construction necessarily allocates, and as such is not an option if zero allocation is a requirement.
The alternative, pre-allocating `ScalarAffineFunction` and `ScalarQuadraticFunction` objects and then modifying them, is currently almost a solution, save for the `constant` fields, which cannot be modified. Making these types mutable fully enables this second workflow.
An alternative could be to store the constants in `Base.RefValue{T}` fields, but for little gain, and simply making these types mutable seems like the least amount of hassle.

RFC: make ScalarAffineFunction and ScalarQuadraticFunction mutable.

---

.travis.yml
src/Utilities/parser.jl

Also test 0.7 on travis. Failures *not* allowed.
Closes #317 
Closes #378

fix Utilities/parser.jl on 0.7

---

.travis.yml
src/Bridges/Bridges.jl
src/Bridges/bridgeoptimizer.jl
src/Bridges/detbridge.jl
src/Bridges/geomeanbridge.jl
src/Bridges/soctopsdbridge.jl
src/Test/UnitTests/basic_constraint_tests.jl
src/Test/UnitTests/constraints.jl
src/Test/contconic.jl
src/Test/modellike.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/mockoptimizer.jl
src/Utilities/parser.jl
src/attributes.jl
src/constraints.jl
src/functions.jl
src/indextypes.jl
test/bridge.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/385

Turn warnings into errors in CI and fix last remaining warnings

---

docs/src/apireference.md
src/Bridges/soctopsdbridge.jl
src/Utilities/functions.jl
src/functions.jl
src/sets.jl
test/functions.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/366

Define output_dimension

---

perf/cachingoptimizer.jl
src/Utilities/cachingoptimizer.jl
test/cachingoptimizer.jl

This PR adds a type parameter for the optimizer of `CachingOptimizer`. It adds this type parameters in the first place as it will be more useful than the second one (see e.g. `dropoptimizer!`). It also changes the order of the cache and the optimizer fields for consistency.
Note that it does not implement the idea of https://github.com/JuliaOpt/MathOptInterface.jl/issues/321#issuecomment-382729573 of removing the possibility to have no optimizer or to change the optimizer.
Indeed, this would require JuMP to handle these cases and I initially thought that this was the solution because I didn't have the idea of simply using the non concrete type parameter `Union{Nothing, MOI.AbstractOptimizer}` in the case where we want to be able to drop the optimizer and to change it and use the concrete …

Add type parameter for CachingOptimizer

---

NEWS.md

@blegat @odow @joaquimg let me know if there's a reason to hold off on this release. If we do wait, then we should stick to 0.3 for JuMP-dev.

update NEWS for 0.4

---

src/Test/nlp.jl

Ref https://github.com/JuliaOpt/Ipopt.jl/issues/114

add nlp tests for FeasibilitySense

---

docs/src/apimanual.md
docs/src/apireference.md

Closes #401. 
It seems I forgot to check the docs for errors in #388. The links weren't correct either. 
This PR builds the docs without warnings and it looks like:

Fix formatting of modification section

---

src/Test/UnitTests/constraints.jl
src/Test/UnitTests/modifications.jl
src/Test/UnitTests/objectives.jl
src/Test/UnitTests/unit_tests.jl
src/Test/UnitTests/variables.jl
src/Utilities/cachingoptimizer.jl
test/cachingoptimizer.jl
test/runtests.jl

Trying to run unit tests on the caching optimizer showed that there was method missing in the name implementation.
There was also some unit tests that didn't check `config.solve`. I move this check to the subfunction to be sure it is always checked

Fix names for CachingOptimizer

---

src/Utilities/functions.jl
src/functions.jl
test/functions.jl
test/runtests.jl

Fixes #429 
This implements the in-place canonicalization I suggested over in #429 with some cleanup to make it a bit more readable. It adds two new functions: `iscanonical()` which tests if an AffineFunction is canonical and `canonical!` which converts an AffineFunction to canonical form in-place. ~~In Julia v0.7 and above, the in-place `canonical!` should allocate zero memory (on v0.6, it allocates a tiny amount for keyword arguments).~~ Edit: the in-place version now has zero allocations on 0.6 and 0.7 (thanks @tkoolen!) 
Another significant change is that if a function is already in canonical form, it is not copied or modified. This should make things a bit faster for modeling layers like JuMP that already provide canonical functions.

Add in-place version of canonical() and more tests

---

src/Test/modellike.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
test/universalfallback.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/397
Closes https://github.com/JuliaOpt/JuMP.jl/issues/1152

Universal constraint fallback

---

src/Test/UnitTests/objectives.jl
test/Test/unit.jl

Raised by @tkoolen https://github.com/JuliaOpt/Gurobi.jl/pull/125#issuecomment-406017666
See also https://github.com/JuliaOpt/Gurobi.jl/pull/136

Add unit tests for duplicate terms in linear portion of objective

---

src/Test/UnitTests/variables.jl
test/Test/unit.jl

GLPK has issues where it requires integer variables to have integer bounds. So the wrapper has to round the bounds prior to solve, then unround them afterward so they can be queried appropriately.

Add some more tests

---

src/attributes.jl
test/attributes.jl
test/runtests.jl

Without the `S<:AbstractSet` in the first method, julia considers that the signature is less specific.

Fix method specialization

---

src/Test/UnitTests/solve.jl
src/Test/UnitTests/unit_tests.jl
src/Utilities/mockoptimizer.jl
test/Test/unit.jl

Add tests for ObjectiveBound

---

src/indextypes.jl
test/attributes.jl

We'll have to release a MOI v0.5.1 with this fix as it is blocking for copy-only solver

Fix delete fallback

---

docs/src/apireference.md
src/Test/contconic.jl
src/Utilities/Utilities.jl
src/Utilities/mockoptimizer.jl
src/Utilities/model.jl
src/Utilities/results.jl
src/attributes.jl
src/sets.jl
test/Test/contconic.jl
test/Test/contlinear.jl
test/Test/unit.jl
test/mockoptimizer.jl

As discussed in https://github.com/JuliaOpt/MathOptInterface.jl/issues/442 and https://github.com/JuliaOpt/LinQuadOptInterface.jl/issues/41, some solver API do not contain any getters for result informations that can be deduced for variable primals and constraint duals of non-variablewise constraints.
These include the following:
* ObjectiveValue: can be deduced from VariablePrimal and ObjectiveFunction
* ObjectiveBound: can be deduced from ConstraintDual and constants in ConstraintFunction's and ConstraintSet's
* ConstraintPrimal: can be deduced from ConstraintFunction's and VariablePrimal's
* ConstraintDual of variablewise constraints: can be deduced from ConstraintDual of non-variablewise constraints, ObjectiveFunction and ConstraintFunction's.
This PR
* moves the fallback already used …

Add result fallbacks

---

docs/src/apireference.md
src/MathOptInterface.jl

It looks like no solvers implement `free!` yet so this isn't very disruptive. Can anyone think of a situation where we need a special MOI function instead of using `finalize()`? If not I'll go ahead with this.

remove MOI.free!(). use Base.finalize() instead

---

src/Bridges/detbridge.jl
src/Bridges/geomeanbridge.jl
src/Bridges/squarepsdbridge.jl
src/Utilities/constraints.jl
src/Utilities/functions.jl
src/functions.jl
test/constraints.jl
test/functions.jl
test/runtests.jl

This PR contains changes in MOIU of https://github.com/JuliaOpt/MathOptInterface.jl/pull/478. They shouldn't be blocked by the SOCtoQuad bridge

Improve quadratic support in MOIU

---

docs/src/apimanual.md
docs/src/apireference.md
src/Bridges/bridgeoptimizer.jl
src/MathOptInterface.jl
src/Test/modellike.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/mockoptimizer.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
src/attributes.jl
src/constraints.jl

Also rename `defaultcopy!` to `default_copy_to`.
Related to https://github.com/JuliaOpt/MathOptInterface.jl/issues/475

Rename copy! -> copy_to

---

docs/src/apireference.md
src/Bridges/Bridges.jl
src/Bridges/soctopsdbridge.jl
test/bridge.jl

This was inconsistent with the name of the file containing the bridge and the bridge optimizers `SOCtoPSD`  and `RSOCtoPSD` which did not contain the C.

Rename PSDC -> PSD

---

docs/src/apimanual.md
docs/src/apireference.md
src/Test/UnitTests/modifications.jl
src/Test/contlinear.jl
src/Utilities/cachingoptimizer.jl
src/attributes.jl
src/constraints.jl

Related to https://github.com/JuliaOpt/MathOptInterface.jl/issues/475

Rename transform! -> transform

---

docs/src/apimanual.md
docs/src/apireference.md
src/Bridges/bridgeoptimizer.jl
src/Bridges/detbridge.jl
src/Bridges/geomeanbridge.jl
src/Bridges/intervalbridge.jl
src/Bridges/rsocbridge.jl
src/Bridges/soctopsdbridge.jl
src/Bridges/squarepsdbridge.jl
src/Test/UnitTests/basic_constraint_tests.jl
src/Test/UnitTests/constraints.jl
src/Test/UnitTests/variables.jl
src/Test/contlinear.jl
src/Test/contquadratic.jl
src/Test/intlinear.jl
src/Test/modellike.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/mockoptimizer.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
src/constraints.jl
src/indextypes.jl
test/bridge.jl
test/cachingoptimizer.jl
test/errors.jl
test/model.jl
test/universalfallback.jl

Note that `MOIU.IndexMap` still overloads `Base.delete!` as it is a dictionary-like object and not a `ModelLike`.
Since `MOI.delete!` used to be equivalent `Base.delete!` this renaming wasn't just a matter of search and replace :-P It might be a good thing for code readability that these are now different.
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/475

Use MOI.delete instead of Base.delete!

---

src/Test/UnitTests/objectives.jl
src/Utilities/model.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/499

Test InexactError thrown for bad objective function type

---

.travis.yml
appveyor.yml

No need for `depwarn=true` if we test with Julia v1.0

Enable Julia v1.0 on CI

---

src/Test/UnitTests/objectives.jl
src/Utilities/functions.jl
src/Utilities/model.jl
src/functions.jl
test/functions.jl

It will be quite hard to implement `MOI.get(::OptimizerType, ::ObjectiveFunction{T})` passing the unit test added in https://github.com/JuliaOpt/MathOptInterface.jl/pull/502 without the convert functions added in this PR.
The two conversions that were present in MOIU were moved to MOI as they do not add utilites but rather define constructor of MOI types.

Define convert

---

src/Bridges/bridgeoptimizer.jl
src/MathOptInterface.jl
src/Test/UnitTests/objectives.jl
src/Test/UnitTests/solve.jl
src/Test/UnitTests/variables.jl
src/Test/contconic.jl
src/Test/contlinear.jl
src/Test/contquadratic.jl
src/Test/intconic.jl
src/Test/intlinear.jl
src/Test/modellike.jl
src/Test/nlp.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/mockoptimizer.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
src/attributes.jl
test/cachingoptimizer.jl
test/universalfallback.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/505

Rename isempty -> is_empty

---

docs/src/apireference.md
src/Bridges/bridgeoptimizer.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/attributes.jl
test/attributes.jl
test/cachingoptimizer.jl
test/dummy.jl
test/errors.jl
test/runtests.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/480

Define is_copyable and is_set_by_optimize

---

src/Bridges/Bridges.jl
src/Bridges/singlebridgeoptimizer.jl
src/Utilities/model.jl
test/bridge.jl
test/cachingoptimizer.jl
test/model.jl
test/parser.jl
test/runtests.jl
test/universalfallback.jl

Simpler solution as suggested by @blegat. Of course we can now delete _mod function and get rid of its calls.
However even with this solution, we still need to import sets/functions to be used by @bridge
If we want the modules passed to @bridge like `MOI.xxxfunction/MOI.xxxset`, we need more modifications in @model since it uses the names passed to create field names of the new structure. Do we go for that?

Support of bridges with external sets/funcs

---

src/Bridges/bridgeoptimizer.jl
src/Bridges/detbridge.jl
src/Bridges/geomeanbridge.jl
src/Bridges/intervalbridge.jl
src/Bridges/rsocbridge.jl
src/Bridges/soctopsdbridge.jl
src/Test/UnitTests/modifications.jl
src/Test/contlinear.jl
src/Utilities/model.jl
test/bridge.jl
test/cachingoptimizer.jl
test/model.jl
test/universalfallback.jl

`ConstraintSet` and `ConstraintFunction` are not copyable (see `is_copyable`) so they should not implement `supports`.

Remove implementation and testing of supports for ConstraintSet

---

src/attributes.jl

I had to put `Ref`'s in ECOS because of broadcasting attributes and now that I am updating SDOI, I need them again... Probably better to just define the attributes here as scalar :)

Broadcast attributes

---

src/Utilities/copy.jl
src/attributes.jl
src/constraints.jl
test/dummy.jl
test/errors.jl
test/runtests.jl

This PR brings two improvements to user friendliness:
* Allocate-Load equivalents to `set` and `add_constraint` now returns nice user-facing errors instead of method errors
* `add_constraint` with VectorFunction-in-ScalarSet or ScalarFunction-in-VectorSet now returns an error instead of an UnsupportedError relying on the fact that the model implements `supports_constraint` correctly or an `AddConstraintNotAllowed` otherwise which are both less user-friendly
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/530

Add errors for Allocate-Load and bad constraint

---

src/Test/UnitTests/objectives.jl
test/Test/unit.jl

CSDP, OSQP and ECOS fail this tests because `x` is not 1.0 but there is no reason why `x` should exactly be 1.0

Allow all correct solution for solve_blank_obj

---

src/Test/modellike.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
src/attributes.jl

Following up on the discussion in https://github.com/JuliaOpt/JuMP.jl/issues/1402. This change avoids creating the `names_to_var` dictionary until it's needed.
Using @IainNZ's script that benchmarks variable creation time,
Before:
```
10^1:  0.000 s, 3981.300000 ns/var, 286 a, 28.600000 a/var
10^2:  0.000 s, 1016.850000 ns/var, 844 a, 8.440000 a/var
10^3:  0.001 s, 703.424000 ns/var, 6756 a, 6.756000 a/var
10^4:  0.007 s, 664.980500 ns/var, 69774 a, 6.977400 a/var
10^5:  0.100 s, 1003.817160 ns/var, 699808 a, 6.998080 a/var
10^6:  1.558 s, 1558.397552 ns/var, 6999859 a, 6.999859 a/var
```
After:
```
10^1:  0.000 s, 3638.900000 ns/var, 286 a, 28.600000 a/var
10^2:  0.000 s, 829.310000 ns/var, 838 a, 8.380000 a/var
10^3:  0.001 s, 520.511000 ns/var, 6742 a, 6.742000 a/var
10^4:  0.005 s, …
```

RFC: construct the name to object dicts lazily

---

appveyor.yml

Similar to https://github.com/JuliaOpt/JuMP.jl/pull/1572

Disable Julia v0.6 and v0.7 in AppVeyor

---

.travis.yml
docs/Project.toml
docs/make.jl

It allows to prevent breakage with Documenter v0.20 as it is fixed to v0.19 in `docs/Project.toml`: https://discourse.julialang.org/t/psa-documenter-jl-breaking-changes-version-capping/16431
Closes #539

Use a Travis project to build doc

---

src/Test/modellike.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
src/attributes.jl
test/model.jl
test/universalfallback.jl

Throw an error only when looking up a string that corresponds to multiple
variables.
Closes #548
Closes JuliaOpt/JuMP.jl#1292

Allow duplicate variable names

---

docs/src/apimanual.md

It was done in `docs/src/apireference.md` but not in `docs/src/apimanual.md`.
It allows `@ref` to find the documentation without the need to explicitely write it.
I made the simplifications in the manual and did line wrap for lines that were modified.

Set CurrentModule as MOI in manual

---

docs/src/apimanual.md
docs/src/apireference.md
src/MathOptInterface.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/mockoptimizer.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
test/copy.jl

As discussed, we plan to make bridging happen after caching hence the need for an additional caching after the bridges to cache the bridge model.
If the optimizer returns `true` for `supports_incremental_copy` then this second cache will not be added.
If it returns `true` even if `copy_names` is true we could even get rid of the first cache.
With MOI v0.7, the second cache could also be removed if `supports_allocate_load` is true and `supports_incremental_copy` is false.
This PR should be non-breaking even if it adds this new function so it can be part of MOI v0.6.3

Add supports_default_copy_to

---

src/Utilities/model.jl

If we didn't have to support deleting variables, we could just implement `add_variables` as follows and get +- 2ns and 0 allocation for creating one variable.
```julia
using MathOptInterface
const MOI = MathOptInterface
MOI.Utilities.@model(Model, (), (), (), (), (), (), (), ())
const model = Model{Float64}();
_add_variable(model) = MOI.VariableIndex(model.num_variables_created += 1)
```
```julia
julia> @btime _add_variable(model)
1.814 ns (0 allocations: 0 bytes)
```
However, because some variables can be deleted we keep a `Set{MOI.VariableIndex}` of the variables and everytime one is created, we add it to the set.
This means that when adding a variable, we need to compute its hash, and we sometime need to allocate to resize the memory used by the set.
We can see that the performance is …

⚡️ Only track variables indices once one is deleted

---

src/Utilities/model.jl
test/Utilities/model.jl

This is a first step to help readability of this file.

Document storage of constraints

---

src/attributes.jl

Document status enums.

---

src/nlp.jl

This was silently broken because it's covered only by `JuMP/test/nlp_solver.jl`.

NLPBlockDual is set by optimize

---

src/Test/modellike.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/mockoptimizer.jl
src/attributes.jl
test/Utilities/cachingoptimizer.jl
test/Utilities/mockoptimizer.jl

Also fixes default statuses in CachingOptimizer.
Closes #571 
Closes #572

Add `OptimizeNotCalled` termination status with tests and docs

---

src/Test/modellike.jl
src/attributes.jl
test/Utilities/mockoptimizer.jl

Presumably some solvers will need to be updated. But they won't fail current tests without opting into the `default_objective_test`.
Closes #335

Make FeasibilitySense the default ObjectiveSense

---

NEWS.md
src/Bridges/bridgeoptimizer.jl
src/Test/contconic.jl
src/Test/contlinear.jl
src/Test/contquadratic.jl
src/Test/intconic.jl
src/Test/intlinear.jl
src/Test/modellike.jl

The addition of supports_copy_to was not entirely finished in https://github.com/JuliaOpt/MathOptInterface.jl/pull/561 because we wanted it to be non-breaking.
This PR finishes the job.
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/562
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/592

supports_default_copy_to

---

docs/src/apimanual.md
src/Test/UnitTests/unit_tests.jl
src/Test/contconic.jl
src/Test/contlinear.jl
src/Test/contquadratic.jl
src/Test/intconic.jl
src/Test/intlinear.jl
src/Test/nlp.jl
src/Utilities/mockoptimizer.jl
src/attributes.jl
test/Test/contconic.jl
test/Test/contlinear.jl
test/Test/unit.jl
test/Utilities/mockoptimizer.jl
test/bridge.jl

This is a breaking change to `TerminationStatus` following the discussion in https://github.com/JuliaOpt/JuMP.jl/issues/1656.
The main change is that `TerminationStatus` now distinguishes between optimal, locally optimal, infeasible, locally infeasible, and dual infeasible, addressing a usability issue in JuMP where users had to query both termination status and result statuses in order to interpret what happened in very basic cases. We had originally planned to abstract this away at the JuMP level, but this was hard to do because it requires additional knowledge about the solver than what's available through MOI.
I've made only the documentation changes. If we agree on this I'll get tests passing. If you can think of additional interesting corner cases, I'll add them to the tables in the …

redesign TerminationStatus

---

docs/src/apimanual.md
src/Utilities/copy.jl

With the implementation suggested, we get
```julia
MethodError: no method matching automatic_copy_to(::SCS.Optimizer, ::SCSModelData{Float64}, ::Pair{Symbol,Bool})
Closest candidates are:
automatic_copy_to(::MathOptInterface.ModelLike, ::MathOptInterface.ModelLike; copy_names) at /home/blegat/.julia/dev/MathOptInterface/src/Utilities/copy.jl:14
```

Fix copy doc

---

docs/src/apimanual.md
docs/src/apireference.md
src/Bridges/Bridges.jl
src/Bridges/bridgeoptimizer.jl
src/Bridges/vectorizebridge.jl
src/Test/modellike.jl
src/Utilities/model.jl
src/constraints.jl
test/bridge.jl

One can get a taste of how some wrapper can be simplified thanks to this bridge with : https://github.com/blegat/SeDuMi.jl/pull/6
This PR also fix and tests (with linear14test) a bug of bridges with deletion of variables.
First item of https://github.com/JuliaOpt/MathOptInterface.jl/issues/614

✨ Add VectorizeBridge

---

src/Test/contconic.jl

Otherwise, sets that do not support nonzero constant in `ScalarAffineFunction` will fail the test

Move constant to set in psdt2

---

src/Utilities/functions.jl
test/Utilities/functions.jl

✨ Add zero for functions

---

src/Utilities/cachingoptimizer.jl
src/Utilities/mockoptimizer.jl
test/Utilities/cachingoptimizer.jl

The CachingOptimizer was setting names to the optimizer while it should only do it in the cache.
We were correctly doing it in `get`, `copy` and `supports` but not in `set`

🐛 Fix CachingOptimizer with setting names

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Vector{AbstractScalarFunction} -> AbstractVectorFunction

✨ Add vectorize

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Fallbacks to `zero(f)` by default which is not implemented (only implemented for its type) and is disputed https://github.com/JuliaOpt/MathOptInterface.jl/issues/636.

✨ Add iszero

---

src/Bridges/lazybridgeoptimizer.jl
test/bridge.jl

Fix a StackOverflow when it re-triggers the algo when checking if a constraint is supported.

🐛 Fix lazy bridge check for supported constraints

---

docs/src/apireference.md
src/attributes.jl

Ref https://github.com/JuliaOpt/MathOptInterface.jl/pull/678#issuecomment-466648971
CC @EdvinAblad

Remove VariableBasisStatus and clarify when NONBASIC_AT_* should be used

---

src/nlp.jl

I was not able to make the docs locally, so I just hope they still build and the cross-ref works.
Details:
```
ERROR: LoadError: `makedocs` encountered errors. Terminating build
Stacktrace:
[1] error(::String) at ./error.jl:33
[2] runner(::Type{Documenter.Builder.RenderDocument}, ::Documenter.Documents.Document) at /home/rs/.julia/packages/Documenter/J3Jag/src/Builder.jl:204
[3] dispatch(::Type{Documenter.Builder.DocumentPipeline}, ::Documenter.Documents.Document) at /home/rs/.julia/packages/Documenter/J3Jag/src/Utilities/Selectors.jl:167
[4] (::getfield(Documenter, Symbol("##3#8")))() at /home/rs/.julia/packages/Documenter/J3Jag/src/Documenter.jl:267
[5] cd(::getfield(Documenter, Symbol("##3#8")), ::String) at ./file.jl:96
[6] #makedocs#1(::Bool, ::Documenter.Writers.HTMLWriter.HTML, …
```

Add note about VariableIndex in docstring for nlp expressions.

---

src/Test/modellike.jl

This allows solvers that do not support a nonzero constant in the function for scalar constraint to pass this test.
Also use a nonzero constant in the objective.

Use zero constant in scalar constraint function of copy test

---

src/Bridges/bridgeoptimizer.jl
src/Utilities/copy.jl

This pull creates a new `add_constraints` method for bridge optimizers than uses it `copyconstraints!`.  The end result is a significant model creation improvement for Clp.  Benchmarks to follow.   
The associated PRs are:
https://github.com/JuliaOpt/Clp.jl/pull/57
https://github.com/JuliaOpt/LinQuadOptInterface.jl/pull/96
The benchmarking results for Clp show a 40x improvement in the time it takes to copy large models from the cache to the solver:
https://github.com/JuliaOpt/Clp.jl/pull/57#issuecomment-471838224

caching bridge optimizer copy improvement

---

docs/src/apireference.md
src/Utilities/cachingoptimizer.jl
src/Utilities/mockoptimizer.jl
src/attributes.jl
test/Utilities/cachingoptimizer.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/663

Add Silent and implement setting optimizer attributes in caching and mock optimizers

---

src/Test/contconic.jl

it was calling PSD triangle tests for PSD square tests

typos in PSD square testset definition

---

src/Test/config.jl
src/Test/contlinear.jl

I was under the impression that `config.infeas_certificates` means that we can expect `INFEASIBILITY_CERTIFICATE` both for `DUAL_INFEASIBLE` and `INFEASIBLE`.
So for a solver that support infeasibility certificates for `DUAL_INFEASIBLE` but not for `INFEASIBLE`, it should just set `duals` to `false` and the tests shouldn't expect infeasibility certificates for `INFEASIBLE`.
What do you think ?

Only ask for dual infeasibility certificate if duals is true

---

src/Test/UnitTests/basic_constraint_tests.jl

In Mosek, a variable cannot be part of two different cones.
Another approach would be to create more variables and use different ones in each constraints.

Disable add_constraints tests for VectorOfVariables

---

src/Test/contquadratic.jl
src/functions.jl
test/Test/contquadratic.jl

We just discovered a bug in SCIP.jl ([#106](https://github.com/SCIP-Interfaces/SCIP.jl/issues/106)) in the handling of quadratic coefficients off the diagonal, based on my misunderstanding of the MOI docs.
To add prevent this kind of problem, I've added a small example to the docstring and two QCP tests.

Add tests, extend docstring for ScalarQuadraticFunction.

---

.gitignore
.travis.yml
Project.toml
REQUIRE
appveyor.yml
docs/Project.toml
src/Bridges/Bridges.jl
src/Bridges/intervalbridge.jl
src/Bridges/lazybridgeoptimizer.jl
src/Bridges/quadtosocbridge.jl
src/Bridges/squarepsdbridge.jl
src/MathOptInterface.jl
src/Test/Test.jl
src/Test/contconic.jl
src/Test/modellike.jl
src/Utilities/Utilities.jl
src/Utilities/copy.jl
src/Utilities/functions.jl
src/Utilities/model.jl
src/Utilities/parser.jl
src/attributes.jl
src/functions.jl
test/Utilities/cachingoptimizer.jl
test/Utilities/functions.jl
test/Utilities/mockoptimizer.jl
test/attributes.jl
test/bridge.jl
test/functions.jl
test/hygiene.jl
test/runtests.jl

Added a Project.toml file with compatible UUID and corresponding dependencies, removed use of Compat

Remove julia-06

---

src/Test/intlinear.jl
src/sets.jl

Some `SOS{1/2}` methods could be merged.
Also, one was defined in Test for no apparent reason

Doubled methods removed

---

src/Bridges/bridgeoptimizer.jl

Hi, this PR follows my message in gitter. 
I'm working on a package that creates variable/constraint attributes in the JuMP model. Then, another package retrieves these attributes through the MOI interface. In the second package, I overloaded `MOI.set` and `MOI.get` to copy/get variable & constraint attributes. 
These are the definitions of MOI.set & MOI.get in my packages :
```julia
MOI.get(dest::MOIU.UniversalFallback, attr::BD.ConstraintDecomposition, ci::MOI.ConstraintIndex)
MOI.set(dest::MOIU.UniversalFallback, attr::BD.ConstraintDecomposition, ci::MOI.ConstraintIndex, annotation)
```
During the copy process, `MOI.set` of `VariableAttribute` receives a `MOIU.CachingOptimizer`as first argument whereas `MOI.set` of `ConstraintAttribute` receives a `MOIU.Bridges.LazyBridgeOptimizer`. …

overload MOI.set & supports for ConstraintAttribute in bridgeoptimizer

---

docs/src/apireference.md
src/Bridges/quadtosocbridge.jl
src/Bridges/scalarizebridge.jl
src/Bridges/vectorizebridge.jl
src/Utilities/functions.jl
src/Utilities/sets.jl
src/functions.jl
src/sets.jl
test/Utilities/functions.jl
test/Utilities/sets.jl

Merge `MOI._constant` and `MOIU.getconstant`. Fixes #618

common constant function

---

docs/src/apireference.md
src/Test/contconic.jl
src/Test/contlinear.jl
src/Utilities/mockoptimizer.jl
src/Utilities/results.jl
src/attributes.jl
test/Bridges/intervalbridge.jl
test/Test/contconic.jl
test/Test/contlinear.jl
test/Test/unit.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/681

Add DualObjectiveValue

---

Project.toml

We are deprecating JuliaOpt, see https://www.juliaopt.org/meetings/santiago2019/slides/miles_lubin.pdf

Remove authors field

---

docs/src/apireference.md
src/Bridges/bridge.jl
src/Bridges/bridgeoptimizer.jl
src/Bridges/detbridge.jl
src/Bridges/flip_sign_bridge.jl
src/Bridges/functionize_bridge.jl
src/Bridges/geomeanbridge.jl
src/Bridges/intervalbridge.jl
src/Bridges/quadtosocbridge.jl
src/Bridges/rsocbridge.jl
src/Bridges/scalarizebridge.jl
src/Bridges/slackbridge.jl
src/Bridges/soctopsdbridge.jl
src/Bridges/squarepsdbridge.jl
src/Bridges/vectorizebridge.jl

Add the `bridge_constraint` function #668 and add a section in the doc about how to implement a bridge.
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/668

Add bridge_constraint

---

src/attributes.jl

Corresponds to Mosek statuses:
* https://docs.mosek.com/8.1/capi/constants.html#mosek.solsta.prim_illposed_cer
* https://docs.mosek.com/8.1/capi/constants.html#mosek.solsta.dual_illposed_cer
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/725

Add REDUCTION_CERTIFICATE

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Rename constant to constant_vector

---

src/Test/UnitTests/attributes.jl
src/Utilities/mockoptimizer.jl
src/Utilities/universalfallback.jl
test/Test/unit.jl
test/Utilities/universalfallback.jl

Also fixes `empty!` and `is_empty` with universal fallback and optimizer attributes.

Add test for MOI.Silent

---

src/Bridges/indicatorbridge.jl
test/Bridges/indicator_bridge.jl

There was a method ambiguity because of the non-sub-typing in the indicator bridge definition.

fix ambiguity

---

src/Bridges/bridge.jl

This is the case for all bridges currently implemented so we might as well impose it to ensure consistency.

Specify that first argument of bridge_constraint is concrete

---

src/Bridges/slackbridge.jl
src/Test/UnitTests/basic_constraint_tests.jl
src/Utilities/functions.jl
test/Bridges/slackbridge.jl

Otherwise, the caller will get slack variables in the function that should not exists even if their terms sum to 0.

Remove variables instead of substracting it

---

src/Bridges/flip_sign_bridge.jl
test/Bridges/flip_sign_bridge.jl

See https://github.com/JuliaOpt/MathOptInterface.jl/issues/750

Test getters of func/set for flip_sign_bridge

---

src/Utilities/copy.jl
test/errors.jl

The signature was incorrect which causes `MethodError` to be thrown instead of the useful `UnsupportedConstraint` error, see https://github.com/JuliaOpt/SCS.jl/issues/145

Fix fallback load_constraint

---

src/Bridges/Constraint/det.jl
src/Bridges/Constraint/flip_sign.jl
src/Bridges/Constraint/functionize.jl
src/Bridges/Constraint/geomean.jl
src/Bridges/Constraint/interval.jl
src/Bridges/Constraint/quad_to_soc.jl
src/Bridges/Constraint/rsoc.jl
src/Bridges/Constraint/scalarize.jl
src/Bridges/Constraint/slack.jl
src/Bridges/Constraint/square.jl
src/Bridges/Constraint/vectorize.jl

See https://github.com/JuliaOpt/MathOptInterface.jl/pull/751#discussion_r287746418

[ci skip] Fix typo

---

src/Bridges/Constraint/single_bridge_optimizer.jl
src/Test/UnitTests/basic_constraint_tests.jl
src/Test/contlinear.jl
src/Test/modellike.jl

These two changes were needed to get https://github.com/JuliaOpt/Gurobi.jl/pull/216 passing.
The first is because Gurobi elects to run `infeas_certificates=false`, but still finds a partial certificate so `ResultCount` is 1.
The second is a bug. The variables need to be mapped to be valid.

Fix tests from Gurobi #216

---

Project.toml
src/Utilities/CleverDicts.jl
src/Utilities/Utilities.jl
test/Utilities/CleverDicts.jl
test/Utilities/Utilities.jl

Originally conceived and implemented here: https://github.com/JuliaOpt/Gurobi.jl/pull/216

Add CleverDicts as submodule to MOI.Utilities

---

docs/src/apimanual.md
docs/src/apireference.md
src/Benchmarks/Benchmarks.jl
src/MathOptInterface.jl
test/Benchmarks/Benchmarks.jl
test/runtests.jl

Originally conceived and implemented in https://github.com/JuliaOpt/Gurobi.jl/pull/216 and https://github.com/JuliaOpt/GLPK.jl/pull/101.

Add MOI.Benchmarks submodule to facilitate solver benchmarking

---

src/Test/UnitTests/constraints.jl
test/Test/unit.jl

Add tests for ZeroOne variables with variable bounds

---

src/Test/UnitTests/solve.jl
test/Test/unit.jl

Add unbounded example from Clp#60

---

docs/src/apimanual.md
src/Bridges/Constraint/quad_to_soc.jl
src/Test/contquadratic.jl
src/Utilities/results.jl
test/Bridges/Constraint/quad_to_soc.jl
test/Test/contquadratic.jl

I have attempted a convention for the dual and constraint values for convex programs with quadratic functions.
It seems to me that it would be inconsistent to say that the dual is the dual of the equivalent SOC formulation since the dimension depends on the choice of `A` and the constraint value has scalar dimension.

[RFC] Add dual for convex problem with quadratic

---

docs/src/apireference.md
src/attributes.jl
src/indextypes.jl

Some operations do not fall into the category of `set` such as:
* Adding heuristic solutions (https://github.com/JuliaOpt/MathOptInterface.jl/pull/670)
* Adding Lazy constraints (https://github.com/JuliaOpt/MathOptInterface.jl/pull/670)
So when a solver want to expose a solver specific feature like this, we need to create a new `add_...` function in MOI and implement it in every layer + adding a function to JuMP, ...
This PR adds a `MOI.add` function which is similar to `MOI.set` except it returns an `AttributeIndex` which is consistent with `add_variable(s)` and `add_constraint(s)`.
With this PR, if a solver want to expose, say lazy constraints, it just have to define `LazyConstraint <: MOI.AbstractOptimizerAttribute`, implement `MOI.add(::Optimizer, ::LazyConstraint, ...)` and no change …

Add MOI.submit to add attribute

---

docs/src/apimanual.md
docs/src/apireference.md
src/Benchmarks/Benchmarks.jl
src/Utilities/cachingoptimizer.jl

Solve #770 
Note that:
- this is a first attempt. If I miss anything, I welcome any feedback.
- I am not sure of the position of the `CachingOptimizer` paragraph in the page `apireference.md`: shall `CachingOptimizer` precede `Allocate-Load API`?

Add CachingOptimizer in doc

---

src/Bridges/Constraint/geomean.jl
src/Utilities/functions.jl
test/Bridges/Constraint/geomean.jl
test/Utilities/functions.jl

✨ Add vcat for SingleVariable and VectorOfVariables

---

src/constraints.jl

`CopyUnsupportedConstraint` was removed a long time ago. Extracted from #759

CopyUnsupportedConstraint -> UnsupportedConstraint

---

docs/src/apireference.md

Extracted from #759 where it's needed since it is referenced by the doc of bridges

Add get_fallback in doc

---

src/modifications.jl
test/errors.jl

Extracted from https://github.com/JuliaOpt/MathOptInterface.jl/pull/759 where the `throw_modify_not_allowed` function is used by `AbstractBridgeOptimizer`.

Test modification errors

---

docs/Project.toml
docs/src/apimanual.md

Notably transition the knapsack example to a doctest with `MockOptimizer`. More doctests are added in https://github.com/JuliaOpt/MathOptInterface.jl/pull/759.
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/780

Address TODOs

---

src/sets.jl
test/sets.jl

Defining scalar sets as 0-dimensional for broadcast seems reasonable.
cc @tweisser

Fix broadcast for scalar sets

---

src/Utilities/functions.jl
test/Utilities/functions.jl

This PR fixes two types piracies and avoid defining operation between `SingleVariable` and `Any`, defining instead operations between `SingleVariable` and `Number`.

Fix operator overload with SingleVariable

---

src/attributes.jl

It would have zero argument for `RejectSolution`, see https://github.com/JuliaOpt/MathOptInterface.jl/pull/782/, it would be weird to require the user to provide a `tuple()`

Allow arbitrary number of arguments to submit

---

docs/src/apimanual.md
docs/src/apireference.md
src/Test/UnitTests/basic_constraint_tests.jl
src/constraints.jl
src/variables.jl

Define add_constrained_variable

---

NEWS.md
docs/src/apireference.md
src/Bridges/Constraint/det.jl
src/Bridges/Constraint/geomean.jl
src/Bridges/Constraint/scalarize.jl
src/Bridges/Constraint/square.jl
src/Utilities/constraints.jl
src/constraints.jl
test/Utilities/constraints.jl

Add normalize_constant

---

src/Test/contconic.jl
src/Test/modellike.jl
test/Bridges/Constraint/flip_sign.jl
test/Bridges/Constraint/functionize.jl
test/Bridges/Constraint/interval.jl
test/Bridges/Constraint/quad_to_soc.jl
test/Bridges/Constraint/rsoc.jl
test/Bridges/Constraint/scalarize.jl
test/Bridges/Constraint/slack.jl
test/Bridges/Constraint/soc_to_psd.jl
test/Bridges/Constraint/square.jl
test/Bridges/Constraint/vectorize.jl
test/Test/Test.jl
test/Test/contconic.jl

Use `add_constrained_variable` and `add_constrained_variables` instead of `add_variable`/`add_variables` in a few tests.
Also create a new rotated SOC test.
There is no rule on whether one should use `add_variable` or `add_constrained_variable` in the tests except in some places where using `add_constrained_variable` would not work as the test use modification not supported by the bridge.
The tests are run with an SDPA model in `test/Bridges/lazy_bridge_optimizer.jl` to make sure tests don't do the wrong choice in https://github.com/JuliaOpt/MathOptInterface.jl/pull/759

Update tests with add_constrained_variable(s)

---

src/Bridges/Constraint/det.jl
src/Bridges/Constraint/flip_sign.jl
src/Bridges/Constraint/functionize.jl
src/Bridges/Constraint/geomean.jl
src/Bridges/Constraint/indicator.jl
src/Bridges/Constraint/interval.jl
src/Bridges/Constraint/quad_to_soc.jl
src/Bridges/Constraint/rsoc.jl
src/Bridges/Constraint/scalarize.jl
src/Bridges/Constraint/soc_to_psd.jl
src/Bridges/Constraint/square.jl
src/Bridges/Constraint/vectorize.jl
src/Utilities/sets.jl
test/Bridges/Constraint/det.jl

Extracted from https://github.com/JuliaOpt/MathOptInterface.jl/pull/759/

Update constraint bridges with new bridge definitions

---

src/Bridges/Bridges.jl
src/Bridges/Variable/Variable.jl
src/Bridges/Variable/bridge.jl
src/Bridges/Variable/map.jl
src/Utilities/functions.jl
test/Bridges/Variable/Variable.jl
test/Bridges/Variable/map.jl

Add Variable map

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/map.jl
test/Bridges/Constraint/Constraint.jl
test/Bridges/Constraint/map.jl

Add constraint map

---

docs/src/apireference.md
src/Utilities/functions.jl
src/sets.jl
test/Utilities/functions.jl

This also fixes a few bugs in `MOIU.operate` with quadratic terms

Add substitute_variables

---

src/Bridges/Constraint/single_bridge_optimizer.jl
src/Bridges/Constraint/slack.jl
src/Bridges/Variable/Variable.jl
src/Bridges/Variable/single_bridge_optimizer.jl
src/Bridges/bridge_optimizer.jl
src/Bridges/lazy_bridge_optimizer.jl
test/Bridges/lazy_bridge_optimizer.jl
test/Bridges/utilities.jl

Extracted from https://github.com/JuliaOpt/MathOptInterface.jl/pull/759/

Update bridge optimizers with variable bridges

---

src/Bridges/Variable/Variable.jl
src/Bridges/Variable/zeros.jl
src/Bridges/bridge_optimizer.jl
src/Utilities/functions.jl
src/attributes.jl
test/Bridges/Bridges.jl
test/Bridges/Variable/Variable.jl
test/Bridges/Variable/zeros.jl
test/Bridges/bridge_optimizer.jl
test/Bridges/utilities.jl

Extracted from https://github.com/JuliaOpt/MathOptInterface.jl/pull/759/

Add Variable.ZerosBridge

---

src/Bridges/Variable/Variable.jl
src/Bridges/Variable/flip_sign.jl
test/Bridges/Variable/Variable.jl
test/Bridges/Variable/flip_sign.jl

Extracted from https://github.com/JuliaOpt/MathOptInterface.jl/pull/759/

Add Variable.FlipSignBridge

---

src/Bridges/Variable/Variable.jl
src/Bridges/Variable/rsoc_to_psd.jl
test/Bridges/Variable/Variable.jl
test/Bridges/Variable/rsoc_to_psd.jl

Add Variable.RSOCtoPSD

---

src/Bridges/Variable/Variable.jl
src/Bridges/Variable/vectorize.jl
src/Bridges/bridge_optimizer.jl
test/Bridges/Variable/Variable.jl
test/Bridges/Variable/vectorize.jl

Also fix a bug in `bridge_optimizer.jl` caught while adding the model tests.

Add Variable.VectorizeBridge

---

src/Bridges/Variable/Variable.jl
src/Bridges/Variable/free.jl
test/Bridges/Variable/Variable.jl
test/Bridges/Variable/free.jl

 Add Variable.FreeBridge

---

src/Utilities/parser.jl
test/Utilities/parser.jl

This improves the errors obtained when parsing an incorrect string.

More detailed parser errors

---

docs/src/apireference.md
src/Bridges/bridge_optimizer.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/functions.jl
src/Utilities/mockoptimizer.jl
test/Utilities/cachingoptimizer.jl
test/Utilities/functions.jl

Refactor `mapvariables` into `map_indices`. This will also be used in `submit` once it's implemented.
Also fixes `MOI.set(::CachingOptimizer, ::MOI.ConstraintFunction, ...)` as it was not mapping the variables of the function.

Replace mapvariables by map_indices

---

docs/src/apimanual.md
docs/src/apireference.md

This allows drastic simplifications to SDOI: https://github.com/JuliaOpt/SemidefiniteOptInterface.jl/pull/30 that even questions the reason of the need to keep this SDOI layer as it is rendered trivial by constraint + variable bridges.
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/710
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/693

Add variable bridges

---

src/Utilities/functions.jl
test/Utilities/functions.jl

See https://github.com/JuliaOpt/MathOptInterface.jl/pull/818/files#r314057544

Implement operate: Vector + and / constant

---

src/Bridges/Constraint/soc_to_psd.jl
src/Utilities/functions.jl
test/Bridges/Constraint/soc_to_psd.jl
test/Bridges/lazy_bridge_optimizer.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/838
@chriscoey Also adds `operate_output_index!` methods you need for https://github.com/JuliaOpt/MathOptInterface.jl/pull/818

Fix SOC to PSD bridge

---

src/Test/modellike.jl

Current tests weren't testing the edge-case where we rename variables/constraints.
ref https://github.com/JuliaOpt/Gurobi.jl/pull/216, https://github.com/JuliaOpt/GLPK.jl/pull/101
<s>Also, it doesn't look like the `modellike.jl` tests are tested?</s>

Add extra tests to nametest

---

src/Utilities/copy.jl
test/Utilities/copy.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/849

Don't change order of variables when NLPBlock is used

---

docs/src/apimanual.md

When there is not quadratic constraints (i.e. when it's a QP but not a QCQP), things can be simplified into the form of the cone QP dual of CVXOPT.
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/828

Dual program for QPs

---

docs/src/apireference.md
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/rsoc.jl
src/Bridges/Constraint/soc_to_psd.jl
src/Bridges/Constraint/socr.jl
test/Bridges/Constraint/socr.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/637

Add SOCRBridge and disable SOCtoPSDBridge

---

src/Utilities/copy.jl
src/Utilities/mockoptimizer.jl

The change in `MockOptimizer` is to makes
https://github.com/JuliaOpt/MathOptInterface.jl/blob/6ac4e6d6ee47486062ab9a14816aca6d51328760/test/Utilities/copy.jl#L51-L58
fail and the change in `copy.jl` fixes it.
This fixes the bug reported by @lkapelevich in https://gist.github.com/lkapelevich/9942e37d9eb3cef96d6be7eb041ee838

Fix Allocate-Load copy for single variable constraints

---

src/Test/config.jl
src/Test/contlinear.jl

I tried starting to address #841. I haven't incorporated @blegat's suggestion to use a type parameter for `TestConfig` but that should be easy to change. I run into a problem, however, when trying to run the `contlinear` tests with `BigFloat`s for SDPA-GMP, which is that `Float64`'s are used internally in a few places in MOI. For example,
https://github.com/JuliaOpt/MathOptInterface.jl/blob/6ac4e6d6ee47486062ab9a14816aca6d51328760/src/Bridges/Constraint/slack.jl#L20
causes
```julia
MethodError: no method matching shift_constant(::MathOptInterface.EqualTo{Float64}, ::BigFloat)
```
in the test on line `1539` of `contlinear.jl`. I imagine this is why it's important to test with other numeric types if we want to use them with MOI! I think therefore something beyond changing the tests here is …

Generalize tests for `contlinear`

---

src/Bridges/Variable/rsoc_to_psd.jl
test/Bridges/Variable/rsoc_to_psd.jl

Required for https://github.com/JuliaOpt/MathOptInterface.jl/pull/865 as SOC of dim 2 are bridged into RSOC of dim 2.

Fix Variable/rsoc_to_psd for dimension 2

---

docs/src/apireference.md
src/Bridges/Bridges.jl
src/Bridges/Objective/Objective.jl
src/Bridges/Objective/bridge.jl
src/Bridges/Objective/map.jl
src/Bridges/bridge.jl
test/Bridges/Bridges.jl
test/Bridges/Objective/map.jl

Extracted from https://github.com/JuliaOpt/MathOptInterface.jl/pull/789/

Define objective bridge and objective map

---

docs/src/apireference.md
src/Bridges/Variable/Variable.jl
src/Bridges/Variable/bridge.jl
src/Bridges/Variable/map.jl
src/Bridges/Variable/soc_to_rsoc.jl
src/Test/contconic.jl
test/Bridges/Variable/soc_to_rsoc.jl

Currently, adding SOC variables to PSD solvers not supporting SOC is inefficient as it will go through constraint bridges and create slack variables.
This PR adds SOCtoRSOCBridge to improve the situation.
We also create a different `unbridged_map` as SOCtoRSOCBridge could not implement the current one which fallbacks on the previous one to avoid breakage for bridge implementing it.

Add Variable.SOCtoRSOCBridge

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/single_bridge_optimizer.jl
src/Bridges/Objective/Objective.jl
src/Bridges/Objective/functionize.jl
src/Bridges/Objective/single_bridge_optimizer.jl
src/Bridges/Objective/slack.jl
src/Bridges/Variable/single_bridge_optimizer.jl
src/Bridges/bridge_optimizer.jl
src/Bridges/lazy_bridge_optimizer.jl
src/Utilities/model.jl
test/Bridges/Objective/functionize.jl
test/Bridges/Objective/slack.jl
test/Bridges/Variable/zeros.jl
test/Bridges/lazy_bridge_optimizer.jl
test/Bridges/utilities.jl

Note that the base branch set is `bl/variable_bridge` but I don't plan to merge it into it, it's only set to have a small diff. This PR will only be merged once `bl/variable_bridge` is merged into master.
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/529

Add Objective bridges

---

src/Bridges/Constraint/rsoc.jl
src/Bridges/Constraint/slack.jl
src/Bridges/Variable/soc_to_rsoc.jl

Fixes https://github.com/JuliaOpt/MathOptInterface.jl/issues/876. 
I also changed `convert(T, √2)` to `√T(2)` in a few places to improve precision when `T` is a BigFloat (calculate the square-root in the BigFloat domain).

Remove some Float64 assumptions

---

src/Utilities/model.jl
test/Utilities/model.jl

It seems we were missing `Semicontinuous` and `Semiinteger` constraints when `SingleVariable` was treated differently.
Closes #879

Fix missing sets from ListOfSupportedConstraints

---

src/sets.jl
test/sets.jl

This was needed to have CDD pass `contlineartest` for `Rational{BigInt}`.
See also https://github.com/JuliaOpt/MathOptInterface.jl/issues/841

Fix == for sets with mutable fields

---

.travis.yml
src/Utilities/model.jl
test/Bridges/lazy_bridge_optimizer.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/854

Fix method ambiguity detected by Julia v1.3

---

src/Utilities/model.jl
test/Bridges/lazy_bridge_optimizer.jl

`SUPPORTED_SCALAR_SET` may be confusing, on might think it also applies to `ScalarAffineFunction` and `ScalarQuadraticFunction`

SUPPORTED_SCALAR_SET -> SUPPORTED_VARIABLE_SCALAR_SET

---

src/Utilities/model.jl
test/Utilities/model.jl

I've found myself wanting this a few times. Particular in MathOptFormat to store options. 
We currently use a `UniversalFallback` with a new `AbstractModelAttribute`, but this requires some hacking:
https://github.com/odow/MathOptFormat.jl/blob/03a8d510aed483f1d83b8fc301da468d0ef82879/src/MPS/MPS.jl#L19-L29
There were three options:
1. What we currently do.
2. Defining a new model type in MathOptFormat and forwarding all `add_constraint` etc calls to it
3. Adding this extension dict.
Thoughts? (Mainly @blegat) Am I missing an easier way?

Add extension dictionary to MOIU.Model

---

src/Utilities/model.jl
test/Utilities/model.jl

I changed my mind: I don't want the `model.ext` dict cleared on `MOI.empty!(model)`.
It's more useful to have persistent storage.

Don't empty MOIU.Model ext dict

---

docs/src/apireference.md
src/attributes.jl

This PR defines the necessary attributes and submittables for lazy and heuristic callbacks.
The docstrings are based on https://github.com/JuliaOpt/MathOptInterface.jl/pull/670.
Closes https://github.com/JuliaOpt/MathOptInterface.jl/pull/670
cc @mtanneau

Add Lazy/Heuristic MIP callbacks

---

docs/src/apireference.md
src/attributes.jl
test/errors.jl

Add InvalidCallbackUsage error

---

src/Test/UnitTests/variables.jl
src/Utilities/cachingoptimizer.jl

To delete constrained variables, you need to delete the whole vector of variables at once if the set dimension cannot change like `MOI.SecondOrderCone`. For this reason, it is important for `CachingOptimizer` to implement the deletion of vector of variables instead of relying on the fallback functions which deletes variable one by one otherwise you get the error:
```
delete_soc_variables: Error During Test at /home/blegat/.julia/dev/MathOptInterface/src/Test/config.jl:46
Got exception outside of a @test
MathOptInterface.DeleteNotAllowed{MathOptInterface.VariableIndex}: Deleting the index MathOptInterface.VariableIndex(1) cannot be performed: Cannot delete variable as it is constrained with other variables in a `MOI.VectorOfVariables`. You may want to use a `CachingOptimizer` in …
```

Fix deletion of constrained variables for CachingOptimizer

---

src/Bridges/bridge_optimizer.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/functions.jl
src/Utilities/mockoptimizer.jl
src/attributes.jl
test/Bridges/bridge_optimizer.jl
test/Utilities/cachingoptimizer.jl

This should allow callbacks to be used with JuMP in `AUTOMATIC` and `MANUAL` mode instead of `DIRECT` mode.
The only thing unsupported is submitting `HeuristicSolution` involving a bridged variable. We could try to determine the value of the solver variables given the value of the bridged variables by solving a linear system but let's keep it simple for now as currently the solvers with callbacks don't need variable bridges.

Implements submit for CachingOptimizer and AbstractBridgeOptimizer

---

docs/src/apireference.md
src/Bridges/Variable/Variable.jl
src/Bridges/Variable/rsoc_to_soc.jl
src/Bridges/Variable/soc_to_rsoc.jl
test/Bridges/Variable/rsoc_to_soc.jl
test/Bridges/lazy_bridge_optimizer.jl

Currently, SDPT3 bridges constrained variables in RSOC into constrained variables in PSD. The bridge selection cannot be blamed, the only other solution is bridging with `Constraint.RSOCBridge` and then `Constraint.VectorSlackBridge` but that's two bridges and it creates slacks so it's not obvious either for the bridge selection algo or for us humans what's the best choice. With this PR, the best choice is clearly the new `Variable.RSOCtoSOCBridge` as it is only one bridge and it does not create any new slack variables :tada: It is added before the `Variable.RSOCtoPSDBridge` in `add_all_bridges` so that it is preferred as both bridging possibilities only use one bridge so they are tied.

Add Variable.RSOCtoSOCBridge

---

src/Bridges/Constraint/bridge.jl
src/Bridges/Constraint/flip_sign.jl
src/Bridges/Constraint/functionize.jl
src/Bridges/Constraint/map.jl
src/Bridges/Constraint/scalarize.jl
src/Bridges/bridge_optimizer.jl
test/Bridges/Constraint/flip_sign.jl
test/Bridges/Constraint/functionize.jl
test/Bridges/Constraint/scalarize.jl
test/Bridges/lazy_bridge_optimizer.jl

Fix bug caught by @odow in https://github.com/JuliaOpt/GLPK.jl/pull/120/files#r330827511
This adds the requirements for constraint bridges to implement `MOI.delete(::ModelLike, BridgeType, ::IndexInVector)` for `VectorOfVariables`-in-`S` constraints where `MOI.supports_dimension_update(S)` is `true`.

Fix deletion of variables in bridged VectorOfVariables constraints

---

src/Test/UnitTests/solve.jl
src/Utilities/mockoptimizer.jl
src/attributes.jl

It's difficult to pass both `MOIT.solve_result_index` and `MOIT.default_status_test` without this change.

PrimalStatus/DualStatus should be NO_SOLUTION if `result_index` is out of bounds

---

src/Test/UnitTests/basic_constraint_tests.jl

Mosek does not support 2.0 as power.

Use 0.5 instead of 2.0 for power in PowerCone in `basic_constraint_test`

---

src/Test/nlp.jl
test/Test/nlp.jl

I stay at your disposal if you want to add other MPEC tests inside MOI

Add QP complementarity test

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/functionize.jl
test/Bridges/Constraint/functionize.jl

Also allows custom attributes to be supported by such bridges via the new `invariant_under_function_conversion` function.

Add support for starting values for functionize bridges

---

src/Test/UnitTests/solve.jl
src/Test/config.jl
src/Test/contconic.jl
src/Test/contlinear.jl

Some solvers support dual value for the constraints but not for the objective (e.g. Ipopt).

Add dual_objective_value option to config

---

docs/src/apireference.md
src/Test/UnitTests/basic_constraint_tests.jl
src/Test/nlp.jl
src/Utilities/model.jl
src/sets.jl
test/Test/Test.jl
test/Test/nlp.jl

This PR adds the set `Complements(dimension)` which defines a mixed complementarity constraint.
The main targets are 
- [KNITRO.jl](https://github.com/JuliaOpt/KNITRO.jl), which will implement `VectorOfVariables-in-Complements` (cc @frapac)
- [PATH.jl](https://github.com/odow/PATH.jl), which will implement `VectorQuadraticFunction-in-Complements` and `VectorAffineFunction-in-Complements`, implementing both allows us to short-circuit the Jacobian evaluation the affine case. `VectorOfVariables-in-Complements` will be handled by bridges.
Closes #771 
I've left more obscure complementarity constraints, like conic constrained `x` compared to `lb <= x <= ub`, un-mentioned. @frapac does KNITRO just look at the bounds? Or does it do something different?
cc @xhub

Add complementarity constraints

---

src/Utilities/functions.jl
src/Utilities/mockoptimizer.jl
test/Bridges/bridge_optimizer.jl
test/Utilities/cachingoptimizer.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/926

No index mapping nor substitution for ModelLike

---

src/Bridges/Variable/map.jl
src/Bridges/bridge_optimizer.jl
test/Bridges/Variable/map.jl
test/Bridges/lazy_bridge_optimizer.jl

As the variable bridges substitute user (bridged) variables into
solver variables, the solver and the bridges that are created by this bridge are
using the solver variables while the user and other bridges are using
the user variables.
Before this commit, the solver variables where substituted for the user
variables even when the call was coming from a bridge that was created
(directly or indirectly) by the bridge that created these variables.
This causes issues if the call was for getting a function which should
then be converted into a VectorOfVariables as even if it is a
VectorOfVariables in terms of the solver variables, it may not be a
VectorOfVariables in terms of the user variables.

Add variable indices context to variable bridges

---

src/Test/intlinear.jl
test/Test/intlinear.jl

There was no test such that:
```
y in {0,1}
y -> a^T x + b in Set
```
with `b != 0`, this additional test is equivalent to the first indicator test, with a part of the RHS shifted to the constant term

Testing constant term in indicator constraint

---

docs/src/apireference.md
src/Bridges/lazy_bridge_optimizer.jl
test/Bridges/lazy_bridge_optimizer.jl

This PR fixes the performance of the following use case (which is in fact the case of SumOfSquares).
Suppose JuMP is extended by a new type of constraints with bridges. So `JuMP.build_constraint` return, say, `M` nested `BridgeableConstraint`, one for each bridge that should be added.
JuMP will then call `MOIB.add_constraint` for each bridge.
So if then the user do
```julia
for i in 1:N
@constraint(model, func in extension_set)
end
```
The issue here is that since `add_bridge` does not check whether a bridge has already been added, there will be `N * M` bridges at the end.
Furthermore, since Bellman-Ford is re-run everytime a bridge is added, it will be run `N * M` times while here it should be run only once!
With large enough `N` and `M`, this can take a non-neglibible time in model …

Lazy add_bridge

---

src/Bridges/Constraint/slack.jl
test/Bridges/Constraint/slack.jl

Add support for starting values for slack bridges

---

src/Bridges/lazy_bridge_optimizer.jl

This fixes the segfault on Julia v1.0 of https://github.com/JuliaOpt/MathOptInterface.jl/pull/877
This also give an impressive performance improvements for the benchmark added in https://github.com/JuliaOpt/MathOptInterface.jl/pull/946. This performance improvement might be explained by https://github.com/JuliaLang/julia/issues/32761
On master:
```
BenchmarkTools.Trial: 
memory estimate:  269.80 KiB
allocs estimate:  4658
--------------
minimum time:     11.074 ms (0.00% GC)
median time:      11.251 ms (0.00% GC)
mean time:        11.761 ms (1.45% GC)
maximum time:     61.752 ms (79.61% GC)
--------------
samples:          425
evals/sample:     1
BenchmarkTools.Trial: 
memory estimate:  715.16 KiB
allocs estimate:  12004
--------------
minimum time:     41.166 ms (0.00% GC)
median time: …
```

Fix segfault of #877

---

src/Bridges/bridge_optimizer.jl
test/Bridges/lazy_bridge_optimizer.jl

All the tests with `add_constraints` we had were run on model that needed the constraint to be bridged which allowed this bug to slip through.

Fix add_constraints with non-bridged variable constraint on bridged variable

---

perf/bellman_ford.jl
src/Bridges/Constraint/square.jl
src/Bridges/debug.jl
src/Bridges/graph.jl
src/Bridges/lazy_bridge_optimizer.jl
test/Bridges/lazy_bridge_optimizer.jl

Most of the time spent in the bridge shortest path algorithm is due to the type instability of bridge types accessed from the vector of bridges added to the `LazyBridgeOptimizer`.
Indeed, we then need to call `supports_constraint`, `concrete_bridge_type` and `added_...` to the bridge type and the method lookup needs to be done at runtime because the bridge type is not known at compile time.
In this PR, the subpart of the bridge graph is constructed so that the Bellman-Ford algorithm is run on a fully type-stable graph structure.
The graph is built lazily when `node` is called for new types.
Of course, the type instability still affects the `node` functions but once the graph is build, the time to run Bellman-Ford is negligible.
Running the `perf/bellman_ford.jl` benchmark gives which …

Build bridge graph to improve performance of bridge shortest path

---

src/attributes.jl

As mentioned in the docstrings:
https://github.com/JuliaOpt/MathOptInterface.jl/blob/fa4e026106a8909bd37d6a2e2e3e9fecf4534b5a/src/MathOptInterface.jl#L61-L74
https://github.com/JuliaOpt/MathOptInterface.jl/blob/fa4e026106a8909bd37d6a2e2e3e9fecf4534b5a/src/attributes.jl#L10-L12
The difference between model and optimizer attributes is that model attributes are discarded at `MOI.empty!` and are not copied at `MOI.copy_to`.
This should resolve the issue of callbacks not working in non-direct mode with JuMP. The issue was that GLPK discarded the callback in `MOI.empty!` but then did not receive it again in `MOI.copy_to`.
This does not closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/958 as we should clarify in the docstring of `MOI.copy_to` that optimizer attributes are not …

Callbacks are model attributes

---

src/Bridges/Constraint/geomean.jl

I am guessing one of the `x_{21}`s in the final constraint in the description of the geomean bridge supposed to be `x_{12}`?

fix tiny typo in geomean bridge docs

---

src/Bridges/Constraint/geomean.jl
src/Test/contconic.jl
test/Bridges/Constraint/geomean.jl
test/Test/contconic.jl

On MOI master I get:
```julia
using JuMP
using MosekTools
n = 9
v = collect(1:n)
model = Model(with_optimizer(Mosek.Optimizer))
@variable(model, t)
@objective(model, Max, t)
@constraint(model, vcat(t, v) in MOI.GeometricMeanCone(n + 1))
optimize!(model)
objective_value(model)
prod(v)^(1 / n)
julia> objective_value(model)
2.6771584679712452
julia> prod(v)^(1 / n)
4.147166274396913
```
A test problem needs more than eight variables in the geomean to trigger this.

fix incorrect increment in geomean bridge

---

docs/src/apireference.md
src/Utilities/functions.jl
src/Utilities/model.jl
test/Utilities/model.jl

When several variables are deleted, instead of doing one pass through each function for each variables, we do only one pass for all variables and use the set of variable indices to determine in O(1) whether a variable should be removed or not.
If N is the number of variables deleted and M is the number of terms in all the functions of the model, the complexity before the PR is O(N * M) and it is O(M) after the PR.

Faster deletion of vector of variables

---

src/Bridges/Constraint/set_map.jl

Remove duplicate computation in bridges

---

docs/src/apireference.md
src/indextypes.jl

Related to https://github.com/JuliaOpt/MathOptInterface.jl/pull/989

properly document batch deletion

---

src/Bridges/Constraint/norm_to_lp.jl
test/Bridges/Constraint/norm_to_lp.jl

Implement starting values for NormOneBridge

---

docs/src/apimanual.md

See the removal of `with_optimizer` in JuMP: https://github.com/JuliaOpt/JuMP.jl/pull/2090.

don't recommend passing optimizer attributes to constructors

---

src/Test/UnitTests/modifications.jl
test/Test/unit.jl

Contribution based in a discussion with @odow and @mlubin. I think the tests may cover more cases but will wait suggestions. Looking at the other tests seem like the style of choice is keeping things simple.
The gist of this contribution is that MOI.delete taking a vector may be specialized to be 'smarter' (i.e., not O(n^2) in some situations as it is now) but this 'smarter' code needs extra tests.

Tests for vector specialized version of MOI.delete

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl

This is a little embarrassing that I didn't notice this earlier.
Closes https://github.com/odow/MathOptFormat.jl/issues/101

[FileFormats] Fix free variables in LP writer

---

src/Test/contconic.jl
test/Test/contconic.jl

Add PSD test with offdiagonal constant. This would have caught the bug fixed by https://github.com/JuliaOpt/SCS.jl/pull/171/

Add PSD3 test

---

docs/src/apimanual.md
docs/src/apireference.md
src/Test/contconic.jl
src/constraints.jl
src/variables.jl
test/Utilities/model.jl

See https://github.com/JuliaOpt/MathOptInterface.jl/issues/987

Add supports_constrained_variable(s)

---

src/Bridges/Constraint/interval.jl
src/Bridges/graph.jl
test/Bridges/Constraint/interval.jl
test/Bridges/bridge_optimizer.jl
test/Bridges/lazy_bridge_optimizer.jl

This would allow solvers in geometric conic form to support ScalarAffineFunction-in-EqualTo and VectorAffineFunction-in-Zeros constraints.

Add support for EqualTo and Zero in Split bridge

---

.travis.yml
src/Utilities/functions.jl
test/Bridges/Variable/vectorize.jl
test/Utilities/copy.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/1000

Fix tests for Julia v1.4-rc1

---

src/Test/UnitTests/modifications.jl

Tulip fails the test with `==`:
https://travis-ci.com/blegat/SolverTests/jobs/281969934

Approximate check in delete in batch test

---

src/Test/contconic.jl

This clarifies that https://github.com/JuliaOpt/MosekTools.jl/issues/44 is a Mosek bug

Clarify dual solution of pow1

---

src/sets.jl

It can be obtained from the bridge to exponential cone.
[I 0]^(-1) * RelEntr = [A B]^(-1) [Exp1 x ... x Expn x R+]
so
[I; 0] * RelEntr* = [A'; B'] * [Exp1* x ... x Expn* x R+]
B' * R+ = 0 says that the u_i are all equal.
Then A' * [Exp1* x ... x Expn*] gives the dual exponential cone constraints with the same u_i

Add dual in RelativeEntropyCone docstring

---

src/Utilities/copy.jl

The comma doesn't do what I expected:
```julia
julia> @warn("a", "b")
┌ Warning: a
│   b = "b"
└
```

Fix warning of unsuppoted attribute

---

src/Utilities/model.jl
test/Utilities/model.jl

One potential fix for #1030 
Pros: this passes tests and is simple.
Cons: 
- we don't define `optimize!`, which might violate the contract of `AbstractOptimizer`. 
- Can this break code? 
I don't think it breaks any of mine. I'm also not aware of any code that assumes that a `@model` is `<: ModelLike`, but not `<: AbstractOptimizer`.
Alternative fix for #1030
Adds a flag to switch between `MOIU.AbstractModelLike` and `MOIU.AbstractOptimizer`.
Pros: flexible.
Cons: will this break code that uses `MOIU.AbstractModel{T}`?

Make AbstractModel <: AbstractOptimizer

---

src/sets.jl

According to https://github.com/JuliaOpt/MathOptInterface.jl/pull/1017#discussion_r376703101, the dual of the GeometricMeanCone is the set of `(u, v)` such that there exists `b < 0` and `d_i` such that `sum(d_i) = u` and
`-b exp(d_i/b) <= exp(1) v_i` for all `i`.
Multiplying them all gives
`(-b)^n exp(u/b) <= exp(1)^n prod(w_i)` (1)
Let `k` such that `exp(k)= exp(1) sqrt[n](prod(w_i))` and `a = -b >= 0`
We have
`-u <= a * (n*k - n * log(a))`.
The maximum of the rhs is for `a = exp(k - 1)`.
Injecting this value of `a` in (1), we have
`exp(u / (n * b)) <= exp(1)`
hence
`-u <= -n * b`
and simplifying gives `-u <= n * sqrt[n](prod(w_i))`.

Add dual of GeometricMeanCone

---

Project.toml

BenchmarkTools made a semver-breaking release although did not really break anything (just removed Julia 0.7 support and added features).
I could make a PR to add CompatHelper support if that would be desired.

Bump BenchmarkTools version

---

docs/src/apimanual.md
src/instantiate.jl

As discussed during the JuMP-dev hangout, this would test that the optimizer is a subtype of `MOI.AbstractOptimizer`.

Update test template with instantiate

---

src/FileFormats/MOF/nonlinear.jl
src/FileFormats/MOF/write.jl
test/FileFormats/MOF/nlp.mof.json
test/FileFormats/MOF/nonlinear.jl

Two bugs:
1. We were still assuming `NLPBlock` used `x[1]` instead of `x[VariableIndex(1)]`
2. NLP objectives were being overwritten by empty linear/quadratic ones because the JSON file for the test was wrong :(

[MOF] fix writing NLPBlock

---

src/Test/intlinear.jl
test/Test/intlinear.jl

I've added some tests for semi-continuous and semi-integer variables.
It's a simple model:
min x 
st   x >= y
x ∈ {0.0} U [2.0,3.0]
y = 0.0
And changed the fixed value of y to see the result.
I've tested on both CPLEX and Xpress solvers.

Add tests for semi continuous and semi integer variables

---

src/Bridges/debug.jl
test/Bridges/lazy_bridge_optimizer.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/1062

[Bridges] Fix StackOverflow in debug

---

src/Bridges/Variable/flip_sign.jl
test/Bridges/Variable/flip_sign.jl

Adding a get function to for `MOI.ConstraintSet` attribute for `FlipSignBridge` . Test is also added.

Adding get function for MOI.ConstraintSet for NonposToNonnegBridge

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/semi_to_binary.jl
src/Utilities/functions.jl
test/Bridges/Constraint/semi_to_binary.jl

Add semi integer/continuous bridges

---

src/FileFormats/SDPA/SDPA.jl
test/FileFormats/SDPA/SDPA.jl

I missed the `-` in front of `F0` in the line `X=F1x1+F2x2-F0` of http://plato.asu.edu/ftp/sdpa_format.txt

[SDPA] Add missing negation of constant

---

src/FileFormats/SDPA/SDPA.jl
test/FileFormats/SDPA/SDPA.jl

An entry `a` for an offdiagonal entry 1, 2 corresponds to exactly `a` for an the index 2 of PositiveSemidefiniteConeTriangle. I started from the dual version for writing the SDPA format where we should divide by 2 because it's counted twice but I forgot to remove this part.
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/1071

[SDPA] No scaling of off-diagonal coefficient

---

src/FileFormats/FileFormats.jl
src/FileFormats/SDPA/SDPA.jl
test/FileFormats/SDPA/SDPA.jl
test/FileFormats/SDPA/models/example_A.dat-s

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/1073

[SDPA] Ignore comments aftere m and nblocks and detect dat-s extension

---

src/FileFormats/SDPA/SDPA.jl
test/FileFormats/SDPA/SDPA.jl
test/FileFormats/SDPA/models/example_integer.sdpa

I have added a feature to read/write integer restrictions on single variables. This resolves #1074.
@blegat @odow, it would be great if you can review this PR.
The feature is based on the extension in http://www.opt.tu-darmstadt.de/scipsdp/downloads/data_format.txt and should be backward compatible.

Feature to read/write integer constraints

---

docs/src/apimanual.md

The only solver having a separate package is Mosek and the separate package is MosekTools so it seems fair to say that we do not recommend this anymore.

Remove recommendation to call package MathOptInterfaceXXX

---

src/Utilities/cachingoptimizer.jl

Resolves #1083 
I have not added any tests yet as I am not sure where it would be best to do so. The "CachingOptimizer MANUAL mode" testset includes adding constraints after the optimizer has been attached, so it could be tested for there.

Fix add_constrained_variable(s) for a CachingOptimizer with an attached optimizer

---

src/Bridges/Constraint/norm_to_lp.jl
src/Test/contconic.jl
test/Bridges/Constraint/norm_to_lp.jl
test/Test/contconic.jl

as discussed with @blegat. I have similar fixes incoming for some other bridges that use `MOIU.normalize_and_add_constraint` but I want to get this merged before I make those PRs.

add L1/Linf cone tests and fix bridge when VAF has nonzero constants

---

test/Utilities/functions.jl

Add tests for the implementation of `is_canonical` for quadratic functions that was added in https://github.com/JuliaOpt/MathOptInterface.jl/pull/1081

Add tests for is_canonical on quadratic functions

---

src/Utilities/universalfallback.jl
test/Utilities/universalfallback.jl

Quick prototype that resolves #1085 
Tests are missing.

Add support for custom objective functions in UniversalFallback.

---

src/Bridges/Constraint/scalarize.jl
src/Test/UnitTests/modifications.jl
test/Bridges/Constraint/scalarize.jl

I found a small bug in ScalarizeBridge. This should fix it.

Bugfix for set ConstraintFunction in ScalarizeBridge.

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/map.jl
test/Bridges/bridge_optimizer.jl

In the definition of `ListOfConstraintIndices`, we require the indices to be returned in order of creation, that was violated for the constraint bridges with function of type `SingleVariable` or `VectorOfVariables`.
Might fix the failing test of https://github.com/jump-dev/MathOptInterface.jl/pull/1099/

Fix order ListOfConstraintIndices with constraint bridges on variable function

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/failing_models/rows_duplicate_2.mps
test/FileFormats/MPS/failing_models/sos.mps

- Function barriers for type-unstable hot loops
- Deterministic ordering of rows/columns (Closes #1106)
- Remove TempRow and TempColumn in favor of vectors
- Use Int instead of String in coef matrix for lower memory usage
<s>Will post before/after benchmarks reading MIPLIB soon.</s>
Still todo:

Various improvements to the FileFormats.MPS subpackage

---

src/FileFormats/MOF/MOF.jl
src/FileFormats/MOF/nonlinear.jl
src/FileFormats/MOF/read.jl
src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl
test/FileFormats/MOF/nonlinear.jl

- Disable validation by default. Large models are excessively slow
- Only pass `model` argument if necessary
- Style fixes
Here are the same benchmarks as https://github.com/jump-dev/MathOptInterface.jl/pull/1109#issuecomment-651190353. Almost all the time is in the JSON reader/writer, so I am investigating alternative packages, e.g., <s>https://github.com/quinnj/JSON2.jl</s>https://github.com/quinnj/JSON3.jl.
```
Benchmarking bab2.mof.json.gz
28.975040 seconds (93.25 M allocations: 5.337 GiB, 28.06% gc time)
7.827851 seconds (28.08 M allocations: 1.426 GiB, 7.81% gc time)
17.103940 seconds (62.18 M allocations: 3.096 GiB, 29.77% gc time)
Benchmarking irish-electricity.mof.json.gz
8.547113 seconds (29.20 M allocations: 1.702 GiB, 26.35% gc time)
1.840084 seconds (6.03 M allocations: …
```

Various improvements to the FilesFormats.MOF subpackage.

---

src/Utilities/lazy_iterators.jl

The function type should be in a type argument (similarly to `Base.Generator`)

Faster LazyMap

---

src/Utilities/results.jl

If `T` is mutable (such as `BigInt` and `BigFloat`), this should be faster as it will modify `result` to contain the result.

Improve triangle_dot with MA

---

docs/src/apireference.md
src/Bridges/bridge.jl
src/FileFormats/MOF/MOF.jl
src/Utilities/functions.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
src/attributes.jl
test/Bridges/Constraint/rsoc.jl
test/Utilities/mockoptimizer.jl
test/Utilities/model.jl
test/Utilities/universalfallback.jl

For models that knows that the constraint function is already canonical they can just
```julia
function MOI.get(model::ModelType, ::Union{MOI.ConstraintFunction, MOI.CanonicalConstraintFunction}, ci)
...
end
```
For `MOI.Utilities.Model`, the function are not canonicalized when added (should we ?) so we canonicalize them then `CanonicalConstraintFunction` is called to spare the `copy` that is done in `MOI.Utilities.canonical` as it can slows things down dramatically (see https://github.com/jump-dev/SCS.jl/issues/186).
Alternatively, we could say that the functions added to `MOI.Utilities.Model` are automatically canonicalized in addition of being copied by replacing this `copy(f)` by `canonical(f)`:
https://github.com/jump-dev/MathOptInterface.jl/blob/26e0af44a254b545276b528298a390d34c3785 …

[RFC] Add CanonicalConstraintFunction attribute

---

src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/dense_dict.jl
test/Utilities/dense_dict.jl

Improves:
- dense dict type stability 
- indexmap copying and reversing in attach optimizer
cc @blegat

Improve indexing performance

---

src/Bridges/lazy_bridge_optimizer.jl

Extracted from #1130
Key line is the `generate` in `SCS MOI scalar`. Drops from 130 ms to 85 ms.
```
──────────────────────────────────────────────────────────────────────────
Time                   Allocations      
──────────────────────   ───────────────────────
Tot / % measured:          1.48s / 44.8%            269MiB / 100%     
Section           ncalls     time   %tot     avg     alloc   %tot      avg
──────────────────────────────────────────────────────────────────────────
SCS MOI scalar         1    355ms  53.4%   355ms    140MiB  51.9%   140MiB
solve                1    224ms  33.8%   224ms   85.9MiB  31.9%  85.9MiB
generate             1    130ms  19.6%   130ms   53.9MiB  20.0%  53.9MiB
GLPK MOI vector        1    106ms  16.0%   106ms   44.3MiB  16.4%  44.3MiB
solve …
```

Improve performance of LazyBridgeOptimizer

---

src/Utilities/DoubleDicts.jl
src/Utilities/Utilities.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/dense_dict.jl
test/Utilities/DoubleDicts.jl

Following #1129
This PR applies dictionary reversion directly do double dicts.
Now it is type stable and more performant.

Double dict reversion

---

src/Test/UnitTests/basic_constraint_tests.jl

It would be helpful to use these tests for Ipopt but it does not support names

Add name option for basic_constraint_test

---

docs/make.jl
docs/src/apimanual.md
docs/src/index.md
perf/cachingoptimizer.jl
src/Bridges/Constraint/geomean.jl
src/Bridges/Constraint/square.jl
src/Bridges/Constraint/vectorize.jl
src/Bridges/Variable/vectorize.jl
src/Test/contconic.jl
src/Test/modellike.jl
src/Utilities/functions.jl
src/Utilities/universalfallback.jl
src/functions.jl

Some links to `JuliaOpt` domains have not been changed, namely:
* [`News.md`](https://github.com/jump-dev/MathOptInterface.jl/blame/372cb21432c80e932a2c2323a23e6bd55c26f648/NEWS.md#L426): the [original link](http://www.juliaopt.org/JuMP.jl/latest/style.html) is broken
* All references to `JuliaOpt/MathProgBase.jl`: it looks like MPB is not in the jump-dev GitHub organization
* Gitter URLs in README: they are still of the form `JuliaOpt/jump-dev`
* URLs that appear in [`src/FileFormats/MOF/v0.4.0.json`](https://github.com/jump-dev/MathOptInterface.jl/blob/372cb21432c80e932a2c2323a23e6bd55c26f648/src/FileFormats/MOF/v0.4.0.json): I don't know what this file is for, and I was afraid I would break something

Update URLs to jump-dev

---

src/Benchmarks/Benchmarks.jl
src/Utilities/copy.jl
test/Utilities/copy.jl

In line with #1035, a first step to allow a common interface for conflicts (exporting just these constraints). Copying the relevant constraints is a more flexible way to get to that point.

When copying a model, propose to only keep conflict constraints.

---

src/Bridges/Constraint/map.jl
src/Bridges/Constraint/single_bridge_optimizer.jl
src/Bridges/Variable/single_bridge_optimizer.jl
src/Bridges/bridge_optimizer.jl
src/Bridges/debug.jl
src/Bridges/graph.jl
src/Bridges/lazy_bridge_optimizer.jl
src/Utilities/copy.jl
test/Bridges/Constraint/map.jl
test/Bridges/Variable/zeros.jl
test/Bridges/bridge_optimizer.jl
test/Bridges/lazy_bridge_optimizer.jl
test/Utilities/copy.jl

There is an issue with the fact that there may be a clash between constraint indices between bridged constraint and solvers constraints of type `VectorOfVariables` or `SingleVariable`.
Indeed for instance if variables constrained on creation in `S` are supported but not `VectorOfVariables`-in-`S` constraints then there may be a clash between a constraint index `VectorOfVariables`-in-`S` that was created with a variable constrained on creation and a bridged `VectorOfVariables`-in-`S` constraints.
The solution would be to recommend the index value of `VectorOfVariables`-in-`S` constraints to be equal to the index of the first variable (this is already the case for most solvers) so that when there is a clash, it's when the same variable is the first one of two conic variable constraint so …

Implementing bridge cost

---

src/FileFormats/MOF/MOF.jl
src/FileFormats/MOF/mof.0.5.schema.json
src/FileFormats/MOF/nonlinear.jl
src/FileFormats/MOF/read.jl
src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl
test/FileFormats/MOF/empty_model.mof.json
test/FileFormats/MOF/failing_models/blank_variable_name.mof.json
test/FileFormats/MOF/failing_models/missing_variable_name.mof.json
test/FileFormats/MOF/failing_models/unsupported_constraint_function.mof.json
test/FileFormats/MOF/failing_models/unsupported_constraint_set.mof.json
test/FileFormats/MOF/failing_models/unsupported_objective_function.mof.json
test/FileFormats/MOF/failing_models/unsupported_objective_sense.mof.json
test/FileFormats/MOF/nlp.mof.json
test/FileFormats/MOF/nonlinear.jl
test/FileFormats/MOF/v0.4.mof.json

x-ref: https://github.com/jump-dev/MathOptFormat/pull/14

Update to MathOptFormat v0.5

---

.travis.yml
src/Bridges/debug.jl
test/Bridges/lazy_bridge_optimizer.jl

More consistent behavior between `print_graph` and `debug`. Also adds the possibility to see why nodes are not supported in `print_graph`

Refactor Bridges debug

---

src/Utilities/CleverDicts.jl
test/Utilities/CleverDicts.jl

OSQP is comparing a `CleverDict` with a `Dict` which requires `CleverDict` to implement `get` which is part of the `AbstractDict` API, see
https://travis-ci.com/github/blegat/SolverTests/jobs/380241593#L549-L565

Implement get for CleverDict

---

src/Utilities/DoubleDicts.jl
test/Utilities/DoubleDicts.jl

See https://github.com/jump-dev/MathOptInterface.jl/pull/1153#issuecomment-687324264

Implement get for DoubleDict

---

src/Utilities/CleverDicts.jl
test/Utilities/CleverDicts.jl

Remove invalid type assertion in CleverDicts

---

src/Test/contconic.jl

Mosek returns dual values that do not satisfy the current tests although they are correct. See https://travis-ci.org/github/jump-dev/MosekTools.jl/jobs/727649211#L374-L389
This PR relaxes the tests so that it passes the tests.

Fix dual check for norminf3 test

---

src/Test/intlinear.jl

Without this PR, with Mosek, I get:
```
semiconttest: Test Failed at /home/blegat/.julia/dev/MathOptInterface/src/Test/intlinear.jl:810
Expression: MOI.get(model, MOI.ObjectiveBound()) <= 3.0
Evaluated: 3.0000000000000004 <= 3.0
Stacktrace:
[1] _semitest(::MathOptInterface.Bridges.LazyBridgeOptimizer{MosekModel}, ::MathOptInterface.Test.TestConfig{Float64}, ::Bool) at /home/blegat/.julia/dev/MathOptInterface/src/Test/intlinear.jl:810
[2] semiconttest(::MathOptInterface.Bridges.LazyBridgeOptimizer{MosekModel}, ::MathOptInterface.Test.TestConfig{Float64}) at /home/blegat/.julia/dev/MathOptInterface/src/Test/intlinear.jl:823
[3] macro expansion at /home/blegat/.julia/dev/MathOptInterface/src/Test/config.jl:48 [inlined]
[4] macro expansion at …
```

Use tolerance for objective bound tests

---

src/Utilities/CleverDicts.jl
test/Bridges/lazy_bridge_optimizer.jl

This is quite a big issue and will require to tag MOI v0.9.17 asap as it will break whenever a variable bridge is used with combination of a CachingOptimizer. It was not detected in the solver tests as the CachingOptimizer as an inner model of the bridges so it does not see any negative indices. However, it is triggered for the cache used by JuMP to hold the non-bridged model so the breakage happens for almost any JuMP model with solvers using variables bridges such as CSDP, SDPA, ...
In short, reproducing the error is as easy as
```julia
julia> using JuMP, CSDP
julia> model = Model(CSDP.Optimizer)
A JuMP Model
Variables: 0
Solver name: CSDP
julia> @variable(model, x)
x
ERROR: …
```

Remove error of CleverDict for negative indices

---

src/Utilities/CleverDicts.jl
test/Utilities/CleverDicts.jl

When negative indices are set, we should set `last_index` to `-1` so that `add_item` throws an error. @joaquimg 
also notified me about the edge case when `last_index` is `-1` and `h` is `0` where we have `h == last_index + 1`.

Fix CleverDict with negative indices

---

src/Utilities/functions.jl
test/Utilities/functions.jl

It's needed for `set_optimizer_attribute` with NLopt as the value of some parameters are symbols.

Add support for Symbol's in map_indices

---

src/attributes.jl

x-ref: https://github.com/jump-dev/GLPK.jl/issues/146
GLPK sometimes asks for a lazy constraint at an integer-infeasible point. We can either tweak these docs to drop the mention of primal feasibility, or tweak GLPK to check for integer feasibility before asking for a lazy constraint.

Tweak wording of LazyConstraintCallback docs

---

src/Utilities/mutable_arithmetics.jl
test/Utilities/mutable_arithmetics.jl

Operations with `SingleVariable` with MA was less tested which let this slip through

Implement mutable_operate with add_mul and SingleVariable

---

src/Test/modellike.jl
src/attributes.jl
test/Test/modellike.jl

Intends to close #2237 and some related open issues (#649, #794, #853).
Some guidance is needed. For now, I just edited what I found to be the relevant piece of documentation, and added a new tests as well flags to an old test (allowing more granular selection of which attributes are tested). I would like to know:
1. There are other places where the documentation needs to be changed? `JuMP` probably will need a change, but there are other points inside MOI?
2. Seems to me that allowing `nothing` to be passed is something done at the wrapper level, and the generic methods in MOI already allow it. The test will probably force the wrappers to allow this behavior.
3. How is the best way to check if the test is working? Should I download a bunch of wrappers and make they use my version of MOI, …

Fixing `set_start_value` only accept numbers (#2237)

---

src/Test/contlinear.jl

I noticed linear9 failed when I ran with BigFloat in Hypatia

fix some real types in contlinear tests

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl

This fixes a bug, because stricter MPS readers like the one in Cbc
distinguish between the variable name "x" and " x" with a leading
space. This caused a segfault in a model sent to me by a user.
This also changes the logic, so that binary variables only get
associated bounds if the bounds are tigher than [0, 1], which Cbc
also complained about.

Use a Card struct when writing MPS files

---

src/Bridges/Constraint/interval.jl
src/Bridges/Constraint/scalarize.jl
src/Bridges/Constraint/slack.jl
src/Utilities/functions.jl
test/Bridges/lazy_bridge_optimizer.jl

When adding the complex bridges defined in [ComplexOptInterface](https://github.com/blegat/ComplexOptInterface.jl), the `LazyBridgeOptimizer` tries to bridge the complex constraints with the real bridges and then fails with cryptic errors. With this PR, it realizes that the real bridges do not support bridging the complex constraints hence it allows `LazyBridgeOptimizer` to select the complex bridges.

Fix wrong coefficient type with bridges

---

README.md

(current url points to an extra step for redirection)
This will need to be rebased after the merge of #1186 (or 1186 rebased after this PR, whichever is merged first)

update travis badge urls from travis-ci.org to travis-ci.com

---

src/Test/UnitTests/solve.jl
test/Test/unit.jl

Related to https://github.com/jump-dev/MathOptInterface.jl/issues/441
I followed the instructions in issue 441 (by odow) to create this PR + added 2 changes
- travis badge links updated to travis-ci.com instead of travis-ci.org (currently the badge goes to an extra redirect page)
- added a new page in the docs about testing. I think this needs some more revision, but I just wanted to get your opinion first about having such a page in the docs. It's basically the same instructions as odow laid out in the issue. I think that it'd be a good documentation for how the testing works (I personally wasn't expecting that the optimizers ran tests from the MOI package), as well as tests being tested, and where to plug in stuff in order to add a new test. Let me know if you think it's a bad idea.
I …

issue 441: unit test for double optimize

---

docs/make.jl
docs/src/index.md
docs/src/testing.md

This was split out from PR #1186. Here's a copy of my original PR description:
- added a new page in the docs about testing. I think this needs some more revision, but I just wanted to get your opinion first about having such a page in the docs. It's basically the same instructions as odow laid out in the issue. I think that it'd be a good documentation for how the testing works (I personally wasn't expecting that the optimizers ran tests from the MOI package), as well as tests being tested, and where to plug in stuff in order to add a new test. Let me know if you think it's a bad idea.
Oscar had made a first revision there as well, which is already incorporated in this PR at this stage.
This PR might need to be rebased if PRs #1186 and #1188 (or others) are merged first.

Add a new docs page about testing in the package

---

docs/src/apireference.md
src/attributes.jl
test/attributes.jl

Add CallbackNodeStatus attribute

---

.github/workflows/documentation.yml
docs/make.jl
docs/src/apireference.md
src/Bridges/Constraint/bridge.jl
src/Bridges/Variable/bridge.jl

Required for JuMP: https://github.com/jump-dev/JuMP.jl/pull/2393/files#r535004411. Should have been done anyway.

Enable doctests and correct previously untested errors

---

src/Utilities/functions.jl
test/Utilities/functions.jl

`findall` is eager, so is `map`, chaining the two functions should be done only once to avoid going through the terms twice.
Addressing issue noticed in:
https://github.com/jump-dev/MathOptInterface.jl/issues/1137

change findall into for comprehension

---

src/Utilities/model.jl
test/Utilities/model.jl

Closes #1214 
See the issue for background, but we have a decision.
Should `set_objective_coefficient` in the following:
```Julia
model = Model()
@variable(model, x)
set_objective_coefficient(model, x, 1.0)
```
1. Throw an error along the likes of "Unable to modify objective because no objective is set."
2. Assume an empty `ScalarAffineFunction` objective exists and modify the linear term?
Currently, this PR does 2, but I would also support the first option.

[Utilities] Fix modifying an un-set objective sets the objective

---

test/runtests.jl

Alphabetical order is nice and tidy, but running benchmarks before running actual tests does not make sense, we would want to test first for correctness before running benchmarks for early termination.

Benchmark last in test

---

src/Test/UnitTests/objectives.jl
test/Test/unit.jl

This test would have caught the OSQP issue fixed by https://github.com/oxfordcontrol/OSQP.jl/pull/90

Add test with zero in off-diagonal entry

---

src/Test/UnitTests/constraints.jl
src/Test/UnitTests/objectives.jl
src/Test/UnitTests/variables.jl

The contquadratic, contconic, etc... are sorted according to the problem class so it makes sense to fail the tests when a class is not supported.
In the case of unit tests, we assume that `supports...` are correctly implemented so it should be ok to rely on it to skip tests.

Skip unit tests when problem not supported

---

src/Utilities/model.jl
test/Utilities/model.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1255
The troublesome line was (note the `S1::Type`)
```julia
julia> @code_warntype MOI.Utilities.throw_if_lower_bound_set(f.variable, typeof(s), mask, T)
Variables
#self#::Core.Compiler.Const(MathOptInterface.Utilities.throw_if_lower_bound_set, false)
variable::MathOptInterface.VariableIndex
S2::Core.Compiler.Const(MathOptInterface.GreaterThan{Float64}, false)
mask::UInt8
T::Core.Compiler.Const(Float64, false)
flag::UInt8
S1::Type
@_8::Bool
Body::Nothing
1 ─       Core.NewvarNode(:(S1))
│         (flag = MathOptInterface.Utilities.single_variable_flag(S2))
│   %3  = (flag::Core.Compiler.Const(0x02, false) & MathOptInterface.Utilities.LOWER_BOUND_MASK)::Core.Compiler.Const(0x02, false)
│   %4  = …
```

Fix inference issue in MOIU.Model

---

docs/src/apireference.md
src/Utilities/sets.jl
test/Utilities/sets.jl

In order to close https://github.com/jump-dev/JuMP.jl/issues/1943, we need a way of checking whether it is possible to push the function constant into the set. The easiest way is just to define this fallback, so the JuMP code will become:
```Julia
function build_constraint(
::Function,
expr::Union{GenericAffExpr, GenericQuadExpr},
set::MOI.AbstractScalarSet,
)
offset = constant(expr)
new_set = MOIU.shift_constant(set, -offset)
if new_set === nothing
return ScalarConstraint(expr, set)
else
add_to_expression!(expr, -offset)
return ScalarConstraint(expr, new_set)
end
end
```
This makes JuMP's heuristic of "I'll push the constant into the set" well-defined by "does it implement shift_constant".
As a follow-up question: should this be moved to MOI proper?

[Utilities] add supports_shift_constant

---

src/Utilities/functions.jl

Implement sketch of https://github.com/jump-dev/MathOptInterface.jl/pull/1257#issuecomment-789634510

Cached getindex for scalar iterator

---

src/Bridges/Constraint/quad_to_soc.jl

Clarify error message in quad_to_soc

---

src/Utilities/functions.jl

**Updated times for most recent commit**
Before
```Julia
julia> @time main(300)
10.678643 seconds (632.16 k allocations: 132.960 MiB, 1.65% gc time)
```
After
```julia
julia> @time main(300);
0.167274 seconds (182.72 k allocations: 137.331 MiB, 17.05% gc time)
```
```Julia
function main(n)
model = MOIU.Model{Float64}()
x = MOI.add_variables(model, n^2)
MOI.set(model, MOI.ObjectiveSense(), MOI.MIN_SENSE)
f = MOI.ScalarQuadraticFunction{Float64}(
MOI.ScalarAffineTerm{Float64}.(rand(n^2), x),
MOI.ScalarQuadraticTerm{Float64}.(1.0, x, x),
0.0,
)
MOI.set(
model,
MOI.ObjectiveFunction{MOI.ScalarQuadraticFunction{Float64}}(),
f,
)
MOI.add_constraint(model, MOI.VectorOfVariables(x), MOI.Nonnegatives(n))
bridged = MOI.Bridges.full_bridge_optimizer(
MOI.Utilities.CachingOptimizer( …
```

Fix complexity of getindex(::ScalarFunctionIterator, i)

---

src/Test/nlp.jl
test/Test/nlp.jl

This PR implements a callback to compute Hessian vector product for the test HS071. 
It currrently runs fine with Knitro. I do not add this test to the [default NLP tests](https://github.com/JuliaOpt/MathOptInterface.jl/blob/master/src/Test/nlp.jl#L349-L361) as that would break the testing for all solvers not supporting Hessian-vector product (including Ipopt).
Implementing a callback for Jacobian vector-product would be straightforward, but I am not aware of any NLP solver supporting this feature.

add Hessian-vector product callback for HS071

---

src/MathOptInterface.jl
src/Utilities/Utilities.jl
src/Utilities/precompile.jl
src/precompile.jl

Cherry-picked from #1264 
Before
```
(base) oscar@Oscars-MBP scripts % '/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia' --project=. precompile.jl
12.614850 seconds (43.66 M allocations: 2.490 GiB, 7.94% gc time, 23.81% compilation time)
```
After
```
(base) oscar@Oscars-MBP scripts % '/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia' --project=. precompile.jl
10.383495 seconds (30.05 M allocations: 1.717 GiB, 5.08% gc time, 22.69% compilation time)
```
If you add #1264 with the improved inference, it drops to
```
(base) oscar@Oscars-MBP scripts % '/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia' --project=. precompile.jl
8.106619 seconds (22.41 M allocations: 1.234 GiB, 5.04% gc time, 27.18% compilation time)
```

Add precompile statements

---

src/Utilities/copy.jl
src/Utilities/functions.jl
src/Utilities/model.jl
src/Utilities/results.jl
src/functions.jl

See the section in Performance Tips:
https://docs.julialang.org/en/v1/manual/performance-tips/index.html#Be-aware-of-when-Julia-avoids-specializing
This should help simplify (and improve) the precompilation files.
Using the script from https://github.com/jump-dev/JuMP.jl/pull/2484
```Julia
(base) oscar@Oscars-MBP scripts % '/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia' --project=. precompile.jl
13.389848 seconds (43.71 M allocations: 2.494 GiB, 7.98% gc time, 24.12% compilation time)
```
```julia
(base) oscar@Oscars-MBP scripts % '/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia' --project=. precompile.jl
11.452046 seconds (37.67 M allocations: 2.103 GiB, 8.23% gc time, 26.85% compilation time)
```

Force Julia to specialize on ::Function arguments.

---

docs/src/submodules/Utilities/overview.md
docs/src/submodules/Utilities/reference.md

Preview: https://jump.dev/MathOptInterface.jl/previews/PR1272/submodules/Utilities/overview/

Document MOI.Utilities

---

docs/src/manual/basic_usage.md
src/Utilities/CleverDicts.jl
src/Utilities/DoubleDicts.jl
src/Utilities/Utilities.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
src/Utilities/vector_of_constraints.jl
test/Utilities/model.jl
test/Utilities/universalfallback.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1234

Refactor Model and UniversalFallback

---

src/Utilities/model.jl
test/Utilities/model.jl

Fix MethodError principle violations

---

src/Utilities/CleverDicts.jl
src/Utilities/copy.jl
src/Utilities/vector_of_constraints.jl
test/Utilities/CleverDicts.jl

Follows what the comment says.

Remove union in IndexMap

---

docs/src/submodules/Bridges/overview.md
docs/src/submodules/FileFormats/overview.md
docs/src/submodules/Utilities/overview.md
docs/src/submodules/Utilities/reference.md
src/Utilities/Utilities.jl
src/Utilities/model.jl
src/Utilities/struct_of_constraints.jl
src/Utilities/vector_of_constraints.jl
test/Bridges/lazy_bridge_optimizer.jl
test/Utilities/cachingoptimizer.jl
test/Utilities/model.jl
test/Utilities/universalfallback.jl

This refactors the code of `AbstractModel` to make it more versatile.
Instead of having one field for each function type which contains a struct with one field for each set type, it now has a field `constraints` that contains one field for each function type, ...
As discussed in https://github.com/jump-dev/MathOptInterface.jl/issues/1261, by changing the type of the `constraints` field, we can now target many more types of models.
The base is set to https://github.com/jump-dev/MathOptInterface.jl/pull/1245 so that it shows the diff with that PR but this is going to be merged to master once https://github.com/jump-dev/MathOptInterface.jl/pull/1245 is merged.

More flexible Model with StructOfConstraints

---

src/Bridges/bridge_optimizer.jl
src/Test/modellike.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
test/Utilities/copy.jl

If the `constraints` field of the model has a more efficient copy_to than adding constraints one by one (e.g. SparseMatrixCSC) then even if it's behind layers of bridges, CachingOptimizer and UniversalFallback, it should be copied (if not bridged), not added one by one.
This PR addresses that.
See https://github.com/jump-dev/MathOptInterface.jl/issues/1261
Requires https://github.com/jump-dev/MathOptInterface.jl/pull/1267

Pass copy operation for non-variable constraints

---

src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

Closes #1220.
@blegat: An alternative is to not pass any OptimizerAttributes. If you're passing a new empty optimizer, it seems weird that the parameters would follow.
What do we expect to happen in the following at the JuMP level?
```Julia
model = Model(Cbc.Optimizer)
set_silent(model)
set_optimizer(model, Clp.Optimizer)
MOI.get(model, MOI.Silent())  # true or false?
```

[Utilities] Drop MOI.RawParameters when resetting a CachingOptimizer

---

docs/src/submodules/Test/overview.md

Initially, I had assumed that if my solver implements `supports(feature) = false`, the relevant tests would be skipped automatically. Instead, they are typically failing, since the tests contain `@assert supports(feature)`.

Reminder to exclude tests for unsupported features

---

NEWS.md
Project.toml

@blegat can you run the SolverTests?

Prep for 0.9.21

---

docs/src/manual/implementing.md
docs/src/reference/models.md
src/Test/UnitTests/attributes.jl
src/Test/intlinear.jl
src/attributes.jl
test/Test/unit.jl

[breaking] Rename SolveTime to SolveTimeSec

---

docs/src/submodules/Bridges/reference.md
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/rsoc.jl
src/Bridges/Constraint/set_map.jl
src/Bridges/Constraint/soc_to_psd.jl
src/Bridges/Variable/rsoc_to_soc.jl
src/Bridges/Variable/soc_to_rsoc.jl
test/Bridges/lazy_bridge_optimizer.jl

This should be breaking only for people who were manually adding this bridge, so I haven't added a deprecation.
Closes #860

[breaking] Rename RSOCBridge and SOCRBridge

---

docs/src/manual/implementing.md
docs/src/reference/models.md
docs/src/submodules/Bridges/overview.md
src/Bridges/bridge_optimizer.jl
src/FileFormats/MOF/write.jl
src/FileFormats/utils.jl
src/Test/contconic.jl
src/Test/intconic.jl
src/Test/modellike.jl
src/Utilities/copy.jl
src/Utilities/functions.jl
src/Utilities/model.jl
src/Utilities/results.jl
src/Utilities/struct_of_constraints.jl
src/Utilities/universalfallback.jl
src/Utilities/vector_of_constraints.jl
src/attributes.jl
src/precompile.jl
test/Bridges/Constraint/slack.jl
test/Bridges/Variable/free.jl
test/Bridges/bridge_optimizer.jl
test/Bridges/utilities.jl
test/Utilities/cachingoptimizer.jl
test/Utilities/model.jl
test/Utilities/universalfallback.jl

This has always been a weirdly named attribute. 
Closes #214

[breaking] Rename ListOfConstraints -> ListOfConstraintTypesPresent

---

src/Bridges/Constraint/indicator_activate_on_zero.jl
src/Bridges/Constraint/indicator_sos.jl
src/Bridges/Constraint/quad_to_soc.jl
src/Bridges/Constraint/semi_to_binary.jl
src/Bridges/bridge_optimizer.jl
src/FileFormats/CBF/CBF.jl
src/FileFormats/LP/LP.jl
src/FileFormats/MOF/write.jl
src/FileFormats/MPS/MPS.jl
src/FileFormats/SDPA/SDPA.jl
src/Test/UnitTests/basic_constraint_tests.jl
src/Test/contlinear.jl
src/Utilities/functions.jl
src/Utilities/mutable_arithmetics.jl
src/Utilities/parser.jl
src/Utilities/results.jl
src/deprecate.jl
src/functions.jl
test/Bridges/Constraint/indicator_activate_on_zero.jl
test/Bridges/Constraint/indicator_sos.jl
test/FileFormats/MOF/MOF.jl
test/deprecate.jl

I'm not necessarily sold on this one. 
The other option is to rename `SingleVariable` to `.variable_index` and `VectorOfVariables` to `.variable_indices`. Either way, we should standardize.
Closes #641

[breaking] Rename .variable_index fields to .variable

---

src/Utilities/cachingoptimizer.jl
src/Utilities/model.jl
src/Utilities/vector_of_constraints.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/1313
This was stopping the `delete` from precompiling:
After
```
Running: clp 
18.562974 seconds (38.47 M allocations: 2.200 GiB, 5.93% gc time, 43.03% compilation time)
0.001416 seconds (5.95 k allocations: 534.227 KiB)
Running: clp --no-bridge
10.577259 seconds (18.82 M allocations: 1.070 GiB, 5.15% gc time, 96.09% compilation time)
0.001221 seconds (3.01 k allocations: 309.070 KiB)
Running: glpk 
14.450203 seconds (33.37 M allocations: 1.910 GiB, 6.87% gc time, 53.09% compilation time)
0.000738 seconds (3.17 k allocations: 249.656 KiB)
Running: glpk --no-bridge
11.603105 seconds (20.37 M allocations: 1.163 GiB, 5.11% gc time, 99.98% compilation time)
0.000591 seconds (2.52 k allocations: 233.828 KiB)
```

Improve type inference in Utilities

---

src/Utilities/struct_of_constraints.jl

Noticed when investigating the benchmark of https://github.com/jump-dev/MathOptInterface.jl/pull/1287
Should also help with https://github.com/jump-dev/MathOptInterface.jl/issues/1313
On the benchmark of https://github.com/jump-dev/MathOptInterface.jl/pull/1287:
Before this PR:
```
0.043870 seconds (123.85 k allocations: 17.192 MiB, 20.42% gc time)
0.000315 seconds (178 allocations: 257.875 KiB)
```
After this PR:
```
0.011613 seconds (3.72 k allocations: 1.152 MiB)
0.000312 seconds (178 allocations: 257.875 KiB)
```

Remove useless {S}

---

src/Utilities/cachingoptimizer.jl

Turned out this had no effect on the benchmarks, but was useful to rule out as a cause.
Unifying the return types and providing some extra annotations can't hurt.

Minor fixes to CachingOptimizer

---

src/Utilities/functions.jl

As this is taking a non-negligeable time in https://github.com/jump-dev/MathOptInterface.jl/pull/1287, it is worth optimizing.
Consider the benchmark:
```julia
function bench(n)
x = MOI.VariableIndex.(1:n)
f = MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.(ones(length(x)), x), 0.0)
@btime MOI.Utilities.is_canonical($f)
end
```
Before:
```
julia> bench(10000)
8.769 μs (0 allocations: 0 bytes)
```
Initial suggestion:
```
julia> bench(10000)
6.477 μs (0 allocations: 0 bytes)
```
@odow improved implementation:
```
julia> bench(10000)
5.808 μs (0 allocations: 0 bytes)
```

inbounds for is_strictly_increasing

---

src/Test/config.jl
src/Test/contconic.jl
src/Test/contlinear.jl
src/Test/contquadratic.jl
src/Test/intconic.jl
src/Test/intlinear.jl

Needed for https://github.com/jump-dev/MathOptInterface.jl/pull/1287

Add query_number_of_constraints option

---

src/FileFormats/MPS/MPS.jl

This definition invalidated some pretty basic print functionality:
```Julia
inserting println(io::IO, card::MathOptInterface.FileFormats.MPS.Card) in MathOptInterface.FileFormats.MPS at /Users/oscar/.julia/dev/MathOptInterface/src/FileFormats/MPS/MPS.jl:114 invalidated:
backedges: 1: superseding println(xs...) in Base at coreio.jl:4 with MethodInstance for println(::Any, ::Any) (1 children)
2: superseding println(io::IO, xs...) in Base at strings/io.jl:73 with MethodInstance for println(::IO, ::Any) (7 children)
27 mt_cache
```

Fix invalidation of println

---

Project.toml
docs/Project.toml
docs/src/submodules/FileFormats/overview.md
src/FileFormats/MOF/MOF.jl
src/FileFormats/MOF/read.jl
test/FileFormats/MOF/MOF.jl
test/FileFormats/MOF/nonlinear.jl

A big cause of method invalidation in JuMP is HTTP (https://github.com/jump-dev/JuMP.jl/issues/2273). One option is to fix them in HTTP, but that requires modifications to Base Julia (https://github.com/JuliaWeb/HTTP.jl/issues/712). 
The better question is: why do we even have HTTP as a dependency? Turns out it is a transitive dependency of JSONSchema, which may need to access schemas from the web. We only use JSONSchema to validate MOF files, and then not even by default.
And if we move JSONSchema to a test and doc dependency, we save 0.4 seconds on `using`, and 1000 method invalidations!
Before 
```julia
julia> @time @eval using MathOptInterface
2.258680 seconds (3.82 M allocations: 274.937 MiB, 7.42% gc time, 0.15% compilation time)
julia> exit()
(base) oscar@Oscars-MBP …
```

[breaking] move JSONSchema to a test dependency

---

docs/src/submodules/Utilities/reference.md
src/Utilities/DoubleDicts.jl
src/Utilities/copy.jl
test/Utilities/copy.jl

Needed for https://github.com/jump-dev/Clp.jl/pull/111

Add identity_index_map and fix DoubleDict bug

---

src/Bridges/bridge_optimizer.jl
src/constraints.jl
test/constraints.jl
test/runtests.jl

Extracted from https://github.com/jump-dev/MathOptInterface.jl/pull/1287/

Add throw_if_scalar_and_constant_not_zero

---

src/Utilities/model.jl
src/Utilities/struct_of_constraints.jl
src/Utilities/vector_of_constraints.jl
test/Utilities/model.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/1313
Calling `MOIU.Model{Float64}()` does a lot of work. It has to create 97 different `CleverDict`s to store all the constraints in! Even though most users only use a small fraction of the possible constraint types. 
This PR uses a small `Union{Nothing,X}` to avoid creating the dictionaries, instead it lazily creates them on the first call to `add_constraint`.
Before
```
(base) oscar@Oscars-MBP auto-cache % ~/julia --project=. bench.jl clp
21.929698 seconds (54.74 M allocations: 3.082 GiB, 6.57% gc time, 34.33% compilation time)
0.001764 seconds (6.02 k allocations: 538.508 KiB)
(base) oscar@Oscars-MBP auto-cache % ~/julia --project=. bench.jl clp --no-bridge
11.345386 seconds (19.50 M allocations: 1.112 GiB, 4.68% gc time, …
```

Lazily create storage in StructOfConstraints

---

src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/copy/allocate_load.jl
src/Utilities/copy/index_map.jl
test/Utilities/CleverDicts.jl
test/Utilities/copy.jl

Closes #1335 
I have a few other changes coming for copy, but I'll split them up one-by-one.

Rename IndexMap fields and refactor

---

src/Utilities/model.jl
test/Utilities/model.jl

Needed for https://github.com/jump-dev/Clp.jl/pull/111. With this PR, `lower_bound` and `upper_bound` are now part of the API since it's documented so Clp can use it directly.

Infinite default bounds for AbstractFloat

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/Constraint.jl
src/Bridges/Objective/Objective.jl
src/Bridges/Variable/Variable.jl

Before
```Julia
julia> using SnoopCompile
julia> using GLPK
julia> f() = GLPK.MOI.Bridges.full_bridge_optimizer(GLPK.Optimizer(), Float64)
f (generic function with 1 method)
julia> tinf = @snoopi_deep f()
InferenceTimingNode: 0.480379/1.063381 on InferenceFrameInfo for Core.Compiler.Timings.ROOT() with 5 direct children
julia> itrigs = inference_triggers(tinf)
5-element Vector{InferenceTrigger}:
Inference triggered to call MethodInstance for f() from eval (./boot.jl:360) inlined into MethodInstance for eval_user_input(::Any, ::REPL.REPLBackend) (/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:139)
Inference triggered to call MethodInstance for add_all_bridges(::MathOptInterface.Bridges.LazyBridgeOptimizer{GLPK.Optimizer}, ::Type) from …
```

Fix an inference issue in Bridges

---

src/Bridges/bridge_optimizer.jl

Big reduction in the amount of compiled code and the elimination of a type instability (the compiler couldn't prove the type in `map` due to `FS...`. 
Before
```julia
julia> using MathOptInterface
julia> const MOI = MathOptInterface
MathOptInterface
julia> using GLPK
julia> model = MOI.Bridges.full_bridge_optimizer(GLPK.Optimizer(), Float64)
MOIB.LazyBridgeOptimizer{GLPK.Optimizer}
with 0 variable bridges
with 0 constraint bridges
with 0 objective bridges
with inner model A GLPK model
julia> @time MOI.get(model, MOI.ListOfConstraintTypesPresent())
1.158660 seconds (3.68 M allocations: 215.417 MiB, 12.50% gc time)
Tuple{DataType, DataType}[]
julia> @time MOI.get(model, MOI.ListOfConstraintTypesPresent())
0.000021 seconds (11 allocations: 1.016 KiB)
Tuple{DataType, DataType}[]
```
After …

Simplify ListOfConstraintTypesPresent in Bridges

---

src/Bridges/Constraint/det.jl
src/Bridges/Constraint/geomean.jl
src/Bridges/Constraint/norm_to_lp.jl
src/Bridges/Constraint/relentr_to_exp.jl
src/Bridges/Constraint/scalarize.jl
src/Bridges/Constraint/slack.jl
src/Bridges/Constraint/soc_to_nonconvex_quad.jl
src/Bridges/Variable/flip_sign.jl
src/Bridges/Variable/free.jl
src/Bridges/Variable/rsoc_to_psd.jl
src/Bridges/Variable/rsoc_to_soc.jl
src/Bridges/Variable/soc_to_rsoc.jl
src/Bridges/bridge_optimizer.jl

Closes #1346 
The current behavior was ripe for introducing bugs. 
In addition, the `copy(list)` in `bridge_optimizer` was unnecessary for most bridges, which just return `[variable]`, so removing it avoids an unnecessary copy in those cases, and maintains the same number of copies for the ones modified here.

Ensure bridges return vectors that can be modified by the user

---

src/Bridges/Constraint/bridge.jl
src/Bridges/Constraint/flip_sign.jl
src/Bridges/Constraint/functionize.jl
src/Bridges/Constraint/scalarize.jl
src/Bridges/Variable/bridge.jl
src/Bridges/Variable/flip_sign.jl
src/Bridges/Variable/free.jl
src/Bridges/Variable/map.jl
src/Bridges/Variable/rsoc_to_psd.jl
src/Bridges/Variable/rsoc_to_soc.jl
src/Bridges/Variable/soc_to_rsoc.jl
src/Bridges/Variable/zeros.jl
src/Bridges/bridge.jl
src/Bridges/bridge_optimizer.jl
test/Bridges/Variable/bridge.jl
test/Bridges/Variable/map.jl
test/Bridges/Variable/zeros.jl

I don't think we need to do this. I tried it out and it actually makes things slightly less readable, because the Variable and Constraint modules need to have `MOIB.IndexInVector`. It's a trivial type that isn't the source of our problems, and the difference isn't even really measurable.

[bridges] unify IndexInVector

---

src/Utilities/product_of_sets.jl

Working on writing the model for Clp.
@blegat I thought you had Clp working?
We also need a way of getting the row from the `MatrixOfConstraints`. Ideally, the `ConstraintIndex` would correspond to the row, and the `VariableIndex` would correspond to the column.

Correct type in ProductOfConstraints

---

.github/workflows/ci.yml

We now have a release-0.9 branch: https://github.com/jump-dev/MathOptInterface.jl/tree/release-0.9

Enable CI on release branches

---

src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

There is no reason that the `model_cache` field has to be empty when creating a `CachingOptimizer`. (And it isn't checked in the other method.)
This is also needed for an upcoming PR to JuMP.

Remove is_empty assertion in CachingOptimizer

---

src/Utilities/matrix_of_constraints.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
src/Utilities/vector_of_constraints.jl
test/Utilities/matrix_of_constraints.jl

Currently, deleting a variable throws a `MethodError`

Throw error at variable deletion for MatrixOfConstraints

---

src/Bridges/bridge_optimizer.jl
test/Bridges/lazy_bridge_optimizer.jl

Forgot the `return` in https://github.com/jump-dev/MathOptInterface.jl/pull/1354/ so things were copied twice :facepalm:

Fix pass_nonvariable_constraints with bridged variables bis

---

src/Utilities/matrix_of_constraints.jl
src/Utilities/mockoptimizer.jl
test/Utilities/matrix_of_constraints.jl
test/Utilities/mockoptimizer.jl

`are_indices_mapped` was storing the index of the set, not the index of the constraint in the cache so that wasn't working.
It was passing the tests because the mapping was always the identity so I now use `MockOptimizer` to make the mapping nontrivial.
Closes https://github.com/jump-dev/MathOptInterface.jl/pull/1360

Fix index mapping of MatrixOfConstraints

---

src/Utilities/sparse_matrix.jl
test/Utilities/sparse_matrix.jl

No bugs. Just some tidying and adding stand-alone tests.

Add tests for Utilities/sparse_matrix.jl

---

docs/src/submodules/Utilities/reference.md
src/Utilities/matrix_of_constraints.jl
src/Utilities/product_of_sets.jl
test/Utilities/matrix_of_constraints.jl
test/Utilities/product_of_sets.jl

@blegat this is still WIP. I wrote proper tests for ProductOfSets and found some bugs (see `@test_broken`).
What is the point of returning the `LazyMap`?
I also changed a few types to private. We can probably split this PR up once things are working, or merge it as a mix of updates.

Various changes and refactoring of ProductOfSets

---

src/Bridges/bridge_optimizer.jl
src/Test/UnitTests/constraints.jl
test/Test/unit.jl

Add a test combining a conic constraint and starting values.
This would have caught https://github.com/jump-dev/MosekTools.jl/issues/66

Add conic test with starting values

---

docs/src/submodules/Utilities/reference.md
src/Utilities/functions.jl
test/Utilities/functions.jl

Document and test zero_with_output_dimension

---

src/attributes.jl

Document order of multiple solutions

---

docs/src/submodules/Test/overview.md

It doesn't match the inside of the module nor the `end # module TestFooBar` at  the end.

Fix case typo in Tests doc

---

src/Utilities/product_of_sets.jl
src/Utilities/sparse_matrix.jl
test/Utilities/matrix_of_constraints.jl
test/Utilities/product_of_sets.jl

Zero index is used to determine whether there are duplicate names:
https://github.com/jump-dev/MathOptInterface.jl/blob/65924e39a438b8338cabf1fada461dc4a1abf3fd/src/Utilities/model.jl#L243
This was clashing with the fact that `MatrixOfConstraints` was returning zero indices. It turns out we don't really don't zero indices. In fact with this PR, `ci.value` corresponds to the row in the scalar case which is nice (and to the first row in the vector case). Before, it corresponded to the offset but it was zero for the first constraint.

Fix getting constraint by name with MatrixOfConstraints

---

docs/src/reference/variables.md
src/Bridges/Constraint/slack.jl
src/Test/config.jl
src/Test/contlinear.jl
src/Utilities/mockoptimizer.jl
src/attributes.jl
test/Bridges/Constraint/functionize.jl
test/Bridges/Constraint/interval.jl
test/Bridges/Constraint/slack.jl
test/Test/contlinear.jl
test/attributes.jl

I started to implement this, but it needs some discussion.
Really, the only thing we're missing is "is a variable with no constraints in the basis?" The only answers can be `BASIC` or `SUPERBASIC`.
I'd vote for my previous suggestion of:
```julia
"""
VariableInBasis(result_index::Int = 1)
A variable attribute which indicates `true` or `false` if some variable in
result `result_index` is in the corresponding optimal solution basis.
"""
struct VariableInBasis <: AbstractVariableAttribute 
result_index::Int
VariableInBasis(result_index::Int = 1) = new(result_index0
end
```
Closes #1297

Add VariableBasisStatus

---

docs/src/submodules/Utilities/overview.md
src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

Follow up of https://github.com/jump-dev/MathOptInterface.jl/pull/1254

EMPTY_OPTIMIZER mode after empty!

---

docs/src/submodules/FileFormats/overview.md
src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/free_integer.mps
test/FileFormats/MPS/stacked_data.mps

[FileFormats.MPS] Add support for OBJSENSE

---

src/attributes.jl
test/attributes.jl

Fix and add test for throwing UnsupportedSubmittable

---

src/Bridges/Constraint/geomean.jl
src/FileFormats/SDPA/SDPA.jl
src/sets.jl
test/Bridges/Variable/map.jl
test/Utilities/model.jl
test/sets.jl

This fixes a TODO in Bridges and closes #967.
One point is up for debate: can you initialize a zero-dimensional set? What do we do in cases like
- `Nonnegatives(0)` => ??
- `SecondOrderCone(1)` => `t <= 0`?

Add error checks for set dimensions

---

src/attributes.jl
test/attributes.jl

Update error message of get_fallback

---

src/Bridges/bridge.jl
test/Bridges/Variable/zeros.jl
test/Bridges/bridge_optimizer.jl

Improve error message of unsupported attributes in bridges

---

src/Test/UnitTests/basic_constraint_tests.jl
src/Test/UnitTests/constraints.jl
src/Test/UnitTests/objectives.jl
src/Test/UnitTests/solve.jl
src/Test/UnitTests/variables.jl
src/Test/contconic.jl
src/Test/contlinear.jl
src/Test/contquadratic.jl
src/Test/intconic.jl
src/Test/intlinear.jl
src/Test/modellike.jl
src/Test/nlp.jl

I'm on a mission to clean up the tests (https://github.com/jump-dev/MathOptInterface.jl/pull/1404) and an annoying piece of style is the arbitrary whitespace in some of the tests. There's a lot of it too! 1300 lines!
If the tests are unreadable, we should break them into smaller tests. Not introduce blank lines arbitrarily or between every line.

[Tests] Remove unnecessary whitespace

---

src/Bridges/Constraint/det.jl
src/Bridges/Constraint/norm_spec_nuc_to_psd.jl
src/Bridges/Constraint/norm_to_lp.jl
src/Bridges/Constraint/relentr_to_exp.jl
src/Utilities/functions.jl

I didn't run all the tests locally yet, so let's see what, if anything, this breaks.
Closes #1388

[breaking] remove operate(::typeof(sum)

---

docs/src/submodules/Utilities/reference.md
src/Test/modellike.jl
src/Utilities/Utilities.jl
src/Utilities/box.jl
src/Utilities/matrix_of_constraints.jl
src/Utilities/model.jl
src/Utilities/product_of_sets.jl
src/Utilities/sparse_matrix.jl
src/Utilities/struct_of_constraints.jl
src/Utilities/vector_of_constraints.jl
test/Utilities/matrix_of_constraints.jl
test/Utilities/model.jl

Various improvements to `MatrixOfConstraints`. It can now pass the relevant tests in `Test/modellike.jl`.
- Add macros to create subtypes of `StructOfConstraints` and improve `StructOfConstraints` so that sub-fields can be `MatrixOfConstraints`s.
- [breaking] Use `Box` in `MOIU.Model` for storing variable bounds.
- Implement some of the getters for MOI attributes.

Various improvements to MatrixOfConstraints

---

docs/src/submodules/Test/overview.md
docs/src/submodules/Test/reference.md
src/Test/Test.jl
src/Test/test_attribute.jl
src/Test/test_variable.jl

[Test] Add test_variable.jl

---

src/Test/Test.jl
src/Test/test_attribute.jl
src/Test/test_basic_constraint.jl
src/Test/test_variable.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/1398

[Test] add test_basic_constraint.jl

---

src/Test/test_constraint.jl
src/Test/test_model.jl
src/Test/test_variable.jl
src/Utilities/mockoptimizer.jl
test/Test/Test.jl

[Test] add test_model.jl

---

src/Utilities/matrix_of_constraints.jl
test/Utilities/matrix_of_constraints.jl

Who knows whether this will be supported in the future but not today

Throw error when adding constraint to MatrixOfConstraints

---

src/Test/test_constraint.jl
src/Test/test_linear.jl
src/Test/test_model.jl
src/Test/test_modification.jl
src/Test/test_nonlinear.jl
src/Test/test_objective.jl
src/Test/test_quadratic.jl
src/Test/test_solve.jl
test/Test/Test.jl

In particular:
- removes calls to `MOI.empty!` inside test functions. This now gets called outside.
- Uses `@requires` in more places
- More explicit exclusion of failing tests in `test/Test/Test.jl`. 
Part of #1398

[Test] various fixes to MOI.Test

---

src/Test/test_objective.jl

GLPK was failing without this. Part of #1398

Fix missing line in test_objective.jl

---

src/Test/test_model.jl
src/Utilities/model.jl
test/Utilities/model.jl

Closes #1429 
I've had to add two tests for now, because I haven't migrated the tests in MOI to the new MOI.Test system.

[Utilities] Fix bug in ListOfConstraintAttributesSet

---

src/Test/Test.jl
src/Test/test_linear.jl
src/Test/test_objective.jl
src/Test/test_solve.jl

Needed for Ipopt. Part of #1398

[Test] change MOI.OPTIMAL to config.optimal_status

---

docs/src/submodules/Test/overview.md
src/Test/Test.jl
src/Test/test_attribute.jl
src/Test/test_modification.jl
src/Test/test_objective.jl

I distinctly remember removing `supports_optimize`, but it seems like that commit never reached `master`...
Part of #1398

[Test] remove supports_optimize in favor of standard exclude

---

src/Test/test_nonlinear.jl

[Test] updates to Test/test_nonlinear.jl

---

src/Test/test_model.jl

[Test] Updates to Test/test_model.jl

---

src/Utilities/universalfallback.jl
test/Utilities/universalfallback.jl

Update the tests of UniversalFallback to new MOI.Test

---

src/Bridges/Constraint/scalarize.jl
test/Bridges/Constraint/scalarize.jl

I like these new tests.
Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1433

Fix Bridges.Constraint.ScalarizeBridge with unset starting values

---

src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

Part of #1398 
@blegat I didn't expect to find two bugs in CachingOptimizer! These new tests are great.

[Utilities] Migrate Utilities/cachingoptimizer to new MOI.Test and fix bugs

---

src/Utilities/constraints.jl
test/Utilities/constraints.jl

Migrate constraints.jl to modular test

---

src/Utilities/lazy_iterators.jl
test/Utilities/lazy_iterators.jl

@blegat so the only point of these is that they are used in the bridges? Why not define them in the bridges then?

Migrate tests of lazy_iterators.jl

---

src/Utilities/parser.jl
test/Utilities/parser.jl

For consistency, we should rename `loadfromstring!` to `load_from_string`, but I'll leave that for a separate PR, since it's going to be quite breaking.
I've also added some underscores here. But this shouldn't be breaking because people shouldn't be touching anything other than `loadfromstring!`.

Migrate tests of parser.jl

---

docs/src/submodules/Test/overview.md

Closes #224 
This may be okay for now. In future, we could look at adding every test docstring to the manual? That seems a lot, and I don't know how useful it would be.

[Test] document how to debug a failing test

---

src/Test/test_attribute.jl
src/Test/test_constraint.jl
src/Test/test_model.jl
test/Utilities/cachingoptimizer.jl
test/Utilities/model.jl
test/Utilities/universalfallback.jl

This PR updates a some tests so that fewer solvers need manually
exclude them.

[Test] various improvements to pass more by default

---

docs/src/submodules/Utilities/reference.md
src/Utilities/matrix_of_constraints.jl
src/Utilities/sparse_matrix.jl
test/Utilities/sparse_matrix.jl

Added by https://github.com/jump-dev/MathOptInterface.jl/pull/1387, but missing some documentation and the testing was a bit convoluted (which made #1457 look bad).

[Utilities] updates to sparse_matrix.jl

---

src/Utilities/struct_of_constraints.jl
test/Utilities/matrix_of_constraints.jl

Needed by ECOS since it needs a `StructOfConstraints` with `MOI.Zeros` on one side and `Union{MOI.Nonnegatives,MOI.SecondOrderCone,MOI.ExponentialCone}` on the other side.

Add support for Union on StructOfConstraints

---

src/DeprecatedTest/contlinear.jl
src/Test/test_conic.jl
src/Test/test_linear.jl
src/Utilities/mockoptimizer.jl
test/Bridges/Constraint/functionize.jl
test/Bridges/Constraint/interval.jl
test/Bridges/Constraint/slack.jl
test/DeprecatedTest/contconic.jl
test/DeprecatedTest/contlinear.jl
test/Utilities/mockoptimizer.jl

Part of #1398
Cleans up the interface, improves the documentation, and migrates the tests to functional form.

Migrate tests of mockoptimizer.jl

---

test/Utilities/mutable_arithmetics.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/1398

Migrate tests of mutable_arithmetics.jl

---

src/Test/test_linear.jl
test/Bridges/Variable/bridge.jl
test/Bridges/Variable/flip_sign.jl
test/Bridges/Variable/free.jl
test/Bridges/Variable/map.jl
test/Bridges/Variable/rsoc_to_psd.jl
test/Bridges/Variable/rsoc_to_soc.jl
test/Bridges/Variable/soc_to_rsoc.jl
test/Bridges/Variable/vectorize.jl
test/Bridges/Variable/zeros.jl
test/Bridges/utilities.jl

Part of #1398 
I haven't gone through the bridges in any detail. I just migrated the tests. I may take another pass after this PR is merged.

Migrate tests of Variable bridges

---

docs/src/submodules/Utilities/overview.md
docs/src/submodules/Utilities/reference.md
src/Utilities/Utilities.jl
src/Utilities/box.jl
src/Utilities/model.jl
src/Utilities/vector_bounds.jl
test/Utilities/box.jl
test/Utilities/matrix_of_constraints.jl
test/Utilities/model.jl
test/Utilities/vector_bounds.jl

This started off by adding some tests to `box.jl`, but I got confused. There's a muddle between `box.jl` and `model.jl`, and who owns what and does what isn't clear. Making this commit now, and then I'm going to try and encapsulate all of the mask stuff into box.jl.
Part of #1457

Refactor box.jl

---

src/Test/test_objective.jl
test/Utilities/model.jl
test/Utilities/vector_bounds.jl

These tests didn't belong in `model.jl`

Move tests out of Utilities/model.jl

---

src/functions.jl
test/Bridges/Variable/zeros.jl
test/FileFormats/SDPA/SDPA.jl
test/functions.jl

Fix isapprox for empty terms

---

src/Utilities/matrix_of_constraints.jl
test/Utilities/matrix_of_constraints.jl

Part of #1398
Interested to see what this does to the code coverage. The previous tests in this file were pretty haphazard, and it's not obvious which tests were testing what. 
The individual components (ProductOfSets, MutableSparseMatrixCSC, etc.) are independently tested, so I don't see the need for wide-scale testing on lots of different types.

Migrate tests of matrix_of_constraints.jl

---

.codecov.yml

Since this is now deprecated, it makes sense to remove it from codecov to stop distracting failures like https://github.com/jump-dev/MathOptInterface.jl/pull/1486#issuecomment-885390001

Ask codecov to ignore DeprecatedTest module

---

docs/src/tutorials/implementing.md

[docs] remove mention of DeprecatedTest

---

docs/src/submodules/Utilities/overview.md
docs/src/submodules/Utilities/reference.md
src/Utilities/DoubleDicts.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy/index_map.jl
test/Utilities/DoubleDicts.jl

I took a look through DoubleDicts for the first time in a long time (ever?).
Why are there so many types and implementations? This is very complicated (600 lines!) for something that should be simple.
From what I can tell, the only type in DoubleDicts that is used is
https://github.com/jump-dev/MathOptInterface.jl/blob/667ad660b7766c526c7526eacbf256d0b9ec9104/src/Utilities/copy/index_map.jl#L8
With this constructor
https://github.com/jump-dev/MathOptInterface.jl/blob/667ad660b7766c526c7526eacbf256d0b9ec9104/src/Utilities/copy/index_map.jl#L24
And this related type which is used to access the inner dictionaries
https://github.com/jump-dev/MathOptInterface.jl/blob/667ad660b7766c526c7526eacbf256d0b9ec9104/src/Utilities/copy/index_map.jl#L49
called from here …

Refactor DoubleDicts.jl

---

src/Test/test_variable.jl
src/variables.jl

[Test] add test for scalar add_constrained_variables

---

src/constraints.jl
test/constraints.jl

These `showerror` method were not tested.

Improve coverage of constraints.jl

---

src/constraints.jl

Introduced by https://github.com/jump-dev/MathOptInterface.jl/pull/1004, which seems far enough ago to remove. We don't want it in 1.0 anyway.

[breaking] remove fallback for supporting free variables

---

src/sets.jl

This was added in https://github.com/jump-dev/MathOptInterface.jl/pull/711 because quote
> [it] was defined in Test for no apparent reason
Seems like we can safely remove. It isn't hit by code coverage, and we don't offer `isapprox` for other sets.

[breaking] remove isapprox for SOS sets

---

src/functions.jl

Jeff says "if you're doing that, please stop."

Remove calls with DataType

---

src/Utilities/Utilities.jl
src/Utilities/model.jl
src/Utilities/objective_function_container.jl
src/Utilities/vector_of_constraints.jl
test/Utilities/objective_function_container.jl

This simplifies the `Utilities.Model` quite a bit.
Currently needs test_broken due to the isapprox issue #1484

Refactor .objective field of Utilities.Model into a struct

---

docs/make.jl
docs/src/background/naming_conventions.md

Add naming conventions.

---

src/Bridges/Constraint/soc_to_nonconvex_quad.jl
src/DeprecatedTest/UnitTests/basic_constraint_tests.jl
src/DeprecatedTest/UnitTests/constraints.jl
src/DeprecatedTest/UnitTests/objectives.jl
src/DeprecatedTest/contquadratic.jl
src/DeprecatedTest/nlp.jl
src/FileFormats/MOF/read.jl
src/Test/test_basic_constraint.jl
src/Test/test_constraint.jl
src/Test/test_nonlinear.jl
src/Test/test_objective.jl
src/Test/test_quadratic.jl
src/Utilities/functions.jl
src/Utilities/mutable_arithmetics.jl
src/Utilities/parser.jl
src/deprecate.jl
src/functions.jl
test/Bridges/Constraint/quad_to_soc.jl
test/FileFormats/NL/NL.jl
test/Utilities/functions.jl
test/Utilities/model.jl
test/Utilities/parser.jl
test/Utilities/print.jl
test/deprecate.jl
test/functions.jl

Closes #1406
@blegat pros and cons of merging this?

[breaking] re-order fields of QuadraticFunction

---

docs/make.jl
docs/src/tutorials/mathprogbase.md

[docs] Add tutorial on transitioning from MPB

---

src/indextypes.jl

These functions were not called anywhere. We should remove unused things. People can just use `.value`.

[breaking] remove index_value function

---

src/Bridges/Constraint/set_map.jl
src/Bridges/Constraint/single_bridge_optimizer.jl
src/Bridges/Objective/single_bridge_optimizer.jl
src/Bridges/Variable/set_map.jl
src/Bridges/Variable/single_bridge_optimizer.jl
src/Bridges/bridge_optimizer.jl
src/Bridges/lazy_bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl
test/Bridges/identity_bridge.jl

This is breaking for a user relying on the fact that SingleBridgeOptimizer was creating the constraint to the same model recursively.
It would have been used in a non-stackoverflow situation in case a bridge would create a constraint of the same time as the constraint being transformed twice and then not. I would guess no user was doing that but we never know.
Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1015

Fix StackOverflow with self-loop bridges

---

docs/src/tutorials/mathprogbase.md

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1508

Nuance MPB vs MOI implementation

---

docs/src/background/duality.md
docs/src/manual/standard_form.md
docs/src/tutorials/example.md
docs/src/tutorials/implementing.md

Adds some typo fixes and smaller stylistic changes in presentation (hopefully not too much at once).

Stylistic changes and typo fixes in intro docs

---

src/Test/test_solve.jl

Found while updating AmplNLWriter

[Test] Fix requires in ObjectiveBound tests

---

src/Test/test_nonlinear.jl

This adds a useful test from AmplNLWriter

[Test] Add test for NLPBlockDual

---

src/Test/Test.jl

[Test] fix bug in skipping ConstraintDual

---

src/Test/test_attribute.jl

This was a useful test from Clp.

[Test] add a test for attributes after empty

---

docs/src/submodules/Utilities/reference.md
docs/src/tutorials/implementing.md
src/Bridges/bridge_optimizer.jl
src/Utilities/copy.jl
src/Utilities/mockoptimizer.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
test/DeprecatedTest/modellike.jl
test/Utilities/cachingoptimizer.jl
test/Utilities/copy.jl
test/deprecate.jl
test/dummy.jl

[breaking] remove automatic_copy_to

---

src/MathOptInterface.jl
src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

I've just refactored ECOS with MatrixOfConstraints (https://github.com/jump-dev/ECOS.jl/pull/121/).
There is something tricky that will also be problematic for other similar solvers.
When you implement `copy_to!(dest::Optimizer, src::OptimizerCache)`, `src` contains exactly the data you need to call the solver directly. However, you cannot call it yet, you need to wait for `optimize!` to be called.
So you need to store a cache `src` in `dest`. You need to store a copy since `src` could be modified or its data could be free'd before `optimize!` is called.
This create a lot of edge cases that kind of defeat the purpose of https://github.com/jump-dev/MathOptInterface.jl/pull/1381 to remove the need for the optimizer to have a cache as this is handled by the `CachingOptimizer`.
This PR …

Define copy_to_and_optimize!

---

src/Utilities/model.jl

It's more than just variable bounds. In another PR I'm going to try and move the name stuff over.
This also unifies: `.objective`, `.variables`, and `.constraints`.

Rename .variable_bounds to .variables

---

src/DeprecatedTest/UnitTests/constraints.jl
src/Test/test_constraint.jl

`optimize!` is already called by `test_model_solution`. I was a bit confused when this test was causing ECOS to segfault because it's not obvious that it's calling `optimize!` twice.

Remove redundant optimize call

---

docs/src/submodules/Bridges/overview.md
docs/src/submodules/FileFormats/overview.md
docs/src/submodules/Utilities/overview.md
src/Utilities/model.jl
test/Utilities/copy.jl
test/Utilities/matrix_of_constraints.jl
test/Utilities/model.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1261
Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1502
Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1470

Parametrize GenericModel with objective/variable sub-model

---

docs/src/reference/models.md
src/MathOptInterface.jl
src/Utilities/copy/index_map.jl

Closes #1527 
Just a look at what this would look like.

Improve documentation of IndexMap

---

src/Bridges/bridge_optimizer.jl
src/Test/test_model.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/matrix_of_constraints.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
test/Utilities/copy.jl

Part of #1313, using that same script with GLPK.
Now that allocate-load is gone, we can refactor a lot of `Utilities.default_copy_to`.
```
julia> tinf
InferenceTimingNode: 4.981569/10.378739 on InferenceFrameInfo for Core.Compiler.Timings.ROOT() with 79 direct children
```
```
julia> tinf
InferenceTimingNode: 3.927378/8.255136 on InferenceFrameInfo for Core.Compiler.Timings.ROOT() with 61 direct children
```
We now have 61 entries into runtime dispatch instead of 79, and time drops from ~10 seconds to ~8 seconds.
There are 29 methods remaining where this happens:
```Julia
julia> mtrigs
29-element Vector{SnoopCompile.TaggedTriggers{Method}}:
MathOptInterface.Utilities.CachingOptimizer(model_cache::MathOptInterface.ModelLike, optimizer::MathOptInterface.AbstractOptimizer) in …
```

Refactor Utilities.default_copy_to

---

src/MathOptInterface.jl

Technically breaking, but I think this only ever existed in the documentation.
Looks like Hypatia has it as an argument (cc @chriscoey), but didn't do anything with it:

Remove warn_attributes

---

docs/src/submodules/Bridges/reference.md
src/Bridges/Bridges.jl
src/Bridges/Constraint/ltgt_to_interval.jl
src/Bridges/Constraint/soc_to_nonconvex_quad.jl
src/Bridges/Constraint/soc_to_psd.jl
test/Bridges/lazy_bridge_optimizer.jl

This attributes allow an optimizer to list a few bridges that should automatically be used by JuMP.
Here are a few use cases:
* Solvers that requires SOC constraint to be provided as ScalarQuadraticFunction-in-LessThan can add the SOCtoQuad bridge in this list in the prefered form (either supporting VectorOfVariables-in-SOC or VectorAffineFunction-in-SOC, since for some solver, the quadratic function obtained is recognized only if it is computated from the correct one, and we can go from one form to another with the [Slack and VectorOfVariables bridges](https://github.com/JuliaOpt/MathOptInterface.jl/issues/528)), see https://github.com/JuliaOpt/MathOptInterface.jl/pull/478#discussion_r211120417 (@ccoffrin this would resolve the issue we discussed with @mlubin )
* Solvers that use …

Add Bridges.ListOfNonstandardBridges attribute

---

src/Test/test_nonlinear.jl

[Test] Add test for NaN in NLP callbacks

---

docs/src/submodules/Utilities/overview.md
docs/src/tutorials/implementing.md
src/Bridges/bridge_optimizer.jl
src/DeprecatedTest/contconic.jl
src/DeprecatedTest/contlinear.jl
src/DeprecatedTest/contquadratic.jl
src/DeprecatedTest/intconic.jl
src/DeprecatedTest/intlinear.jl
src/DeprecatedTest/modellike.jl
src/FileFormats/NL/NL.jl
src/MathOptInterface.jl
src/Test/test_conic.jl
src/Test/test_linear.jl
src/Test/test_model.jl
src/Test/test_quadratic.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/mockoptimizer.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
src/instantiate.jl
test/Utilities/cachingoptimizer.jl
test/Utilities/copy.jl
test/deprecate.jl
test/dummy.jl
test/instantiate.jl

A look at what this would look like. I still need to benchmark to cost of always trying to copy names.
Closes #1533

Remove copy_names argument

---

src/Bridges/bridge_optimizer.jl

[Bridges] fix TODOs in bridge_optimizer

---

src/Test/test_solve.jl
src/Utilities/mockoptimizer.jl
test/Utilities/cachingoptimizer.jl

This PR adds a lot of conflict tests that were in Gurobi.jl. Conflict statuses weren't tested in the rest of MOI.
Part of #1065

[Test] add compute_conflict tests from Gurobi.jl

---

src/attributes.jl

[docs] Clarify RelativeGap is solver-dependent

---

src/Bridges/Constraint/geomean.jl
src/Utilities/functions.jl

I was trying to address this TODO:
https://github.com/jump-dev/MathOptInterface.jl/blob/5fb36a46fe1de6c4b23abb515e6a5af50e4f23f8/src/Bridges/Constraint/geomean.jl#L48-L52
and I got very confused with the GeoMean implementation.
I started with some renaming, but then I gave up. It could use some much better documentation.

[Bridges] Maintenance of GeoMeanBridge

---

src/Bridges/Constraint/det.jl
src/Bridges/Constraint/norm_spec_nuc_to_psd.jl
src/Bridges/Constraint/soc_to_psd.jl
src/Bridges/Variable/rsoc_to_psd.jl
src/Utilities/sets.jl
test/Utilities/sets.jl

`trimap` was defined in two files, but used all-over...
Part of #1345

[Utilities] Move trimap from bridges

---

src/Test/test_objective.jl
src/Test/test_solve.jl

[Test]  Add more tests from Gurobi.jl
