src/Utilities/parser.jl
test/Utilities/parser.jl

Improve error message loadfromstring

---

docs/src/submodules/Utilities/overview.md
docs/src/submodules/Utilities/reference.md
src/Bridges/bridge_optimizer.jl
src/Test/test_model.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/matrix_of_constraints.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
test/Utilities/copy.jl

The `filter_constraints` argument was always a bit weird. This goes to a model-wrapper approach that @blegat created instead.
Closes #1554

Replace filter_constraints with ModelFilter

---

NEWS.md
docs/make.jl
docs/src/release_notes.md

The Python ecosystem do this. I think it works quite well: http://xarray.pydata.org/en/latest/whats-new.html
It's doubly important for this release of MOI because there are such a large number of changes.

[docs] move NEWS to the documentation

---

src/Test/test_conic.jl

[Test] Add SecondOrderCone tests from Gurobi.jl

---

src/Test/test_constraint.jl
src/sets.jl

Part of #1065 
It's not really clear whether we support indicator constraints like `2 * x[1] => sum(x[2:end]) <= 1.0`. (i.e., the first row isn't a variable). Are they any solvers that won't throw an error?

[Test] add indicator tests from Gurobi.jl

---

.github/workflows/documentation.yml
docs/Project.toml
docs/src/manual/constraints.md
docs/src/manual/modification.md
docs/src/manual/variables.md
docs/src/submodules/Bridges/implementation.md
docs/src/submodules/Bridges/overview.md
docs/src/submodules/FileFormats/overview.md
docs/src/submodules/Utilities/overview.md
docs/src/tutorials/example.md
docs/src/tutorials/manipulating_expressions.md
src/Bridges/Constraint/bridge.jl
src/Bridges/Variable/bridge.jl

[docs] update docs to build on Julia 1.6

---

docs/src/manual/models.md
docs/src/reference/models.md
docs/src/tutorials/implementing.md
src/MathOptInterface.jl

We have never explicitly documented which attributes we expect to be implemented. To date it has been "whatever is needed to pass the tests."

Document interface expected by subtypes

---

src/Bridges/Constraint/zero_one.jl
test/Bridges/Constraint/zero_one.jl

What does it mean to `ConstraintPrimalStart` a `ZeroOne` constraint? We should only be supporting it if it makes sense.

[Bridges] maintenance of zero_one.jl

---

src/Bridges/Constraint/interval.jl
src/Bridges/Constraint/ltgt_to_interval.jl
test/Bridges/Constraint/interval.jl

See https://github.com/jump-dev/MathOptInterface.jl/pull/1228

Support infinite bounds in SplitIntervalBridge

---

src/Bridges/Constraint/indicator_sos.jl
test/Bridges/Constraint/indicator_sos.jl

In particular:
* Remove MaybeBC type parameter
* Remove and rename fields in struct
* Fix MOI.supports for ConstraintPrimalStart
The fields and MaybeBC parameter were superfluous because we can
implicitly figure out what they are from the existing set.

[breaking] [Bridges] Refactor IndicatorSOS1Bridge

---

src/Test/test_conic.jl

This is an embarrassing error on my part. I just copy-pasted these from Gurobi.jl without checking them too thoroughly. I guess Gurobi can find the exact solution, whereas CPLEX doesn't.

[Test] change exact comparison to approx

---

src/Test/Test.jl

This came up in CPLEX. For `ObjectiveFunctionType`, it will infer as `Type`, but a concrete type will be returned. Since inference is also Julia-version specific, we should probably just drop this requirement.

[Test] relax inferred in attribute_value_type

---

src/Test/test_solve.jl

This one is a real doozy that took me while to isolate. Two dueling bugs here:
* `MOI.VectorOfVariables(λ)` should have been `MOI.VectorOfVariables(η)`
* `λ` was boxed and causing some weird failure with CPLEX.
Note the `λ@_5::Core.Box`.
```Julia
julia> function main(model)
MOI.empty!(model)    
function _add_SOS2()
λ = MOI.add_variables(model, 2)
c = MOI.add_constraint(
model,
MOI.VectorOfVariables(λ), 
MOI.SOS2{Float64}([1.0, 2.0, 3.0]),
)
return λ, c
end
x = MOI.add_variables(model, 2)
λ, c1 = _add_SOS2(model)
MOI.delete(model, c1)
MOI.add_constraint(
model,
MOI.VectorOfVariables(λ),
MOI.SOS2{Float64}([1.0, 2.0, 3.0]),
)
MOI.optimize!(model)
return
end
main (generic function with 1 method)
julia> @code_warntype main(CPLEX.Optimizer())
Variables
#self#::Core.Const(main) …
```

[Test] fix bug in test_solve_SOS2_add_and_delete

---

docs/src/reference/errors.md
src/attributes.jl

Fixes #1600. 
If you are OK with the wording, the same patch could be applied to `ConstraintDual`, `ConstraintBasisStatus`, `ObjectiveValue`, `DualObjectiveValue`, `VariableBasisStatus`, `ConstraintPrimal`.

VariablePrimal: document undefined behaviour 

---

docs/src/submodules/Utilities/reference.md
src/Utilities/matrix_of_constraints.jl
test/Utilities/matrix_of_constraints.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1606
Closes https://github.com/jump-dev/MathOptInterface.jl/pull/1607

Add set_with_dimension

---

src/Test/test_nonlinear.jl

Minor fixes to make the nonlinear tests pass both with Knitro and MadNLP.
1. `NLPBlockDual`: Check correctness of dual variables directly with KKT stationary condition
As the problem HS071 is nonconvex, solvers can return a different values than the one previously specified in `test_nonlinear_hs071_NLPBlockDual`: 
```julia
@test isapprox(dual, [0.178761800, 0.985000823], config)
```
For instance, both Knitro and MadNLP return `[0.0, 0.4058829] ` there. Using directly the KKT stationary condition avoids this problem.
2. Fix issue in definition of `FeasibilitySenseEvaluator`
When using the `FeasibilitySenseEvaluator`, we test that the primal variable returned is equal to 1: 
```julia
xv = MOI.get(model, MOI.VariablePrimal(), x)
@test isapprox(abs(xv), 1.0, config)
```
However, this is …

[Test] Minor fixes in nonlinear tests

---

src/Bridges/Constraint/geomean.jl
src/Test/test_basic_constraint.jl

More fixes found while working on https://github.com/jump-dev/SCS.jl/pull/219

[Test] more misc fixes from SCS

---

src/Utilities/copy.jl

We should put a proper `supports` check here and throw the right error so down-stream users don't have to duplicate work.
Another idea from https://github.com/jump-dev/SCS.jl/pull/219

[Utilities] throw UnsupportedAttribute in pass_attributes

---

docs/src/reference/models.md
docs/src/tutorials/implementing.md
src/MathOptInterface.jl
src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

There is an issue with `copy_to_and_optimize!`. What if the user changes the optimizer attributes and then want to optimize again ?
The solver supports setting optimizer attributes so the state in the `CachingOptimizer` will remain `ATTACHED_OPTIMIZER`.
So it will call `optimize!` but the solver can't optimize since it did not cache the model data.
For solvers relying on `copy_to_and_optimize!`, `CachingOptimizer` should keep the state `EMPTY_OPTIMIZER`.
This PR allows to do that with a new `MOI.optimize_model!`.
I have kept `copy_to_and_optimize!` so that it's not breaking but we can get rid of it in MOI v1.0.
Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1604

Replace copy_to_and_optimize! with optimize_model!

---

src/Utilities/cachingoptimizer.jl

I hit another snag: callbacks through a CachingOptimizer require `optimizer_to_model_map` to be set before `optimize!` so that they are accessible for things like `CallbackVariablePrimal`. But, the two-argument version means that this isn't set until afterwards. 
As a work-around, we call `attach` if a callback is set. I don't think there will be any optimizers that require the two-argument version and support callbacks. There aren't any at the moment, at least.

[Utilities] allow callbacks through CachingOptimizer

---

Project.toml
docs/src/release_notes.md

If we merge #1619 and then this, we should have GLPK, Ipopt, and SCS all updated and working with the new MOI. Then we can tag their releases and start working on breaking changes for JuMP.

Update release notes for v0.10.3

---

src/Test/test_nonlinear.jl

Should it be this or `if MOI.get(model, MOI.DualStatus()) != MOI.NO_SOLUTION` ?

Allow skipping NLPBlockDual

---

src/FileFormats/MOF/nonlinear.jl
src/FileFormats/NL/NL.jl
src/Utilities/print.jl
src/Utilities/universalfallback.jl
test/Utilities/universalfallback.jl

While thinking about https://github.com/jump-dev/JuMP.jl/issues/2770. The current behavior is:
```Julia
julia> using JuMP, Gurobi
julia> model = Model(Gurobi.Optimizer)
Academic license - for non-commercial use only - expires 2021-11-06
A JuMP Model
Variables: 0
Solver name: Gurobi
julia> MOI.get(model, Gurobi.ModelAttribute("IsMIP"))
ERROR: KeyError: key Gurobi.ModelAttribute("IsMIP") not found
Stacktrace:
[1] getindex
@ ./dict.jl:482 [inlined]
[2] _get
@ ~/.julia/packages/MathOptInterface/D0LUL/src/Utilities/universalfallback.jl:264 [inlined]
[3] get
@ ~/.julia/packages/MathOptInterface/D0LUL/src/Utilities/universalfallback.jl:309 [inlined]
[4] …
```

[Utilities] Fix getter in UniversalFallback

---

CITATION.bib
docs/src/index.md

JabRef complains with "Found corrupted citation key ... (contains whitespace)."

Fix space issue in BibTeX entry

---

src/Test/test_solve.jl

This test was wrong by doing integer division instead of real-valued division

Fix ZeroOne 2 infeasibility test

---

src/MathOptInterface.jl
test/errors.jl

Fix StackOverflow with copy_to

---

src/FileFormats/NL/NL.jl
test/FileFormats/NL/NL.jl

[FileFormats] fix copy_to for FileFormats.NL

---

src/Test/test_conic.jl
src/Test/test_solve.jl
test/Utilities/CleverDicts.jl

When tests require a number because of a duplicate name they were using `ii` and `2`. I kept the latter because it is clearer.
We should highlight this in docs?

Fix tests names

---

src/FileFormats/NL/NL.jl
test/FileFormats/NL/NL.jl

[FileFormats.NL] Fix printing of large integers

---

src/Utilities/copy.jl

Closes #1614
@blegat's argument being that there should already be some fallbacks for this, and catching it here might obscure other bugs.

[Utilties] don't throw UnsupportedAttribute in pass_attributes

---

src/Test/test_model.jl
test/Bridges/Constraint/semi_to_binary.jl

I considered a few ways of fixing #1431 (e.g., adding an Interval constraint so the variable would have a bound), but couldn't find anything satisfactory. The bridges need something like #1097, but that's a much greater fix.
This stops people running into the common source of failure, and it includes a broken test for us to fix in the future.
Closes #1431. I've opened #1665 to track the broader issue.

Remove source of common test failure in LowerBoundAlreadySet

---

docs/src/tutorials/implementing.md

Closes #1633
I don't think we want to include out-dated READMEs in the documentation, and I don't think we want to mandate what the README should look like. We can aim for internal consistency without explicitly documenting this.

[doc] clarify documentation of solvers

---

docs/src/submodules/Test/overview.md
docs/src/submodules/Test/reference.md
src/Test/Test.jl
src/Test/test_conic.jl
src/Test/test_solve.jl
test/Test/Test.jl

Closes #1661
Not sold on the `exclude_tests_after` name; open to bike shed.
I think with this design it lets us be much more liberal with adding new (potentially breaking) tests, and we won't have this constant fight about updating solvers. Then, solver authors can periodically increment this bound and deal with the fallout. In a post-1.0 world of MOI, nothing of their existing code should break, so this is really just a catch on adding new features.

[Test] add version_added to better control MOI.Test.runtests

---

src/Test/test_basic_constraint.jl

Part of #841
I think this is going to be a long slog, so I'll chip away at it slowly.

[Test] update for generic coefficient types

---

docs/make.jl
docs/src/background/infeasibility_certificates.md
src/Bridges/Constraint/scalarize.jl
src/Test/test_infeasibility_certificates.jl
src/Utilities/results.jl

This PR adds documentation and tests for primal and dual infeasibility certificates.
Preview link
https://jump.dev/MathOptInterface.jl/previews/PR1660/background/infeasibility_certificates/
Closes #433. 
Closes #1201

Add docs and tests for infeasibility certificates

---

src/Test/Test.jl
src/Test/test_conic.jl
src/Test/test_constraint.jl
src/Test/test_infeasibility_certificates.jl
src/Test/test_linear.jl
src/Test/test_solve.jl

[Test] add config.infeasible_status

---

src/Test/Test.jl
src/Test/test_linear.jl
test/Test/Test.jl

[Test] add generic number types in test_linear

---

src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

Closes #1310.
I think this is fine for the short-term. It's a continual pain-point for solvers (e.g., @chriscoey bumped into it when updating Pavito).

[Utilities] use ConstraintPrimal fallback in CachingOptimizer

---

src/Utilities/mockoptimizer.jl
test/Bridges/bridge_optimizer.jl
test/Test/Test.jl
test/Utilities/cachingoptimizer.jl
test/instantiate.jl

[Utilities] Support generic number type in MockOptimizer

---

src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/functions.jl
src/Utilities/mockoptimizer.jl
test/Utilities/cachingoptimizer.jl

Closes #1670.
I think the original argument was that we shouldn't have a fallback to force everyone to implement it. However, most people implementing this method just implement the fallback:
- https://github.com/atoptima/BlockDecomposition.jl/blob/v1.4.0/src/axis.jl#L16
- https://github.com/atoptima/BlockDecomposition.jl/blob/v1.4.0/src/tree.jl#L20
If people are writing new attributes and not accounting for this, that's on them for not testing correctly.

[Utilities] fix fallback of map_indices

---

src/Test/test_nonlinear.jl

Part of #841 
This is a better way to do it.

[Test] simplify type check in test_nonlinear

---

src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

Found by running the solver tests: https://github.com/jump-dev/SolverTests/runs/4305389522?check_suite_focus=true

Fix bug in CachingOptimizer ConstraintPrimal

---

src/Test/test_model.jl

A replacement for #1685 
SCS passes this test now:

[Test] fix test_model_copy_to_ tests

---

src/Test/test_conic.jl

Seems like I missed this one.  Caught by the solver test for SCS: https://github.com/jump-dev/SolverTests/runs/4328930300?check_suite_focus=true

[Test] fix missing config in _test_det_cone_helper

---

Project.toml
docs/src/release_notes.md

This release actually contained quite a bit of material.
Most solvers are passing: https://github.com/jump-dev/SolverTests/pull/17
The few that aren't either haven't been updated to 0.10, or are failing the new infeasibility certificate tests. There's a new feature in MOI.Test to avoid these situations in future.

Prep for v0.10.6

---

src/Utilities/print.jl
test/Utilities/print.jl

Closes #1693
```Julia
julia> model = MOI.Utilities.UniversalFallback(MOI.Utilities.Model{Float64}())
MOIU.UniversalFallback{MOIU.Model{Float64}}
fallback for MOIU.Model{Float64}
julia> x = MOI.add_variable(model)
MathOptInterface.VariableIndex(1)
julia> c = MOI.add_constraint(model, (1.0 + 1.0im)x, MOI.EqualTo(1.0 + 1.0im))
MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{ComplexF64}, MathOptInterface.EqualTo{ComplexF64}}(1)
julia> print(model)
Feasibility
Subject to:
ScalarAffineFunction{ComplexF64}-in-EqualTo{ComplexF64}
(0.0 + 0.0im) + (1.0 + 1.0im) v[1] == (1.0 + 1.0im)
```

Fix printing of non-real number types

---

src/Utilities/functions.jl

The existing method was pretty terrible for inference.

[Utilities] Fix method invalidation

---

src/Utilities/copy.jl
test/Utilities/copy.jl

@blegat should this be a + or a -? Part of #1698 
With the `-`:
```Julia
julia> solver = MOI.instantiate(
MOI.OptimizerWithAttributes(
MOIPajarito.Optimizer,
"oa_solver" => MOI.OptimizerWithAttributes(GLPK.Optimizer),
"conic_solver" => MOI.OptimizerWithAttributes(ECOS.Optimizer),
);
with_bridge_type = Float64
);
julia> MOI.Utilities._cost_of_bridging(solver, MOI.GreaterThan{Float64})
(0.0, false)
julia> MOI.Utilities._cost_of_bridging(solver, MOI.Integer)
(0.0, false)
```
The cost for GreaterThan is `1 - 1` but the cost for `Integer` is `0 - 0`. Or perhaps we need to return a triplet of `(x - y, x + y, false)`.

Fix logic in cost_of_bridging

---

src/Utilities/functions.jl

Initial analysis of https://github.com/jump-dev/JuMP.jl/issues/2817
No changes to the memory allocations. But `canonical` gets called an awful lot, so this is a critical path. The current implementation was very generic with dynamic dispatch. But the functions aren't used outside MOI, or anywhere else in MOI:
https://juliahub.com/ui/Search?q=sort_and_compress%21&type=code
https://juliahub.com/ui/Search?q=is_strictly_sorted&type=code
Script:
```julia
using MathOptInterface
const MOI = MathOptInterface
function create_model(I, T = 10000)
model = MOI.Utilities.Model{Float64}()
v = MOI.VariableIndex[]
for _ in 1:I
x = MOI.add_variables(model, T)
MOI.add_constraint.(model, x, MOI.GreaterThan(0.0))
MOI.add_constraint.(model, x, MOI.LessThan(100.0))
for t in 2:T
f = MOI.ScalarAffineFunction( …
```

[Utilities] improve performance of canonical

---

src/Utilities/cachingoptimizer.jl
src/Utilities/mockoptimizer.jl
src/Utilities/results.jl

[Utilities] Fix location of check_result_index_bounds

---

src/MathOptInterface.jl
src/precompile.jl

A small but easy win
Before
```
(base) oscar@Oscars-MBP time_to_first_solve % ~/julia --project=. script.jl clp
Running: clp 
10.806358 seconds (26.74 M allocations: 1.644 GiB, 7.28% gc time, 21.54% compilation time)
0.001693 seconds (3.54 k allocations: 305.125 KiB)
(base) oscar@Oscars-MBP time_to_first_solve % 
(base) oscar@Oscars-MBP time_to_first_solve % ~/julia --project=. script.jl clp --no-bridge
Running: clp --no-bridge
5.038987 seconds (10.89 M allocations: 675.651 MiB, 5.38% gc time, 40.86% compilation time)
0.001256 seconds (2.55 k allocations: 242.703 KiB)
(base) oscar@Oscars-MBP time_to_first_solve % ~/julia --project=. script.jl glpk           
Running: glpk 
6.586336 seconds (17.67 M allocations: 1.037 GiB, 6.42% gc time, 35.91% compilation time)
0.000462 seconds (1.22 k …
```

[perf] Precompile for instantiate

---

perf/time_to_first_solve/Project.toml
perf/time_to_first_solve/README.md
perf/time_to_first_solve/script.jl

[perf] add time-to-first-solve benchmark

---

perf/time_to_first_solve/script.jl
src/Bridges/Bridges.jl
src/Bridges/precompile.jl
src/Utilities/precompile.jl
src/Utilities/universalfallback.jl

[perf] more latency improvements

---

src/Utilities/sparse_matrix.jl
test/Utilities/sparse_matrix.jl

Closes #1711 
The need for `final_touch` is just a recipe for bugs like this. We should endeavor to make it that we don't need to call `final_touch` for most things (now I think it's only the sets).

[Utilities] simplify MutableSparseMatrix to remove final_touch

---

docs/src/background/duality.md

Preview at https://jump.dev/MathOptInterface.jl/previews/PR1717/

Improve quadratic duality in doc

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl
test/FileFormats/LP/models/corrupt.lp
test/FileFormats/LP/models/example_lo1.lp
test/FileFormats/LP/models/invalid_affine_term_constraint.lp
test/FileFormats/LP/models/invalid_affine_term_objective.lp
test/FileFormats/LP/models/invalid_bound.lp
test/FileFormats/LP/models/invalid_constraint.lp
test/FileFormats/LP/models/invalid_sos_constraint.lp
test/FileFormats/LP/models/invalid_sos_set.lp
test/FileFormats/LP/models/invalid_variable_name.lp
test/FileFormats/LP/models/model1.lp
test/FileFormats/LP/models/model1_tricky.lp
test/FileFormats/LP/models/model2.lp

This implementation is some copy from https://github.com/odow/LPWriter.jl/blob/master/src/reader.jl
There are still a few missing important features. 
I will probably implement them next week. 
I have some questions regarding the files we use as test sets. Do you have any suggestions?
Closes #1675

Add LP Base.read! and tests

---

src/Utilities/matrix_of_constraints.jl
test/Utilities/matrix_of_constraints.jl

Closes #1721 
To be used by https://github.com/jump-dev/SCS.jl/pull/244

Fix PowerCone in MatrixOfConstraints

---

docs/src/manual/solutions.md

[docs] Add try-catch section on querying attributes

---

src/Utilities/print.jl
test/Utilities/print.jl

Removed backslashes before brackets in both code (`/src/Utilities/print.jl`) and tests (`/test/Utilities/print.jl`).
Closes #1728

Fix printing of intervals (jump-dev#1728)

---

docs/src/submodules/Utilities/reference.md
src/Utilities/Utilities.jl
src/Utilities/free_variables.jl
src/Utilities/model.jl
src/Utilities/variables_container.jl
test/Utilities/matrix_of_constraints.jl

Needed by https://github.com/jump-dev/DiffOpt.jl/pull/187/ and by most conic solvers.
The problem when using `VariablesContainer` is that model that use this as inner representation will need to redefine `supports_constraint` and `supports_add_constrained_variable` to avoid variables bounds to go through. This is quite tedious and if you don't do it correctly, you will silently ignore constraints that went through hidden in this VariablesContainer while they should have been bridged. This is the problem with DiffOpt.
For conic solvers, when they use `VariablesContainer` in their `OptimizerCache`, they need to verify that no variable bounds have been set during `copy_to`. Also, you cannot just copy_to to the `OptimizerCache` as otherwise, that won't bridge the variable bounds, you are …

Add FreeVariables

---

src/Utilities/mutable_arithmetics.jl

To be used in conjunction with https://github.com/jump-dev/MutableArithmetics.jl/pull/147
This is my new favorite performance bug of all time. For some reason,
the extra N type parameter was preventing Julia from being clever, but
it's soooooo hard to notice.

Fix performance of MutableArithmetics

---

src/Bridges/Constraint/geomean.jl

[Bridges] convert GeoMeanBridge to inner constructor

---

src/Utilities/mutable_arithmetics.jl

ScalarLike{T} includes VariableIndex, which does not have a type
parameter. So passing two variables to promote_operation would have
resulting in a 'T not defined error'.
_We_ know that this would have been caught by another method, but it
seems good coding practice to explicitly enumerate these methods.
Part of #1732

[Utilities] clean dispatch in MA.promote_operation

---

src/Utilities/cachingoptimizer.jl

[Utilities] move CachingOptimizer to internal constructors

---

.github/workflows/aqua.yml
src/Utilities/cachingoptimizer.jl
src/Utilities/functions.jl

Damn. There are some pretty complicated ones here. I'll comment inline. GitHub action still to come because there are a few errors.

Add Aqua.jl as a CI job and fix remaining errors

---

docs/src/reference/models.md
src/Utilities/cachingoptimizer.jl
src/instantiate.jl
test/instantiate.jl

The main use case for this is that once a solver defines a fast `copy_to` method with a `MatrixOfConstraint` model, then it can use it as cache directly to avoid having to store an extra cache. As `instantiate` is used by JuMP, this will be what's used by default in JuMP.

Allow changing default cache for instantiate

---

.github/workflows/CompatHelper.yml
.github/workflows/ci.yml
Project.toml
src/Bridges/Bridges.jl
src/MathOptInterface.jl
src/Test/Test.jl
src/Utilities/Utilities.jl

Initial prep for v1.0 release

---

src/Utilities/sets.jl
test/Utilities/sets.jl

This is needed to make this work at the JuMP level:
```julia
julia> @constraint(model, im * x == 1)
ERROR: MethodError: no method matching shift_constant(::MathOptInterface.EqualTo{Float64}, ::ComplexF64)
Closest candidates are:
shift_constant(::Union{MathOptInterface.EqualTo{T}, MathOptInterface.GreaterThan{T}, MathOptInterface.LessThan{T}}, ::T) where T at ~/.julia/packages/MathOptInterface/IQWV4/src/Utilities/sets.jl:38
shift_constant(::MathOptInterface.Interval, ::Any) at ~/.julia/packages/MathOptInterface/IQWV4/src/Utilities/sets.jl:49
shift_constant(::MathOptInterface.Test.UnknownScalarSet, ::Any) at ~/.julia/packages/MathOptInterface/IQWV4/src/Test/test_model.jl:14
Stacktrace:
[1] build_constraint(_error::Function, expr::GenericAffExpr{ComplexF64, VariableRef}, …
```

Automatic promotion with shift_constant

---

Project.toml
docs/src/release_notes.md
src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

Closes jump-dev/MathOptInterface.jl#1750
Closes https://github.com/jump-dev/JuMP.jl/issues/2887

Fix bug in which OptimizerAttributes were not copied to a CachingOptimizer

---

src/Utilities/matrix_of_constraints.jl
test/Utilities/matrix_of_constraints.jl

Detected by https://github.com/jump-dev/ECOS.jl/pull/137

Canonicalize function in add_constraint for MatrixOfConstraints

---

src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

This allows to use a `CachingOptimizer` with a `MatrixOfConstraint` cache with the workflow: `add_variable`, `add_constraint`, `optimize`.

Call final_touch in optimize in CachingOptimizer

---

src/Test/test_model.jl
test/Test/Test.jl

Fix bug in test_model_ScalarFunctionConstantNotZero

---

src/Bridges/Constraint/soc_to_psd.jl
test/Bridges/Constraint/soc_to_psd.jl

Closes #1761 
The premise of using a RotatedSecondOrderCone in dimension 2 has always seemed a bit iffy to me.

[Bridges] error in RSOCtoPSD when dimension is 2

---

src/Utilities/universalfallback.jl
test/Utilities/universalfallback.jl

This would be needed here:
https://github.com/jump-dev/Clp.jl/blob/6a6ebbf637f8933718645137e343bb969e1578e0/src/MOI_wrapper/MOI_wrapper.jl#L334-L339
Currently, the unsupported parts will just be ignored.
This is a blocker for Clp.jl and ECOS.jl releases. Using it allows to fix the last remaining failing tests in https://github.com/jump-dev/Clp.jl/pull/130

Add UniversalFallback utility to throw unsupported attributes and constraints

---

src/Test/test_objective.jl

With SDPA:
```julia
test_objective_ObjectiveFunction_blank: Test Failed at /home/runner/.julia/packages/MathOptInterface/FHFUH/src/Test/test_objective.jl:195
Expression: MOI.get(model, MOI.ObjectiveValue()) == T(0)
Evaluated: 1.3932339049530345e-8 == 0.0
```
See https://github.com/jump-dev/SDPA.jl/runs/5383637798?check_suite_focus=true#step:6:616

Use tolerance to compare value of blank objective in test

---

src/Test/test_model.jl

Modifies `test_model_UpperBoundAlreadySet` to match the implementation of `test_model_LowerBoundAlreadySet`.   In particular, fixes potential errors for solvers that do not support `MOI.delete` 
by mirroring the requirement ```@requires _supports(config, MOI.delete)``` as in the lower bound test.

Fix to test_model_UpperBoundAlreadySet

---

src/Test/test_infeasibility_certificates.jl

[Test] add check for DualObjectiveValue and ConstraintPrimal in certificate tests

---

src/Utilities/cachingoptimizer.jl
src/instantiate.jl
test/FileFormats/FileFormats.jl
test/instantiate.jl

Alternative to #1780
This will need JuMP to lower-bound it's dependence on MOI, but that's okay. This is really a bug-fix, so I plan to tag as 1.1.1.
```julia
julia> using MathOptInterface; const MOI = MathOptInterface
MathOptInterface
julia> MOI.instantiate(MOI.FileFormats.NL.Model)
An AMPL (.nl) model
julia> MOI.instantiate(MOI.FileFormats.NL.Model; with_bridge_type = Float64)
MOIB.LazyBridgeOptimizer{MOIU.CachingOptimizer{MOI.FileFormats.NL.Model, MOIU.UniversalFallback{MOIU.Model{Float64}}}}
with 0 variable bridges
with 0 constraint bridges
with 0 objective bridges
with inner model MOIU.CachingOptimizer{MOI.FileFormats.NL.Model, MOIU.UniversalFallback{MOIU.Model{Float64}}}
in state EMPTY_OPTIMIZER
in mode AUTOMATIC
with model cache MOIU.UniversalFallback{MOIU.Model{Float64}}
fallback …
```

Relax AbstractOptimizer requirement in instantiate

---

Project.toml
docs/src/release_notes.md

One question: is a new test a patch or minor release?

Prep for v1.1.1

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl
test/FileFormats/LP/models/invalid_sos_constraint.lp
test/FileFormats/LP/models/invalid_sos_set.lp
test/FileFormats/LP/models/model1_tricky.lp

[FileFormats] fix read and write of SOS constraints in FileFormats.LP

---

docs/src/submodules/Test/overview.md

[docs] clarify how to re-run excluded tests in a solver

---

docs/src/submodules/FileFormats/reference.md
src/FileFormats/SDPA/SDPA.jl

Preview doc at https://jump.dev/MathOptInterface.jl/previews/PR1797/
Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1796

Improve FileFormats.SDPA.Model docstring and include it in doc

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl

[FileFormats.MPS] Fix to stop writing OBJSENSE by default

---

docs/src/submodules/FileFormats/overview.md
src/FileFormats/FileFormats.jl
src/FileFormats/MPS/MPS.jl
src/FileFormats/utils.jl
test/FileFormats/MPS/MPS.jl

[FileFormats] add option for generic names

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl

Closes #1809. The LP reader is still immature compared to the other formats.

[FileFormats] fix default lower bound in LP reader

---

docs/src/submodules/Nonlinear/overview.md
src/Nonlinear/evaluator.jl
src/Nonlinear/model.jl
src/Nonlinear/parse.jl
test/Nonlinear/Nonlinear.jl

Closes #1817 
To avoid breakage, we'd move the `_expr_to_constraint` code back into JuMP, and then it's up to JuMP if it wants to break things.

[Nonlinear] change Nonlinear.add_constraint to accept function and set

---

src/Utilities/DoubleDicts.jl
src/Utilities/copy.jl
src/Utilities/copy/index_map.jl
src/Utilities/functions.jl

I'm investigating some performance problems with a facility location problem: https://github.com/jump-dev/JuMPPaperBenchmarks/blob/main/benchmark/facility.jl
```Julia
function _benchmark(n)
model = Model(Gurobi.Optimizer)
set_silent(model)
solve_facility(model, n, n)
end
```
Before
```julia
julia> @time _benchmark(60);
Academic license - for non-commercial use only - expires 2022-06-19
9.661598 seconds (57.29 M allocations: 4.051 GiB, 28.08% gc time)
julia> @time _benchmark(60);
Academic license - for non-commercial use only - expires 2022-06-19
8.932473 seconds (57.29 M allocations: 4.051 GiB, 23.78% gc time)
```
After
```julia
julia> @time _benchmark(60);
Academic license - for non-commercial use only - expires 2022-06-19
7.956889 seconds (47.67 M allocations: 3.210 GiB, 25.95% gc time) …
```

Fix various performance issues

---

src/modifications.jl
test/Utilities/cachingoptimizer.jl

Many solvers support changing many coefficients at once.
Some examples are functions in Gurobi (https://www.gurobi.com/documentation/9.5/refman/c_xchgcoeffs.html) and Xpress (https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/XPRSchgmcoef.html).
This is a draft about making an MOI version of such methods and a proper fallback. Honestly, I don't know what would be the best approach but I am happy to make a PR with the correct implementation.

MOI.modify version for multiple changes at once

---

docs/src/reference/standard_form.md
src/Test/test_basic_constraint.jl
src/Test/test_cpsat.jl
src/Utilities/model.jl
src/sets.jl
test/sets.jl

Part of #1805
This adds:
* Cumulative
* BinPacking
* Table
* Circuit
* Path

Add constraint programming sets

---

docs/src/reference/standard_form.md
src/Test/test_basic_constraint.jl
src/Test/test_cpsat.jl
src/Utilities/model.jl
src/sets.jl
test/sets.jl

Part of #1805
Stacked on #1826 to avoid conflicts.
This set could use some bikeshedding. 
Minizinc calls it `among`, https://www.minizinc.org/doc-2.5.5/en/lib-globals.html, but what about:
* `Count`
* `CountAmong`
* `CountIn`
* `CountWithin`
* `CountInSet`
* `CountBelongs`
ConstraintProgrammingExtensions had a much more complicated setup, where there was `Count{<:AbstractSet}`, https://github.com/JuliaConstraints/ConstraintProgrammingExtensions.jl/blob/master/src/sets_count.jl. The generality was nice, but it would be quite hard to implement and might be too general.

Add CountBelongs set

---

src/Test/Test.jl

This PR makes a small change in `src/Tedst/Test.jl`. Currently it runs `include` over all the files that starts with `test_` in `src/Test` directory, but this can cause an issue when the coverage data are generated (e.g., https://github.com/MadNLP/MadNLP.jl/runs/6478904950?check_suite_focus=true#step:4:272). 
To avoid this behavior, we now also check that the file ends with `.jl` extension.

Test.jl check files ending with .jl

---

src/FileFormats/NL/NL.jl
src/FileFormats/NL/read.jl
test/FileFormats/NL/NL.jl
test/FileFormats/NL/read.jl

```Julia
julia> using JuMP, Ipopt
julia> model = read_from_file("/Users/Oscar/.julia/dev/MathOptInterface/test/FileFormats/NL/data/hs071ampl.nl")
A JuMP Model
Minimization problem with:
Variables: 4
Objective function type: AffExpr
`VariableRef`-in-`MathOptInterface.GreaterThan{Float64}`: 4 constraints
`VariableRef`-in-`MathOptInterface.LessThan{Float64}`: 4 constraints
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.
julia> set_optimizer(model, Ipopt.Optimizer)
This is Ipopt version 3.14.4, running with linear solver MUMPS 5.4.1.
Number of nonzeros in equality constraint Jacobian...:        4
Number of nonzeros in inequality constraint Jacobian.:        4
Number of nonzeros in Lagrangian Hessian.............:       24 …
```

[FileFormats.NL] add read!(::IO, ::Model)

---

src/Bridges/Objective/Objective.jl
src/Bridges/Objective/bridges/functionize.jl
src/Bridges/Objective/bridges/slack.jl

Navigating the Bridges submodule is confusing, because there are a large number of files, and they aren't clear whether it's a utility file used in lots of places, or a single implementation of a bridge. 
This PR creates a directory structure like:
```
/src
/Bridges
/Objective
Objective.jl
bridge.jl
map.jl
single_bridge_optimizer.jl
/bridges
functionize.jl
slack.jl
```
and moves the definition of each bridges constant into the corresponding file.

[Bridges] re-organize the Objective bridges folder

---

src/Bridges/Variable/Variable.jl
src/Bridges/Variable/bridges/flip_sign.jl
src/Bridges/Variable/bridges/free.jl
src/Bridges/Variable/bridges/rsoc_to_psd.jl
src/Bridges/Variable/bridges/soc_rsoc.jl
src/Bridges/Variable/bridges/vectorize.jl
src/Bridges/Variable/bridges/zeros.jl
src/Bridges/Variable/set_map.jl

Same reason as #1851. This found some bridges hiding at the bottom of `set_map.jl`, which was confusing.

[Bridges] re-organize the Variable bridges folder

---

src/Bridges/Constraint/bridge.jl
src/Bridges/Objective/bridge.jl
src/Bridges/Variable/bridge.jl

As far as I can tell, these aren't used anywhere and they aren't tested (they have missing coverage). All calls to the functions just use the single-argument methods which only accept the bridge type.

[Bridges] remove unused methods

---

src/Bridges/Objective/bridges/functionize.jl
src/Bridges/Objective/bridges/slack.jl

I started documenting the graph part of the bridges, but trying to link to existing bridges to show how they work was pretty limiting because they aren't well documented. 
I think it'd be helpful to fully document what each bridge does in terms of the mathematical reformulation, the objective/constraint that it supports, and the nodes that it targets. 
Starting with objective bridges because there's only two of them.
Part of https://github.com/jump-dev/MathOptInterface.jl/issues/1504

[Bridges] improvements to bridge docstrings

---

Project.toml
docs/src/release_notes.md

This will be quite an important release as it adds a lot of new code. 
<s>I'd like to sneak in a few more PRs:
although we can discuss on Friday's call whether or not to do so.</s>

Prep for v1.3.0

---

docs/src/submodules/Nonlinear/reference.md
src/Nonlinear/ReverseAD/forward_over_reverse.jl
src/Nonlinear/ReverseAD/mathoptinterface_api.jl
src/Nonlinear/ReverseAD/utils.jl
src/Nonlinear/model.jl
src/Nonlinear/operators.jl
test/Nonlinear/ReverseAD.jl

Refactored from https://github.com/jump-dev/JuMP.jl/pull/2953

[ReverseAD] Add support for user-defined hessians

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/map.jl
src/Bridges/Objective/map.jl
src/Bridges/Variable/map.jl
src/Bridges/bridge_optimizer.jl
test/Bridges/Constraint/map.jl
test/Bridges/Objective/map.jl
test/Bridges/Variable/map.jl

This shouldn't have been a public method, they were in a weird place disconnected from the types, and the implementations used an un-needed anonymous function.

[Bridges] refactor print_num_bridges

---

src/Bridges/Constraint/bridges/square.jl
test/Bridges/Constraint/square.jl

There's still the giant (and infamous https://github.com/jump-dev/JuMP.jl/issues/1062) "Let S₊ be the cone of symmetric semidefinite matrices" comment, which is related to #1839. If we come to a conclusion I can tidy it up and add it to the docs properly.

[Bridges] tidy SquareBridge

---

src/Utilities/cachingoptimizer.jl
src/attributes.jl
test/attributes.jl
test/errors.jl

Closes #1777 
With @blegat's example, the state is now `EMPTY_OPTIMIZER`, and the set is `<= 2.0` as desired.
```julia
julia> using MathOptInterface
julia> const MOI = MathOptInterface
MathOptInterface
julia> MOI.Utilities.@model(
NoFreeVariablesModel,
(),
(MOI.LessThan,),
(MOI.Nonnegatives,),
(),
(),
(MOI.ScalarAffineFunction,),
(MOI.VectorOfVariables,),
()
)
MathOptInterface.Utilities.GenericModel{T, MathOptInterface.Utilities.ObjectiveContainer{T}, MathOptInterface.Utilities.VariablesContainer{T}, NoFreeVariablesModelFunctionConstraints{T}} where T
julia> function MOI.supports_constraint(
::NoFreeVariablesModel{T},
::Type{MOI.VectorOfVariables},
::Type{MOI.Reals},
) where {T}
return false
end
julia> function MOI.supports_add_constrained_variables(
::NoFreeVariablesModel, …
```

Add GetAttributeNotAllowed error

---

src/Bridges/Constraint/bridges/indicator_activate_on_zero.jl
test/Bridges/Constraint/indicator_activate_on_zero.jl

It is nice having these tests. I finally made it to the end of https://github.com/jump-dev/MathOptInterface.jl/issues/820.

[Bridges] add tests and functionality for IndicatorActiveOnFalseBridge

---

src/Bridges/Constraint/bridges/square.jl
test/Bridges/Constraint/square.jl

Closes #1830
If there are no symmetry constraints added, then we can copy-across the duals from the upper triangle to the lower triangle.

[Bridges] Fix bug in dual of PSDConeSquare bridge

---

docs/src/submodules/Nonlinear/overview.md

After reading the Nonlinear's documentation over and over, I found a few typos in the doc. This PR addresses them.

Fix minor typos in Nonlinear's documentation

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/bin_packing.jl
src/Bridges/Constraint/bridges/table.jl
test/Bridges/Constraint/bin_packing.jl
test/Bridges/Constraint/table.jl

This is quite a naïve reformulation. We could make it stronger by computing a smaller set of bins (e.g., greedily assignment), and we could add ordering constraints on the bins, so that you can only use bin 2 if bin 1 is full.

[Bridges] add constraint programming bridges

---

src/Test/test_variable.jl

Xpress had a bug https://github.com/jump-dev/Xpress.jl/pull/172, which was because we tested `min x <= 0` instead of `max x <= 0`, so it didn't appropriately check the upper bound.
I've also added a test for the lower bound.
cc @rafabench

[Test] fix ZeroOne tests with lower and upper bounds

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/all_different.jl
src/Test/test_cpsat.jl
test/Bridges/Constraint/all_different.jl

Refactored from #1901
Part of #1805

[Bridges] add AllDifferentToCountDistinctBridge

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/bin_packing.jl
test/Bridges/Constraint/bin_packing.jl

This PR update the `BinPackingToMILPBridge` to use `final_touch` and the actual bounds of the variables.

[Bridges] update BinPackingToMILPBridge to final_touch

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/count_greater_than.jl
src/Test/test_cpsat.jl
test/Bridges/Constraint/count_greater_than.jl

[Bridges] add CountGreaterThanToMILPBridge

---

src/Bridges/bridge_optimizer.jl

Added here: https://github.com/jump-dev/MathOptInterface.jl/commit/703a3ce000407b2ef14b69762bbc2f36b560586b#diff-981d3b9e81384ac450930a71b03861f26b60ba3f6435942ae7d965037106f2edR77
but seem to have never been used.

[Bridges] remove unused ObjectiveAttribute

---

src/Utilities/functions.jl
src/Utilities/objective_container.jl
src/Utilities/vector_of_constraints.jl

Closes #1921
Just seeing if how this fares in CI. We'd have to be careful here. 
From what I can tell, no one is using `modify_function` other than StochasticPrograms, which should be okay with modifying the function: https://juliahub.com/ui/Search?q=modify_function&type=code
I'll see if I can come up with an example where this would matter. My guess is something like a function being re-used in an objective and a constraint.

[Utilities] remove copy in modify_function

---

src/Bridges/bridge_optimizer.jl

Chipping away at #1504, and the complications are largely limited to `bridge_optimizer.jl`. This `reduce_bridged` method confuses me everything I read it, because it uses too many magic anonymous function calls.

[Bridges] remove reduce_bridged in favor of explicit methods

---

src/Test/test_conic.jl

Needed after https://github.com/jump-dev/MathOptInterface.jl/pull/1839
All SDP solvers are currently failing this test, see e.g., https://github.com/jump-dev/SDPA.jl/runs/7246518765?check_suite_focus=true#step:6:128

Update PSDSquare_3 test after bridge change

---

src/Utilities/parser.jl
test/Utilities/parser.jl

Part of #1945
Complex number support still not working. Debugging a problem in `Model` for some reason.

[Utilities] add support for non-Float64 number types in loadfromstring

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Just got bitten by this.
Before:
```
julia> T1 = eltype(variable_blocks)
MathOptInterface.VariableIndex
julia> T2 = eltype(1.0 * variable_blocks)
MathOptInterface.ScalarAffineFunction{Float64}
julia> promote_type(T1, T2)
MathOptInterface.AbstractScalarFunction
```
After:
```
julia> promote_type(T1, T2)
MathOptInterface.ScalarAffineFunction{Float64}
```

Add missing promotion rules

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/bridges/split_complex_zeros.jl
src/Utilities/parser.jl
test/Bridges/Constraint/split_complex_zeros.jl

The amount of little niggly things here shows how hard it is to write a bridge without these new tests.

[Bridges] fix tests for SplitComplexZerosBridge

---

docs/src/reference/models.md
docs/src/tutorials/implementing.md
src/Test/test_attribute.jl
src/attributes.jl

Addresses #1936 
I have created a `RelativeGapTolerance` attribute. If that's satisfactory code- and doc-wise, I'll do the same with `AbsoluteGapTolerance`.
TODO

Create RelativeGapTolerance and AbsoluteGapTolerance optimizer attributes

---

docs/src/manual/standard_form.md

Preview https://jump.dev/MathOptInterface.jl/previews/PR1960/manual/standard_form/
I think the tables are tidier and easier to read than the bulleted list.

[docs] tidy standard form page and add global constraints

---

Project.toml
docs/src/release_notes.md

Lots of new stuff for ComplexOptInterface that would be good to get out before JuMP-dev.
Closes https://github.com/jump-dev/MathOptInterface.jl/pull/1963

Prep for v1.7.0

---

src/Nonlinear/ReverseAD/mathoptinterface_api.jl
test/Nonlinear/ReverseAD.jl

Sparsity is confusing, and the tests we had didn't have enough complexity to catch the switch in indices.
Closes #1965.

[Nonlinear] Fix JacVec products

---

src/Test/test_linear.jl

Closes #881. 
If we merge this before tagging 1.7, we might want to run SolverTests.

[Test] add test for open Interval sets

---

docs/src/manual/standard_form.md
docs/src/reference/standard_form.md
docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Variable/Variable.jl
src/Bridges/Variable/bridges/hermitian.jl
src/Test/Test.jl
src/Test/test_conic.jl
src/Utilities/results.jl
src/sets.jl
test/Bridges/Variable/hermitian.jl

Refactored from https://github.com/jump-dev/ComplexOptInterface.jl

Add HermitianPositiveSemidefiniteConeTriangle with bridges

---

src/Bridges/Constraint/bridges/soc_rsoc.jl

I was a bit confused by `|x|`, I was wondering what was the absolute value of a vector. I agree it's a common notation for the cardinality of set but here I didn't think about it since it's not a set.

Clarify assumption for SOC bridge

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Bridges.jl
src/Bridges/Objective/Objective.jl
src/Bridges/Objective/bridges/quadratize.jl
test/Bridges/Objective/quadratize.jl

Closes #1978
This should simplify QP solvers and allow then to support only a quadratic objective.
There's a lot of double up with the `Functionize` bridge, but it was simpler to copy-paste than to extend the existing definition of `Functionize` to add new type parameters.

[Bridges] add Objective.Quadratize bridge

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/hermitian.jl
src/Utilities/functions.jl
src/Utilities/matrix_of_constraints.jl
src/Utilities/sets.jl
test/Bridges/Constraint/hermitian.jl

This is the last piece needed from MOI for complex number support in JuMP.
This was not part of ComplexOptInterface and will allow to transform hermitian LMIs into LMIs. This missing feature of ComplexOptInterface was requested in https://discourse.julialang.org/t/advice-on-optimizing-large-sdp-model-generation-with-jump-complexoptinterface/82629
cc @cgois

[Bridges] Add hermitian bridge for constraints

---

src/Test/test_conic.jl

It's not the case that the dual must be 0 (Hypatia, SDPA, and ProxSDP all find different duals). It's simpler to just remove this part of the test.

[Test] remove dual test in Hermitian_2

---

src/Test/test_cpsat.jl

SCIP was failing this test because the c variable was unbounded.
A trivial fix is to give it some finite bounds.
x-ref: https://github.com/scipopt/SCIP.jl/pull/239

[Test] fix numerics of test_cpsat_CountGreaterThan

---

src/Nonlinear/evaluator.jl
src/Nonlinear/types.jl

The main benefit of this is that modifying a parameter no longer
needs a call to initialize to reconstruct the expressions.
This fix is needed for https://github.com/jump-dev/JuMP.jl/pull/3018#issuecomment-1192049278.
x-ref https://github.com/jump-dev/JuMP.jl/issues/1185
x-ref https://github.com/jump-dev/Ipopt.jl/pull/321

[Nonlinear] lazily build ::Expr representaton of subexpressions

---

src/Test/test_linear.jl
src/Test/test_solve.jl

It's reasonable for some solvers to return `NORM_LIMIT` instead of `DUAL_INFEASIBLE` (Ipopt is one example). 
This would help meta-solvers like Pavito pass tests: https://github.com/jump-dev/Pavito.jl/pull/65

[Test] allow NORM_LIMIT in unbounded tests

---

src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

xref:
* https://github.com/jump-dev/Ipopt.jl/pull/333
* https://github.com/jump-dev/Ipopt.jl/pull/334

[Bridges] fix supports for VariableIndex attributes

---

src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

A fix for the fix in https://github.com/jump-dev/MathOptInterface.jl/pull/1991.
This is actually a super subtle part of the bridging system, and we don't have good test coverage. I think I understand the space of possible outcomes, and I've tested with Ipopt, SCS, and SDPA etc.
So before merging:

[Bridges] fix supports for VariableIndex: Take II

---

src/attributes.jl

Tidy of docstrings and a partial fix for https://github.com/JuliaDocs/Documenter.jl/issues/1934.

Tidy docstrings in attributes.jl

---

Project.toml
docs/src/release_notes.md

We need a release so that JuMP can build the updated docs: https://github.com/jump-dev/JuMP.jl/pull/3080

Prep for v1.8.2

---

src/Utilities/variables_container.jl

Limit the scope of some `MOIU` methods to avoid reaching `_single_variable_flag` (#2005)  when creating new `MOI.AbstractScalarSet` on JuMP extensions.

Add `<:SUPPORTED_VARIABLE_SCALAR_SETS` upper bound

---

src/Utilities/model.jl
test/Utilities/model.jl

[Utilities] fix unsupported get in model.jl

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl

<s>Currently, these changes mean we can read the example from #2006 without erroring, but we don't actually add the free rows to the model. I guess we could/should with a `Interval(-Inf, Inf)` set, but free rows in a MILP are pretty poor form.</s> I added the free rows; they're in the file so we should respect the user.
Closes #2006

[FileFormats.MPS] fix reading of free rows

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Part of #2017 
Recent changes to sorting have introduced allocations: 
* https://github.com/JuliaLang/julia/issues/45326
* https://github.com/JuliaLang/julia/pull/45222

Omit allocation test due to changes in sort on nightly

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/stacked_data.mps

x-ref: https://github.com/jump-dev/MathOptInterface.jl/pull/2016#issuecomment-1280818477
All solvers are maddeningly different in how they want `OBJSENSE`:
Gurobi want it on the same line https://www.gurobi.com/documentation/9.5/refman/mps_format.html
Mosek want it in field 2 (col 5) on a new line https://docs.mosek.com/10.0/pythonfusion/mps-format.html
CPLEX wants it in column 3 (not a field!) on a new line https://www.ibm.com/docs/en/icos/22.1.0?topic=extensions-objective-sense-name-offset-in-mps-files
Mosek is the only sane one here, and from testing, it seems like the rest can at least read it, so I've changed to that.x

[FileFormats.MPS] write OBJSENSE on new line, and loosen parsing rules

---

src/Test/test_attribute.jl
src/attributes.jl
test/Test/Test.jl

This PR adds a fallback for `ListOfConstraintIndices` and `NumberOfConstraints` to return default values in the case that the solver does't support the particular function-set combination.
This has come up a few times:
Closes #2011 
Closes #2010
Follow-up to #2008
We already had something similar in two places:
https://github.com/jump-dev/MathOptInterface.jl/blob/71defad7679ca34987860bbfd660fc290b1e2290/src/Utilities/struct_of_constraints.jl#L142-L150
https://github.com/jump-dev/MathOptInterface.jl/blob/71defad7679ca34987860bbfd660fc290b1e2290/src/Utilities/struct_of_constraints.jl#L132-L140
#2008 added it to two more:
https://github.com/jump-dev/MathOptInterface.jl/blob/71defad7679ca34987860bbfd660fc290b1e2290/src/Utilities/model.jl#L416-L424 …

Add fallback for ListOfConstraintIndices and NumberOfConstraints

---

src/Nonlinear/operators.jl
test/Nonlinear/Nonlinear.jl

Part of #1996. 
We've long had this discontinuity between JuMP+Ipopt and AMPLNLWriter+Ipopt, ever since I introduced it waaaaaay back in https://github.com/jump-dev/AmplNLWriter.jl/issues/15 and https://github.com/jump-dev/AmplNLWriter.jl/pull/17.
We've had to frequently address this problem on discourse. Here are three that I found through search, but there are probably more:
* https://discourse.julialang.org/t/jump-using-max-x-where-x-is-a-matrix/78451/6?u=odow
* https://discourse.julialang.org/t/using-max-in-nonlinear-constraints/21606/4?u=odow
* https://discourse.julialang.org/t/methoderror-no-method-matching-isless-int64-affexpr/69731/3?u=odow
The derivatives are non-smooth etc. But this can work nicely in situations such as:
```Julia
julia> using JuMP
julia> import Ipopt
julia> …
```

[Nonlinear] add support for multivariate min and max operators

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/bridges/zero_one.jl
src/Bridges/bridge.jl
test/Bridges/Constraint/zero_one.jl

Alternative to #1787. I think this is preferable as it's more correct in allowing other bounds to be set, even if it's a little slower by adding scalar affine inequalities (although these should get presolved out).
It also fits with the ethos of allowing users to move closer to the solver: if they use Mosek they can remove the bridges by declaring `@variable(model, 0 <= x <= 1, Int)` instead of `@variable(model, x, Bin)`.
Closes #1787
Closes #1431

[Bridges] fix Constraint.ZeroOne bridge with existing bounds

---

src/Test/test_constraint.jl

I got surprised the test fails for an optimizer even though it does not specify that it supports constraint names, shouldn't there be a `@requires` there?
Possibly also checking the requires with `Type{CI{F,S}}`

[Test] add requires for test_constraint_get_ConstraintIndex

---

src/Bridges/Objective/bridges/slack.jl

The bridge will fail with the error given in https://github.com/jump-dev/MathOptInterface.jl/issues/2035 whenever the function type is different from `T` so this should fix all these cases, not only the `Complex` case.

[Bridges] Use is_coefficient_type

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Tracking to see if #2017 changed.
But I don't expect it to have. This is a regression introduced by https://github.com/JuliaLang/julia/pull/45222.
Closes #2017

[Utilities] Re-enable allocation test from #2018

---

src/Utilities/functions.jl
test/Utilities/functions.jl

I've gone back and forward on this: https://github.com/jump-dev/MathOptInterface.jl/pull/2034
But there are cases where the scaling behavior of InsertionSort rules it out. So let's just incur the allocations and be done with it.

[Utilities] revert to QuickSort

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl

Closes #2045 
cc @matbesancon 
This fixes some of the issues:
```julia
julia> import Downloads
julia> function read_qplib(num)
num = lpad(num, 4, '0')
io = IOBuffer()
Downloads.download("https://qplib.zib.de/lp/QPLIB_$(num).lp", io)
seekstart(io)
model = MOI.FileFormats.LP.Model()
Base.read!(io, model)
return model
end
read_qplib (generic function with 1 method)
julia> read_qplib(0032)
A .LP-file model
julia> read_qplib(0678)
A .LP-file model
julia> read_qplib(0681)
A .LP-file model
julia> read_qplib(2073)
A .LP-file model
julia> read_qplib(3729)
A .LP-file model
```
but it doesn't fix the zlib errors (which I think are just because the files are so large?)

[FileFormats.LP] more fixes from QPLIB

---

src/FileFormats/NL/NL.jl
src/FileFormats/NL/NLExpr.jl
src/Nonlinear/ReverseAD/forward_over_reverse.jl
src/Nonlinear/operators.jl
test/FileFormats/NL/NL.jl
test/Nonlinear/Nonlinear.jl
test/Nonlinear/ReverseAD.jl

Part of #1996 
This now works, where previously it errored.
```julia
julia> using JuMP, Ipopt
julia> p = 1.5
1.5
julia> model = Model(Ipopt.Optimizer)
A JuMP Model
Variables: 0
Solver name: Ipopt
julia> @variable(model, -10 <= x <= 10, start = 1.0)
x
julia> @NLobjective(model, Min, ifelse(x > 0, x^p, -(-x)^p))
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
Ipopt is released as open source code under the Eclipse Public License (EPL).
For more information visit https://github.com/coin-or/Ipopt
****************************************************************************** …
```

[Nonlinear] fix situations in which the result of ^ is Complex

---

src/Utilities/CleverDicts.jl
src/Utilities/vector_of_constraints.jl

These were no help at all, on the contrary.
Before:
```
julia> main()
typeof(keys(d)) = Vector{MathOptInterface.VariableIndex}
0.361756 seconds (2 allocations: 762.939 MiB, 19.29% gc time)
0.064835 seconds
```
After:
```
julia> main()
typeof(keys(d)) = Base.KeySet{MathOptInterface.VariableIndex, MathOptInterface.Utilities.CleverDicts.CleverDict{MathOptInterface.VariableIndex, Int64, typeof(MathOptInterface.Utilities.CleverDicts.key_to_index), typeof(MathOptInterface.Utilities.CleverDicts.index_to_key)}}
0.032200 seconds
0.062263 seconds
```
Code:
```julia
using MathOptInterface
const CleverDicts = MathOptInterface.Utilities.CleverDicts
function build(N::Int)
d = CleverDicts.CleverDict{MathOptInterface.VariableIndex, Int}()
for i in 1:N
CleverDicts.add_item(d, i)
end
return d
end
function …
```

Remove special iterators from CleverDict

---

docs/src/submodules/Utilities/reference.md
src/Utilities/Utilities.jl
src/Utilities/distance_to_set.jl
test/Utilities/distance_to_set.jl

Docs: https://jump.dev/MathOptInterface.jl/previews/PR2048/submodules/Utilities/reference/#Set-utilities
Reviving the ghost of https://github.com/jump-dev/MathOptInterface.jl/pull/1023
These definitions have been working fine in JuMP, and providing a public API will let external packages add new definitions (even if it's piracy). x-ref #2033.
The up-for-debate topic is the fact, after some thinking, I called it an upper bound on the Euclidean distance. I think this resolves the debate of which distance to use, and how to define it for various sets.
It's _always_ the Euclidean distance between the point and the set, it just might not be the smallest distance. It will be `0` if the point is within the set.
That'd let us define:
```julia
function distance_to_set(
point::AbstractVector{T}, …
```

[Utilities] add distance_to_set

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2075
I hate the LP file. No one has a standard. Even though it makes more sense than `Generals`, it's not documented by solvers that they support reading it.
From Gurobi:
> Valid keywords for variable type headers are: binary, binaries, bin, general, generals, gen

[FileFormats.LP] fix reading "Integer" section

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Bridges.jl
src/Bridges/Constraint/single_bridge_optimizer.jl
src/Bridges/Objective/Objective.jl
src/Bridges/Objective/bridge.jl
src/Bridges/Objective/bridges/vector_slack.jl
src/Bridges/Objective/map.jl
src/Bridges/Objective/single_bridge_optimizer.jl
src/Bridges/bridge.jl
src/Bridges/bridge_optimizer.jl
src/Bridges/debug.jl
src/Bridges/lazy_bridge_optimizer.jl
src/Test/test_multiobjective.jl
src/Utilities/objective_container.jl
src/attributes.jl
test/Bridges/Objective/vector_slack.jl

This is a re-hash of https://github.com/jump-dev/MathOptInterface.jl/pull/968
The last PR lost steam because of the discussion in https://github.com/jump-dev/JuMP.jl/issues/2099
My sense is that this is still the right API approach at the MOI-level, but that it's the wrong approach at the JuMP level. I'm working on a PR to JuMP: https://github.com/jump-dev/JuMP.jl/pull/3176, <s>so let's hold off comments until things are working fully and we can discuss the full API, rather than the pros and cons of treating multi-criteria as vector optimization.</s>
I have a proof-of-concept solver at https://github.com/odow/MOO.jl and a PR for Gurobi is https://github.com/jump-dev/Gurobi.jl/pull/497.
Instead of having a vector-valued objective, we could instead add a vector of scalar objectives.
The …

Add support for vector-valued objective functions

---

src/Utilities/distance_to_set.jl
test/Utilities/distance_to_set.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/2033. 
We'll need to decide what sets we use exact methods for, and what we make up.
Boyd's book is: https://web.stanford.edu/~boyd/papers/pdf/prox_algs.pdf

[Utilities] add distance_to_set for SecondOrderCone

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/bridges/bin_packing.jl
src/Bridges/Constraint/bridges/count_belongs.jl
src/Bridges/Constraint/bridges/count_distinct.jl
src/Bridges/Constraint/bridges/count_distinct_reif.jl
src/Bridges/Constraint/bridges/count_greater_than.jl
test/Bridges/Constraint/bin_packing.jl
test/Bridges/Constraint/count_belongs.jl
test/Bridges/Constraint/count_distinct.jl
test/Bridges/Constraint/count_distinct_reif.jl
test/Bridges/Constraint/count_greater_than.jl

Closes #2088 
So I think the previous implementation was technically correct, if a little slower than need be because it would always reformulate.
Now we cache the bounds and only reformulate if the bounds have changed since the last call.
This fixes the original SCIP issue:
```Julia
julia> using JuMP, SCIP
julia> model = Model(SCIP.Optimizer)
A JuMP Model
Variables: 0
Solver name: SCIP
julia> @variable(model, 0 <= s <= 2, Int)
s
julia> @variable(model, n)
n
julia> @constraint(model, s + n <= 3)
s + n ≤ 3.0
julia> @constraint(model, [n, s] in MOI.CountBelongs(2, Set([1])))
[n, s] ∈ MathOptInterface.CountBelongs(2, Set([1]))
presolving:
(round 1, fast)       1 del vars, 1 del …
```

Fix and test that Bridges.final_touch can be called multiple times

---

test/FileFormats/MOF/MOF.jl

Turns out this was already supported, but good to have some additional tests.

[FileFormats.MOF] add tests for vector-valued objective functions

---

docs/make.jl

The last few doc builds have been failing because of linkcheck, so let's just skip for now.

[docs] skip some links in linkcheck

---

src/Utilities/product_of_sets.jl
test/Utilities/matrix_of_constraints.jl

I got this error when working on https://github.com/jump-dev/DiffOpt.jl/pull/231. For a program with a quadratic objective and no constraints except variable bounds, the DiffOpt's product of sets don't record any set type hence the product of sets has no set type.

[Utilities] Fix for empty product of sets

---

src/Test/test_basic_constraint.jl

x-ref #2102
SolverTests are still failing because the Parameter set has some non-standard interpretations (it doesn't make sense to have `ScalarAffineFunction-in-Parameter` constraints).

Remove test_basic_F_Parameter because it does not support generic constraints

---

docs/src/reference/standard_form.md
src/functions.jl
src/indextypes.jl

A follow-up to #2099 
Preview: https://jump.dev/MathOptInterface.jl/previews/PR2108/reference/standard_form/

Tidy functions.jl and improve docstrings

---

Project.toml
docs/src/changelog.md

This release is necessary so that I can add the Google style guide to the full JuMP documentation.

Prep for v1.13.1

---

docs/.vale.ini
docs/src/background/duality.md
docs/src/changelog.md
docs/src/manual/constraints.md
docs/src/tutorials/mathprogbase.md
docs/styles/Vocab/JuMP-Vocab/accept.txt

x-ref https://github.com/jump-dev/JuMP.jl/pull/3263

[docs] modify the TokenIgnores in vale for fewer false negatives

---

docs/src/manual/variables.md
docs/src/submodules/FileFormats/overview.md
docs/src/submodules/Nonlinear/overview.md
docs/src/submodules/Utilities/overview.md
docs/src/tutorials/manipulating_expressions.md
src/Utilities/print.jl
src/functions.jl
src/sets.jl
test/Utilities/print.jl

Closes #2111 
Open to ideas for what we should print, exactly.
Docstrings can all be updated using `--fix` when building the docs:
```julia
julia> ARGS
1-element Vector{String}:
"--fix"
julia> include("docs/make.jl")
WARNING: redefinition of constant _PAGES. This may fail, cause incorrect answers, or produce other errors.
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
[ Info: Skipped ExpandTemplates step (doctest only).
[ Info: Skipped CrossReferences step (doctest only).
[ Info: Skipped CheckDocument step (doctest only).
[ Info: Skipped Populate step (doctest only).
[ Info: Skipped RenderDocument step (doctest only).
3.325270 seconds (4.70 M allocations: 319.401 MiB, 3.95% gc time)
┌ Warning: Documenter could not auto-detect the building …
```

Print algebraic form of AbstractFunction by default

---

src/Bridges/Bridges.jl
src/Bridges/Variable/bridges/free.jl
src/Bridges/Variable/bridges/rsoc_soc.jl
src/Bridges/Variable/bridges/soc_rsoc.jl
src/Bridges/Variable/bridges/vectorize.jl
src/Bridges/Variable/set_map.jl
src/Bridges/bridge.jl
src/Bridges/bridge_optimizer.jl

x-ref #2115 
This is actually a rabbit hole that I'm yet to make my way out of...

Test support for VariablePrimalStart in Bridges.Variable

---

src/Nonlinear/parse.jl
test/Nonlinear/Nonlinear.jl

A common example of such a type is a DenseAxisArray.
Raised on Discourse: https://discourse.julialang.org/t/issue-with-memoization-with-jump-for-nlp-when-adding-nlobjective/96033

[Nonlinear] fix splatting when collection does not support reverse

---

src/Test/Test.jl
test/Test/Test.jl

Closes #2127
We can't disambiguate the existing tests with only `String` arguments. But supporting regex is both generally useful, and allows specifying exact string matches.

[Test] support Regex in the include and exclude arguments to Test.runtests

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/bridges/count_distinct_reif.jl
src/Bridges/Constraint/bridges/det.jl
src/Bridges/Constraint/bridges/geomean.jl
src/Bridges/Constraint/bridges/indicator_sos.jl
src/Bridges/Constraint/bridges/norm_one.jl
src/Bridges/Constraint/bridges/norm_spec_nuc_to_psd.jl
src/Bridges/Constraint/bridges/relentr_to_exp.jl
src/Bridges/Constraint/bridges/table.jl
src/Bridges/Objective/bridges/slack.jl
src/Bridges/Objective/bridges/vector_slack.jl
src/Bridges/bridge.jl
src/Bridges/debug.jl
test/Bridges/debug.jl
test/Bridges/lazy_bridge_optimizer.jl
test/Bridges/utilities.jl

Working on https://github.com/jump-dev/JuMP.jl/issues/3301
But it required a little more work than I initially expected. 
To test out different functions and sets, we need to do it with the type information only. 
This mostly works, except that some bridges _may_ add some constraints depending on runtime values, whereas we must now report the union of all possible things added. This could be confusing, because it may say some things are added when the real model won't have them, but it clarifies that a solver must support all possible runtime constraints to use a bridge.
The main example of this is the objective slack bridge, which adds a `>=` or `<=` constraint, depending on the objective sense.
We also need bridges to report that they add `x in Reals` if they add variables.
TODO:

[Bridges] change print_active_bridges to use types instead of runtime objects

---

src/Bridges/debug.jl
test/Bridges/debug.jl

I missed an edge case: if a variable is unsupported and is bridged by a constraint instead.
x-ref https://github.com/jump-dev/JuMP.jl/issues/3301

[Bridges] fix bug in print_active_bridges

---

Project.toml
docs/src/changelog.md

This is needed before we can update JuMP's documentation: https://github.com/jump-dev/JuMP.jl/pull/3315.

Prep for v1.14.1

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Objective/Objective.jl
src/Bridges/Objective/bridges/vector_functionize.jl
src/functions.jl
test/Bridges/Objective/vector_functionize.jl
test/functions.jl

x-ref https://github.com/jump-dev/MultiObjectiveAlgorithms.jl/issues/61

[Bridges] add Objective.VectorFunctionizeBridge

---

src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

This is a bit of a weird case: if you delete a variable that was an objective, does the type of the objective change, or do we remove one of the objective rows?
I obviously thought so when writing the tests
https://github.com/jump-dev/MathOptInterface.jl/blob/403bc583628682ea6f11b4343fa91b621f2862cf/src/Test/test_multiobjective.jl#L21-L35
but I missed the case that this could also be bridged.

[Bridges] fix deleting variable in bridged objective

---

test/Bridges/Constraint/quad_to_soc.jl
test/Bridges/Objective/slack.jl

Closes #2153
@blegat everything looks okay to me.

[Bridges] add tests for deleting variable in bridged objective

---

docs/src/developer/checklists.md
docs/src/submodules/FileFormats/overview.md
src/FileFormats/MOF/MOF.jl
src/FileFormats/MOF/mof.1.4.schema.json
src/FileFormats/MOF/read.jl
src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl
test/FileFormats/MOF/nlp.mof.json

x-ref https://github.com/jump-dev/MathOptFormat/pull/28
updated in `src/FileFormats/MOF/MOF.jl`
`test/FileFormats/MOF/MOF.jl`

[FileFormats.MOF] update to v1.4

---

src/Bridges/Constraint/bridges/hermitian.jl
test/Bridges/Constraint/hermitian.jl

[Bridges] fix bug in HermitianToSymmetricPSDBridge

---

.github/workflows/solver-tests.yml
src/functions.jl
test/functions.jl

Showed up in https://github.com/jump-dev/MathOptInterface.jl/pull/2172
MosekTools fails tests because of:
It's pretty reasonable that we should skip zero terms when converting.
Check that it fixes Mosek

Fix convert(::VariableIndex, ::ScalarAffineFunction) with zero coefficients

---

Project.toml
docs/src/changelog.md

https://github.com/jump-dev/MathOptInterface.jl/actions/runs/4974400735

Prep for v1.16.0

---

src/Test/test_solve.jl

These test would have caught bugs in Hypatia: 
* https://github.com/chriscoey/Hypatia.jl/pull/826
* https://github.com/chriscoey/Hypatia.jl/issues/823
cc @lkapelevich 
TODO

[Test] add tests for NormNuclearCone, NormSpectralCone and HermitianPSDCone

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Useful for https://github.com/jump-dev/JuMP.jl/pull/3381

Add value_type for AbstractFunction

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl

Closes #2181.
This was my fault in https://github.com/jump-dev/MathOptInterface.jl/pull/1974. I guess I didn't understand the convention well enough. 
It's literally the coefficients as written multiplied by 0.5. Not what MOI does and assume that you're passing one of the off-diagonals. (This is another motivation for changing the definition of ScalarQuadraticFunction in MOI v2 https://github.com/jump-dev/MathOptInterface.jl/issues/2180)
Docs: https://www.ibm.com/docs/en/icos/12.8.0.0?topic=representation-quadratic-terms-in-lp-file-format

[FileFormats.LP] fix reading off-diagonals of quadratic functions

---

.github/workflows/ci.yml
src/Bridges/Constraint/bridges/vectorize.jl
src/Utilities/functions.jl
test/Bridges/Constraint/flip_sign.jl
test/Bridges/Constraint/vectorize.jl

I guess I didn't run `solver-tests.yml` on the ScalarNonlinearFunction PR recently.
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/5108546474

Fix promote_operation for ScalarNonlinearFunction

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl

Closes #2181
cc @inversed-ru can you try this branch? You can install it with `] add MathOptInterface#od/fix-quadratic-newlinne`

[FileFormats.LP] fix new lines in middle of quadratic objective

---

src/Test/test_model.jl

Manopt.jl only supports variables in manifolds, see https://github.com/JuliaManifolds/Manopt.jl/pull/266

Add missing @require in tests

---

src/Test/test_objective.jl

I want to exclude this attribute in https://github.com/JuliaManifolds/Manopt.jl/pull/264

Require list of model attributes in tests

---

src/Bridges/Objective/bridges/slack.jl
test/Bridges/Objective/slack.jl

x-ref https://github.com/jump-dev/JuMP.jl/pull/3271
@blegat, it seemed to me that we would never want to set this to something other than `-1` for the dual and `0` for the slack primal, so I opted to consolidate everything into a single attribute.
Does this seem right? Or am I missing something?

[Bridges] add SlackBridgePrimalDualStart

---

src/Bridges/Constraint/bridges/count_belongs.jl
src/Bridges/Constraint/bridges/count_distinct.jl
src/Bridges/Constraint/bridges/count_distinct_reif.jl
src/Bridges/Constraint/bridges/norm_to_power.jl
src/Bridges/Constraint/bridges/quad_to_soc.jl

`operate!` may modify its argument, but it may also return a new object. These usages were buggy and incorrect. (Although, correct for now, but will break with {Vector,Scalar}NonlinearFunction

Fix incorrect usage of Utilities.operate!

---

src/Utilities/Utilities.jl
src/Utilities/functions.jl
src/Utilities/promote_operation.jl
test/Utilities/functions.jl
test/Utilities/test_promote_operation.jl

This PR consolidates the `Utilities.promote_operation` methods into a single file with tests.
<s>This is going to be a WIP until I settle on a nice design.</s>

[Utilities] refactor promote_operation

---

src/Utilities/functions.jl
src/Utilities/mutable_arithmetics.jl
src/Utilities/operate.jl
test/Utilities/test_operate!.jl

https://github.com/jump-dev/MathOptInterface.jl/pull/2208 moved a bunch of methods around and added tests, but I didn't change any behavior or merge the functionality of different methods.
This PR adds a generic `operate_term` method (which was really `operate_coefficient`), and then leverages that to simplify a number of other methods, in some cases (like univariate -) removing the specialized methods all together.
I've also "deprecated" (in documentation only) `operate_terms!` which was only used in three places in mutable arithmetics. We should aim for fewer simpler methods, instead of a potpourri of methods that we've added for special cases.

[Utilities] simplify various operate_ methods

---

src/Bridges/Constraint/bridges/soc_rsoc.jl

Bridges cannot assume that `+` and `-` are implemented for elements in a function.

[Bridges] use operate in bridges instead of Base methods

---

Project.toml
docs/src/changelog.md

https://github.com/jump-dev/MathOptInterface.jl/actions/runs/5340532776

Prep for v1.18.0

---

src/Bridges/Constraint/bridges/quad_to_soc.jl
src/Bridges/Objective/bridges/slack.jl
src/Nonlinear/operators.jl
src/Utilities/functions.jl
src/Utilities/results.jl
test/Utilities/functions.jl

Related to https://github.com/jump-dev/MathOptInterface.jl/pull/2218
Blocker for https://github.com/jump-dev/MathOptInterface.jl/pull/2201
The implementation leaves a bit to be desired (it uses recursion, and every call needs to create an operator registry), but we can address that later.

[Utilities] add eval_variables support for ScalarNonlinearFunction

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Now that the functions.jl file is a lot cleaner, some things stick out: https://github.com/jump-dev/MathOptInterface.jl/issues/2203.

[Utilities] fix various utilities for ScalarNonlinearFunction

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl

Closes #2223
We didn't handle the case in which `-infinity <= x <= infinity` was used instead of `x free`. 
But I've also refactored the reading and writing of variable bounds to explicitly write both bounds on a single line with `-infinity`.

[FileFormats.LP] fix reading file with free variable and explicit bounds

---

src/FileFormats/NL/NL.jl
src/FileFormats/NL/NLExpr.jl
src/FileFormats/NL/read.jl
src/FileFormats/NL/sol.jl
test/FileFormats/NL/NL.jl

[FileFormats.NL] add support for ScalarNonlinearFunction

---

src/FileFormats/NL/NLExpr.jl
test/FileFormats/NL/NL.jl

Missed a case from https://github.com/jump-dev/MathOptInterface.jl/pull/2228

[FileFormats.NL] fix nested scalar affine and quadratic functions

---

test/Benchmarks/Benchmarks.jl
test/runtests.jl

We're still having frequent memory issues, so let's see if this helps:
https://github.com/jump-dev/MathOptInterface.jl/issues/2183

Refactor test/Benchmarks

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/functionize.jl
src/functions.jl
test/Bridges/Constraint/functionize.jl
test/functions.jl

cc @chriscoey 
Necessary precursor to https://github.com/jump-dev/Pavito.jl/issues/67
bridge
the model:

[Bridges] add ScalarQuadraticToScalarNonlinearBridge

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/integer_to_zeroone.jl
test/Bridges/Constraint/integer_to_zeroone.jl

Closes #2202
bridge
the model:

[Bridges] add IntegerToZeroOneBridge

---

src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl

Closes #2246
@chriscoey is this enough?

[FileFormats.MOF] support writing non-Float64 functions

---

docs/src/manual/standard_form.md
docs/src/reference/standard_form.md
src/Bridges/Constraint/bridges/scalarize.jl
src/Bridges/Constraint/bridges/square.jl
src/Bridges/Constraint/bridges/vectorize.jl
src/Test/test_basic_constraint.jl
src/Test/test_multiobjective.jl
src/Test/test_nonlinear.jl
src/Utilities/functions.jl
src/Utilities/model.jl
src/Utilities/objective_container.jl
src/Utilities/operate.jl
src/Utilities/parser.jl
src/Utilities/promote_operation.jl
src/functions.jl
test/Bridges/Constraint/flip_sign.jl
test/Bridges/Constraint/scalarize.jl
test/Bridges/Constraint/square.jl
test/Bridges/Constraint/vectorize.jl
test/Utilities/functions.jl
test/Utilities/test_operate!.jl
test/Utilities/test_promote_operation.jl

Resurrecting `VectorNonlinearFunction` from the depths of https://github.com/jump-dev/MathOptInterface.jl/pull/2059.
There are two main motivating problems for this:
1. `VectorNonlinearFunction-in-Complements` constrains for nonlinear complementarity problems
- https://github.com/chkwon/PATHSolver.jl/pull/82
2. `ObjectiveFunction{VectorNonlinearFunction}` for nonlinear multi-objective problems
- https://github.com/jump-dev/MultiObjectiveAlgorithms.jl/pull/68
Documentation
https://jump.dev/MathOptInterface.jl/previews/PR2201/reference/standard_form/#MathOptInterface.VectorNonlinearFunction
I also removed this from #2059 because there we a lot of issues with the bridges, but I have a better handle on what to do now, and we can easily run `solver-tests` to catch the culprits. …

Add VectorNonlinearFunction

---

src/Bridges/Constraint/map.jl
src/Bridges/Variable/map.jl
src/Utilities/lazy_iterators.jl
test/Utilities/lazy_iterators.jl

Extracted from https://github.com/jump-dev/MathOptInterface.jl/pull/2237
It also replaces the constructor to use `lazy_map` which redirects to the right one.
The advantage of `VectorLazyMap` is that it is an `AbstractVector` hence it can be used inside a `LinearAlgebra.Diagonal` for instance.

Add VectorLazyMap

---

Project.toml
docs/src/changelog.md

https://github.com/jump-dev/MathOptInterface.jl/actions/runs/5399018088

Prep for v1.19.0

---

src/Utilities/functions.jl
test/Utilities/functions.jl

x-ref https://github.com/jump-dev/JuMP.jl/pull/3106

[Utilities] improve performance of ScalarNonlinearFunction utilities

---

docs/src/manual/models.md
docs/src/reference/models.md
docs/src/tutorials/implementing.md
src/Test/test_attribute.jl
src/attributes.jl
src/precompile.jl
test/Utilities/cachingoptimizer.jl
test/Utilities/universalfallback.jl

This MR introduces an attribute to set an objective limit, after which the solver can stop.
This can be useful e.g. for separation routines, when one requires at least a certain objective value to be reached.
Setting this objective bound as a constraint in a feasibility formulation is often ill-advised and can lead to poor solver behaviour, most MIP solvers provide a dedicated parameter instead:
- Gurobi: https://www.gurobi.com/documentation/current/refman/bestobjstop.html#parameter:BestObjStop
- SCIP: `limits/objectivestop` is coming in the next major release
- HiGHS: objective_bound https://ergo-code.github.io/HiGHS/stable/options/definitions/#objective_bound
CPLEX seems to have [this](https://www.ibm.com/docs/en/icos/20.1.0?topic=parameters-lower-objective-value-limit) but it seems to …

adding ObjectiveLimit attribute

---

docs/src/submodules/FileFormats/overview.md
src/FileFormats/MOF/MOF.jl
src/FileFormats/MOF/mof.1.5.schema.json
src/FileFormats/MOF/read.jl
src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl
test/FileFormats/MOF/nlp.mof.json

Closes #2248 
updated in `src/FileFormats/MOF/MOF.jl`
`test/FileFormats/MOF/MOF.jl`

[FileFormats.MOF] add support for Scaled set

---

src/Bridges/Constraint/bridges/set_dot_scaling.jl
test/Bridges/Constraint/set_dot_scaling.jl

Potential fix for https://github.com/jump-dev/MathOptInterface.jl/pull/2262#issuecomment-1709227184.
I don't really understand what's going here, but it makes sense that the adjoint should be the opposite of the forward map? That's what it is for `SetDotScalingBridge`, so I think this is just a typo.
Seemed to fix SDPA, so I'll re-run solver-tests on this branch: https://github.com/jump-dev/MathOptInterface.jl/actions/runs/6103555292

[Bridges] fix adjoint functions in SetDotInverseScalingBridge

---

src/Test/test_conic.jl

x-ref #2268 
These ones are all needed for calls like
```
ones(T, 4)
```
because JET can't tell if `T` is a type or an `Int`, so it annotate the return type as `ones(T,4)::Union{Vector{T},Matrix{Float64}`.
Locally, I'm down to `═════ 172 possible errors found ═════`

Fix various JET errors in test_conic.jl

---

src/Bridges/Bridges.jl
src/Bridges/Variable/map.jl
src/FileFormats/CBF/CBF.jl
src/FileFormats/MPS/MPS.jl
src/FileFormats/NL/NL.jl
src/FileFormats/SDPA/SDPA.jl
src/Nonlinear/evaluator.jl
src/Nonlinear/operators.jl
src/Utilities/objective_container.jl
src/Utilities/universalfallback.jl

Part of #2268 
Brings count from 211 down to 196. I'll comment in-line.

Fix various JET errors

---

src/Bridges/Constraint/bridges/interval.jl
test/Bridges/Constraint/interval.jl

This was another case that JET found (#2268), so working through them all seems valuable.

[Bridges] fix ConstraintDualStart for Constraint.SplitIntervalBridge

---

src/Bridges/bridge_optimizer.jl

This one deserved a separate commit because the changes are a little subtle.
The various Bridge submodules define EmptyMap as a fallback for when an AbstractBridgeOptimizer doesn't have an associated set of arcs (like a Variable.SingleBridgeOptimizer). But this makes all calls of .bridges(b) type unstable. And sometimes we really do want either, but sometimes (like the ones annnotated here), we want only the explicit Map.
For MOI v2, we could consider refactoring this code to remove EmptyMap in favor of a more explicit fallback like nothing.
This PR brings us down to `═════ 42 possible errors found ═════`

Fix JET errors in bridge_optimizer.jl

---

src/Bridges/bridge_optimizer.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl

This seemed like such a random design choice.
So I traced it back to https://github.com/jump-dev/JuMP.jl/commit/cb8b47ffcc9710a7e22f24b6c47f48467a20b421.
At one point, JuMP used an explicit `UTF8String` type for names, and calling `""` did not make that type, so it was convenient to have an "empty UTF8String" sitting there in one place. Even once `String` came along, we kept it, and the variable even successfully made the transition to MathOptInterface!

[Utilities] Remove EMPTYSTRING

---

src/Utilities/Utilities.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy/index_map.jl
src/Utilities/product_of_sets.jl
src/Utilities/struct_of_constraints.jl
src/Utilities/universalfallback.jl

It's pretty weird for a module to import itself under a different name.

[Utilities] remove MOIU acronym

---

src/Utilities/objective_container.jl
test/Utilities/objective_container.jl

This has the potential to be breaking if people wrote a new `modify_function!` method, but I'm marking this as a bug fix because current usage returns a MethodError.

Fix MethodError when trying to modify a variable objective

---

src/Utilities/model.jl

I don't know what this is or why it was here. From what I can tell, it was added in https://github.com/jump-dev/MathOptInterface.jl/pull/1245, but it seems like a typo. It's not hit by codecov, and it isn't part of the documented API.

[Utilities] remove invalid and unused method

---

src/Utilities/model.jl
src/Utilities/vector_of_constraints.jl

This is one of the most important files in MOI because `Utilities.Model` gets used by almost every package.
The previous version was not ordered, obscured the structs on which it operated until the very end, and used eval to save a few lines.
This made it hard to read, hard to understand, and hard to identify which methods were needed, missing, or incorrect.
The diff is quite bad, but it's just moving things around. No code changes except #2286.

[Utilities] refactor src/Utilties/model.jl

---

src/Utilities/operate.jl

Alternative fix to https://github.com/jump-dev/MathOptInterface.jl/pull/2285
The `for` loop is quite weird as you expect the list of arguments to be a `tuple` of mixed argument types.
I think there is a win of not doing the recursion and falling back to a `for` loop at some point but I think it's at least more readable to use the standard `afold` for this.
This shows a big win on @odow's benchmark in https://github.com/jump-dev/MathOptInterface.jl/issues/2284#issuecomment-1732136438
```julia
julia> import MathOptInterface as MOI
julia> using BenchmarkTools
julia> function my_operate(::typeof(+), ::Type{T}, f, g, h, args...) where {T<:Number}
ret = MOI.Utilities.operate(+, T, f, g)
ret = MOI.Utilities.operate!(+, T, ret, h)
for a in args
ret = MOI.Utilities.operate!(+, T, ret, a)
end …
```

[Utilities] use foldl to avoid StackOverflow

---

Project.toml
docs/src/changelog.md

Prep for v1.20.1

---

docs/src/manual/models.md
docs/src/reference/models.md
docs/src/tutorials/implementing.md
src/Test/test_attribute.jl
src/attributes.jl

Add SolutionLimit attribute

---

docs/make.jl
docs/src/index.md
docs/src/manual/standard_form.md

arXiv is often the cause of the docs failing; https://github.com/jump-dev/MathOptInterface.jl/actions/runs/6333485810/job/17201676749?pr=2296

[docs] add arxiv.org to linkcheck_ignore because it is flakey

---

src/Test/test_attribute.jl

x-ref https://github.com/jump-dev/SCS.jl/pull/280
SCS was throwing `GetAttributeNotAllowed`, so this test was being skipped.

[Test] improve test_attribute_TimeLimitSec

---

docs/src/submodules/FileFormats/overview.md
src/FileFormats/MOF/MOF.jl
src/FileFormats/MOF/read.jl
test/FileFormats/MOF/MOF.jl

Closes #2295 
Discussed on today's call.

[FileFormats.MOF] rename to use_nlp_block and add documentation

---

docs/styles/Vocab/JuMP-Vocab/accept.txt

Docs failed in https://github.com/jump-dev/MathOptInterface.jl/actions/runs/6428404927/job/17455533852?pr=2303 because of this, but I don't know why now and not before.

[docs] add preprint to accept.txt

---

docs/src/manual/modification.md
docs/src/reference/modification.md
docs/src/tutorials/implementing.md
src/Bridges/bridge_optimizer.jl
src/Test/test_modification.jl
src/Utilities/functions.jl
src/functions.jl
test/Bridges/bridge_optimizer.jl

Add ScalarQuadraticCoefficientChange

---

src/Nonlinear/model.jl
test/Nonlinear/Nonlinear.jl

[Nonlinear] add support for is_empty and empty!

---

src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

Closes #2306 
@blegat what do you think about this

[Bridges] add ModifyBridgeNotAllowed

---

src/Bridges/Objective/bridges/conversion.jl
test/Bridges/lazy_bridge_optimizer.jl

Current, the added test fails which means that converting to a quadratic objective is preferred over using several bridges. The bridge cost fixes this issue the same way we fixed it for the constraint conversion bridge.

Use conversion cost for Objective bridge

---

docs/src/manual/standard_form.md

[docs] fix set descriptions in standard_form.md

---

src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl

This was changed in #2293 because I thought it was a private method (not documented or exported, and very niche inside `MOI.FileFormats.MOF`, but PolyJuMP started using it:
x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2319#issuecomment-1776658350

[FileFormats] revert change to extract_function_and_set

---

src/Test/test_modification.jl

[Test] fix isapprox in test_modification_xxx_scalarquadraticcoefficientchange

---

src/Test/Test.jl

This one is up for debate. We've said that solvers can optionally support this, so some tests fail, even though it's known and okay.
Here's one from Pavito because of https://github.com/jump-dev/MathOptInterface.jl/pull/2318#issuecomment-1780291375

[Test] allow skipping ScalarFunctionConstantNotZero errors

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Bridges.jl
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/bin_packing.jl
src/Bridges/Constraint/bridges/count_belongs.jl
src/Bridges/Constraint/bridges/count_distinct.jl
src/Bridges/Constraint/bridges/count_distinct_reif.jl
src/Bridges/Constraint/bridges/count_greater_than.jl
src/Bridges/Constraint/bridges/indicator_to_milp.jl
src/Bridges/Constraint/bridges/sos1_to_milp.jl
src/Bridges/Constraint/bridges/sos2_to_milp.jl
src/Test/test_linear.jl
src/Utilities/variables.jl
test/Bridges/Constraint/indicator_to_milp.jl
test/Bridges/Constraint/sos1_to_milp.jl
test/Bridges/Constraint/sos2_to_milp.jl
test/Utilities/variables.jl

Part of #2316 
I'll need to run the solver-tests, because this should let HiGHS support SOS constraints, but it will probably also start supporting Indicator because of IndicatorToSOS, except that IndicatorToSOS introduces an unbounded variable in the SOS.
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/6620504066

[Bridges] add {SOS1,SOS2,Indicator}ToMILPBridge

---

src/Bridges/bridge.jl
test/Bridges/Constraint/bridge.jl
test/Bridges/bridge_optimizer.jl

<s>Closes</s> <s>`https://github.com/jump-dev/JuMP.jl/issues/3550`</s>

Improve error message unsupported attribute for bridges

---

src/Bridges/Constraint/bridges/all_different.jl
src/Bridges/Constraint/bridges/all_different_reif.jl
src/Bridges/Constraint/bridges/bin_packing.jl
src/Bridges/Constraint/bridges/circuit.jl
src/Bridges/Constraint/bridges/count_at_least.jl
src/Bridges/Constraint/bridges/count_belongs.jl
src/Bridges/Constraint/bridges/count_distinct.jl
src/Bridges/Constraint/bridges/count_distinct_reif.jl
src/Bridges/Constraint/bridges/count_greater_than.jl
src/Bridges/Constraint/bridges/interval.jl
src/Bridges/Constraint/bridges/soc_to_nonconvex_quad.jl
src/Bridges/Constraint/bridges/table.jl
src/Test/test_basic_constraint.jl
src/Utilities/vector_of_constraints.jl
test/Bridges/bridge_optimizer.jl
test/Utilities/model.jl

x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2318#discussion_r1374313826

[Bridges] fix some getters of ConstraintFunction and add better tests

---

docs/make.jl
docs/src/submodules/Bridges/implementation.md
docs/src/submodules/Bridges/reference.md
docs/src/submodules/Utilities/reference.md

[docs] add more docs for implementing a bridge

---

src/Bridges/Constraint/bridges/square.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/684

[Bridges] add support for Constraint{Primal,Dual}Start to SquareBridge

---

src/Bridges/Constraint/bridges/number_conversion.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/684
<s>This isn't very obvious what the return types should be, so I've opted to just leave them as-is and let the solvers deal with them.</s> I used `value_type`.

[Bridges] add support for start values in NumberConversionBridge

---

src/Bridges/Variable/bridges/parameter.jl
src/Bridges/Variable/bridges/rsoc_to_psd.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/684

[Bridges] add VariablePrimalStart support to ParameterToEqualTo and RSOCtoPSD

---

src/Utilities/print.jl
test/Utilities/print.jl

Closes #2335 
cc @WalterMadelim
I need to think about what to do for vector constraints.

[Utilities] print the name of scalar constraints in print(::ModelLike)

---

Project.toml
docs/src/changelog.md
docs/src/submodules/Bridges/list_of_bridges.md

Prep for v1.22

---

src/Bridges/Constraint/bridges/geomean.jl

I though the tests would call this since `supports` is now `true` but it seems it does not.
See https://github.com/jump-dev/MathOptInterface.jl/issues/684

[Bridges] add ConstraintPrimalStart for GeoMeanBridge

---

src/Test/Test.jl
test/Test/Test.jl

I've wanted this a number of times

[Test] add verbose kwarg to MOI.Test.runtests

---

src/Utilities/cachingoptimizer.jl
src/attributes.jl
test/Utilities/cachingoptimizer.jl

Closes #2345
But this PR needs some careful thinking.
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/6805116666

[Utilities] improve errors and docstrings for querying attributes

---

docs/src/submodules/Bridges/reference.md
src/Bridges/Constraint/bridges/functionize.jl
src/Bridges/bridge.jl
src/Utilities/functions.jl
test/Bridges/Constraint/functionize.jl
test/Bridges/bridge_optimizer.jl

I find this useful when debugging. Getting the second bridge doesn't make much sense since the first bridge might create several constraints.

[Bridges] Add MOI.Bridge.FirstBridge attribute

---

src/Utilities/sets.jl
test/Utilities/sets.jl

As a double check, there does not seem to be any difference until 100 millions.
```julia
findall(m -> isqrt(2m) != div(isqrt(1 + 8n), 2), 1:100000000)
Int64[]
```

Simpler side_dimension_for_vectorized_dimension

---

docs/src/submodules/Bridges/reference.md
src/Bridges/Constraint/bridges/soc_to_psd.jl
src/Bridges/Constraint/set_map.jl
test/Bridges/Constraint/soc_to_psd.jl

With this `MultiSetMapBridge`, it should be easy to fix other similar case, e.g., `SecondOrderCone(1)` -> `Nonnegatives(1)` while `SecondOrderCone(2)` -> `RotatedSecondOrderCone(2)` but we can wait for someone or for a test (like in this case) requesting to fix these corner cases before doing it.

Fix RSOCtoPSD bridge for dimension 2

---

src/Bridges/bridge.jl
src/Utilities/functions.jl

This change from https://github.com/jump-dev/MathOptInterface.jl/pull/2211 broke DiffOpt (see failure in https://github.com/jump-dev/DiffOpt.jl/pull/254).

Fix map_indices with attributes

---

src/Bridges/Objective/bridges/slack.jl
test/Bridges/Objective/slack.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2363

Ignore SlackBridgePrimalDualStart for non-Slack bridge

---

src/Test/test_attribute.jl

I looked at how to fix https://github.com/oxfordcontrol/COSMO.jl/pull/185 and it starts being too hacky.
The time limit can be tweaked with two attributes, `RawOptimizerAttribute("time_limit")` or `MOI.TimeLimitSec`. Both attribute actually modify the same thing so they are kept in sync. Asking for `get` to return `nothing` is maybe a bit too much:
```julia
MOI.set(model, RawOptimizerAttribute("time_limit"), 0.0)
MOI.get(model MOI.TimeLimitSec()) # what should this return ?
MOI.set(model, MOI.TimeLimitSec(), nothing)
MOI.get(model MOI.TimeLimitSec()) # returns `nothing`
MOI.set(model, RawOptimizerAttribute("time_limit"), 0.0)
MOI.get(model MOI.TimeLimitSec()) # what should this return ?
MOI.set(model, RawOptimizerAttribute("time_limit"), 1.0)
MOI.get(model MOI.TimeLimitSec()) # what …
```

Allow get to return non-nothing

---

src/Utilities/copy.jl
test/Utilities/copy.jl

Closes #2366
Replacement for:
Closes #2369
Closes #2371
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/7285412217

Fix order of model attributes during copy_to

---

src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

This is needed for https://github.com/blegat/SDPLR.jl/pull/19 to work.

[Utilities.CachingOptimizer] Enable fallback for ConstraintDual of variable indices

---

src/Bridges/Constraint/map.jl
src/Bridges/Variable/map.jl
src/Bridges/bridge_optimizer.jl
test/Bridges/Constraint/map.jl
test/Bridges/Variable/map.jl
test/Bridges/bridge_optimizer.jl
test/Bridges/lazy_bridge_optimizer.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/pull/2358

[Bridges] Fix ConstraintIndex conflicts between variable and constraint bridges

---

src/Bridges/Constraint/bridges/functionize.jl
src/Bridges/Variable/map.jl
test/Bridges/lazy_bridge_optimizer.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/pull/2357

[Bridges] Fix deletion corner cases

---

src/Bridges/bridge_optimizer.jl
src/Utilities/variables_container.jl
test/Bridges/lazy_bridge_optimizer.jl
test/Bridges/sdpa_models.jl

Closes #2375
When looking over the failing tests of https://github.com/blegat/SDPLR.jl/, I noticed some were due to MOI bugs. When looking at how to reproduce them, I found out that we could have detected them by running against all the tests. Looking back at the history, it seems I initially just called `nametest` because it wasn't so easy to run all the tests. When @odow migrated to the new test infrastructure, he used `include = ["ConstraintName", "VariableName"],` so that's its equivalent to `nametest`. This did not take the opportunity brought by this new test infrastructure to run it against all the tests. These tests are usually failing for all solvers so fixing them should help many solver wrappers at the same time.
This brings up a few bugs that I suggest we first fix in separate …

Run all tests against bridged SDPA model

---

src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl
test/Bridges/lazy_bridge_optimizer.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/pull/2357

[Bridges] Fix ListOfVariablesWithAttributeSet

---

src/Bridges/Variable/map.jl
src/Bridges/bridge_optimizer.jl
test/Bridges/Variable/map.jl
test/Bridges/lazy_bridge_optimizer.jl

We could even use `MOI.Utilities.VariableContainer` but it's also storing the upper and lower bounds that we don't need here
Part of https://github.com/jump-dev/MathOptInterface.jl/pull/2357

[Bridges] Throw for bound already set on bridged variable

---

Project.toml
docs/src/changelog.md

Prep for v1.24.0

---

src/Nonlinear/evaluator.jl
test/Nonlinear/Nonlinear.jl

Found by https://github.com/jump-dev/Ipopt.jl/pull/397

[Nonlinear] fix initialize for ExprGraphOnly

---

src/functions.jl
test/functions.jl

This was the cause of @ccoffrin's mysterious 
```
bad line 721 of /tmp/model.nl: C1
Cannot open .nl file
libc++abi: terminating due to uncaught exception of type Ipopt::TNLP::INVALID_TNLP
```

Fix converting 0-valued Scalar(Affine,Quadratic)Function to Nonlinear

---

docs/src/manual/models.md
docs/src/reference/models.md
src/attributes.jl
test/attributes.jl

Add AutomaticDifferentiationBackend

---

Project.toml
docs/src/changelog.md

It's only been a couple of days since the last release, but I'd like to get these out ASAP.

Prep for v1.25.0

---

test/Bridges/Constraint/functionize.jl

Exact test is also here:
https://github.com/jump-dev/MathOptInterface.jl/blob/3a7f89189d8e2b6b2e6514b18618245975cd2366/test/Bridges/Constraint/functionize.jl#L345-L352

[Bridges] remove duplicated test

---

src/Bridges/Variable/bridges/vectorize.jl
test/Bridges/Variable/vectorize.jl
test/Bridges/lazy_bridge_optimizer.jl

One issue from #2384.
It seems simpler to throw here than to carry around a bunch of extra state about which constants we need to modify.

[Bridges] fix deleting variable in Bridges.Variable.VectorizeBridge

---

src/constraints.jl
test/constraints.jl

This is the cause of https://github.com/jump-dev/Pavito.jl/issues/73

Fix Exception supertype of LowerBoundAlreadySet and UpperBoundAlreadySet

---

.github/workflows/documentation.yml

vale v3.0.0 was recently released with breaking changes. This fixes the version for now.

[docs] fix vale version

---

Project.toml
docs/src/changelog.md

Prep for v1.25.1

---

src/Bridges/bridge_optimizer.jl
test/Bridges/lazy_bridge_optimizer.jl

[Bridges] fix getting ConstraintPrimal if Variable bridges are present

---

docs/src/submodules/Nonlinear/overview.md

cc @rluce
The other thing we didn't discuss, but I assume you figured out, is that we don't really need the `CALL_MULTIVARIATE` and `CALL_UNIVARIATE`. You could figure that out based on the number of child nodes.

[docs] clarify ordering of nonlinear tape

---

src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl

[FileFormats.MOF] fix affine and quadratic nodes in ScalarNonlinearFunction

---

Project.toml
docs/src/changelog.md

Prep for v1.25.2

---

src/Utilities/mockoptimizer.jl
src/Utilities/results.jl

[Utilities] use appropriate zero type for get_fallback

---

src/Bridges/Constraint/bridges/count_distinct.jl
test/Bridges/Constraint/count_distinct.jl

Closes #2405
This PR implements a much stronger reformulation for the special case of `[2, x ,y] in CountDistinct` which is created by `[x, y] in AllDifferent(2)`, a.k.a. `x != y`.

[Bridge] implement special case for x != y in CountDistinctToMILPBridge

---

src/FileFormats/MPS/MPS.jl
src/FileFormats/utils.jl
test/FileFormats/MPS/MPS.jl

Using the `Optimizer` from #2417 
```julia
using JuMP
function main(N)
model = direct_model(Optimizer(MOI.FileFormats.MPS.Model()))
@variable(model, 0 <= x[i in 1:N] <= 1; integer = isodd(i))
@constraint(model, [i in 2:N], x[i] + x[i-1] <= 1)
@objective(model, Max, sum(i * x[i] for i in 1:N))
MOI.write_to_file(backend(model).inner, "file.mps")
return
end
```
Before:
```julia
julia> GC.gc(); @time main(100_000);
2.005077 seconds (18.45 M allocations: 812.105 MiB, 9.98% gc time, 24.17% compilation time: 44% of which was recompilation)
julia> GC.gc(); @time main(100_000);
1.495755 seconds (17.55 M allocations: 751.348 MiB, 12.09% gc time)
julia> GC.gc(); @time main(100_000);
1.529073 seconds (17.55 M allocations: 751.348 MiB, 12.28% gc time)
```
After:
```julia
julia> GC.gc(); @time …
```

[FileFormats.MPS] improve performance of MPS writer

---

src/FileFormats/MPS/MPS.jl

https://github.com/jump-dev/MathOptInterface.jl/pull/2421 broke BilevelJuMP.
See https://github.com/joaquimg/BilevelJuMP.jl/pull/214

[FileFormats.MPS] revert change for backwards compatibility

---

src/FileFormats/MPS/MPS.jl
src/FileFormats/utils.jl
test/FileFormats/MPS/MPS.jl

The MPS writer has quadratic-ish performance because it creates GC-tracked strings for every variable and constraint. This PR shows one way we could skip this: generate the generic names on demand.
I didn't implement it for constraints because they need fancier code to deal with the constraint type parameters efficiently.
Potential alternatives:
- Use fixed-length strings as provided by WeakRefStrings
- Use WeakRefStrings.StringArray
Before:
```
148.861351 seconds (472.59 M allocations: 38.948 GiB, 40.91% gc time, 2.87% compilation time)
```
After:
```
109.157014 seconds (552.84 M allocations: 40.555 GiB, 21.95% gc time, 3.86% compilation time)
```
If we extrapolate, the version that does this approach for constraints would be around 70 sec, so we'd get a 2x speed up on this one example …

[FileFormats.MPS]: avoid creating list of variable names

---

Project.toml
docs/src/changelog.md

Prep for v1.25.3

---

src/FileFormats/NL/read.jl
test/FileFormats/NL/read.jl

[FileFormats.NL] improve error msg when parsing unhandled headers

---

src/FileFormats/NL/NL.jl
test/FileFormats/NL/NL.jl

[FileFormats.NL] fix copy_to if MOI.Name is set

---

src/FileFormats/NL/NLExpr.jl
src/Nonlinear/operators.jl
src/Nonlinear/univariate_expressions.jl
src/Nonlinear/univariate_expressions_generator.jl
test/FileFormats/NL/NL.jl
test/Nonlinear/Nonlinear.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2448
I don't know about this one. We might be better off documenting people to write a `signpower` function at the JuMP level because this still has the problem that `sign(x) * abs(x)^p` is not defined when `x=0` and `p < 1`.
Thoughts @ccoffrin?

[Nonlinear] add support for univariate sign

---

src/Utilities/copy.jl

In https://github.com/jump-dev/PolyJuMP.jl/pull/119, the mapping is between constraint indices of different types so it cannot be an `IndexMap` but it would be useful to call `pass_attributes`.
This PR would help fix the broken test added in https://github.com/jump-dev/PolyJuMP.jl/pull/119

[Utilities] Allow non-IndexMap for pass_attributes

---

Project.toml
docs/src/changelog.md

This could arguably be 1.28.0, but it feels too small to be a minor release, and the "new" features are really bug fixes.

Prep for v1.27.1

---

src/Bridges/bridge_optimizer.jl

Both these methods are unused and untested.
* `bridge_function` isn't referenced anywhere else, and appears to be superseded by `(un)bridged_function`?
* `bridged_constraint_function` can never be called with `MOI.VariableIndex` in the current code base.

[Bridges] remove two unused methods

---

src/Utilities/sets.jl

It was in hindsight obvious but on initial read a bit confusing that you needed to use `-func.constant`.

[Utilities] improve docstrings of shift_constant

---

src/Bridges/bridge_optimizer.jl
src/Test/test_modification.jl
test/Bridges/bridge_optimizer.jl

Fixes #2452 
<s>https://github.com/jump-dev/MathOptInterface.jl/actions/runs/8548954452</s>
<s>https://github.com/jump-dev/MathOptInterface.jl/actions/runs/8550055568</s>
<s>https://github.com/jump-dev/MathOptInterface.jl/actions/runs/8550389750</s>

Fix issue #2452

---

src/Bridges/Constraint/bridges/functionize.jl
src/Bridges/Constraint/bridges/norm_one.jl
src/Bridges/Constraint/bridges/vectorize.jl
src/Bridges/Constraint/set_map.jl
src/Utilities/functions.jl
test/Bridges/lazy_bridge_optimizer.jl

Follow-up to https://github.com/jump-dev/MathOptInterface.jl/pull/2451. It's too easy to run into obscure method errors because some bridges incorrectly accept `Complex`-valued functions.

[Bridges] restrict some bridges to acting on real-valued functions

---

src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

Revisiting #2464 for another take at #2452. 
This time it definitely fixes the original MWE:
```Julia
(clarabel) pkg> st
Status `/private/tmp/clarabel/Project.toml`
[61c947e1] Clarabel v0.7.1
[4076af6c] JuMP v1.21.0
[b8f27783] MathOptInterface v1.27.1 `~/.julia/dev/MathOptInterface`
julia> model = Model(Clarabel.Optimizer)
A JuMP Model
Variables: 0
Solver name: Clarabel
julia> set_silent(model)
julia> @variable(model, x >= 1)
x
julia> @constraint(model, c, 2x == 3)
c : 2 x = 3
julia> y = value(x)
1.4999999999999996
julia> b = normalized_rhs(c)
3.0
julia> set_normalized_rhs(c, b)
julia> value(x)
1.4999999999999996
``` …

[Bridges] error on set(_, ::ConstraintSet with variable and constraint bridges

---

docs/src/submodules/Utilities/overview.md

Closes #1940 
JuMP now has https://jump.dev/JuMP.jl/stable/api/JuMP/#lp_matrix_data which is much more useful for people.
Anyone using `MatrixOfConstraints` is likely to just copy existing solver wrappers.

[docs] expand MatrixOfConstraints example

---

src/Bridges/Constraint/bridges/functionize.jl
src/Bridges/Constraint/bridges/norm_one.jl
src/Bridges/Constraint/bridges/vectorize.jl
src/Bridges/Constraint/set_map.jl
src/Utilities/functions.jl

Addresses @blegat's concerns in https://github.com/jump-dev/MathOptInterface.jl/issues/2450
Not breaking because `is_maybe_real` hasn't been released yet.

[Utilities] refactor is_maybe_real to is_complex

---

Project.toml
docs/src/changelog.md

Prep for v1.28.0

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/integer_default_bounds.mps

[FileFormats.MPS] fix reading default bounds of INTORG variables

---

src/FileFormats/CBF/write.jl
test/FileFormats/CBF/CBF.jl

[FileFormats.CBF] write VectorOfVariables constraints in VAR block

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl

[FileFormats.LP] add support for indicator constraints

---

src/Nonlinear/parse.jl
test/Nonlinear/Nonlinear.jl

Part of https://github.com/jump-dev/JuMP.jl/issues/3729
Before
```julia
julia> GC.gc(); @time main3();
1.165808 seconds (11.14 M allocations: 795.583 MiB, 37.12% gc time)
```
after
```julia
julia> GC.gc(); @time main3();
0.455849 seconds (2.60 M allocations: 507.575 MiB, 14.25% gc time)
```

[Nonlinear] improve parsing performance of Scalar(Affine,Quadratic)Function

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/integer_default_bounds_LI.mps
test/FileFormats/MPS/integer_default_bounds_MI.mps
test/FileFormats/MPS/integer_default_bounds_PL.mps

[FileFormats.MPS] fix issue #2479

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl

Related to https://github.com/jump-dev/MathOptInterface.jl/issues/2479#issuecomment-2065448013

[FileFormats.MPS] write out LI and UI in BOUNDS instead of LO and UP

---

src/FileFormats/CBF/write.jl
test/FileFormats/CBF/CBF.jl

Found while investigating https://github.com/jump-dev/MathOptInterface.jl/issues/2493, since the code implemented in the CBF writer is nearly equivalent to what we would need to solve #2493

[FileFormats.CBF] improve heuristic for when to write variable cones

---

src/Bridges/Bridges.jl

In some cases, it's difficult to build the model with `readfromstrings!`, e.g., in SumOfSquares I need to create polynomial variables etc...

Add any function for Bridges.runtests

---

docs/src/background/naming_conventions.md
docs/src/submodules/FileFormats/overview.md

Current builds of the documentation are failing because the link checker is timing out.

[docs] fix links for the link checker

---

src/attributes.jl
test/attributes.jl

Fix return type when getting attribute of empty vector

---

src/Bridges/Bridges.jl
test/Bridges/Constraint/flip_sign.jl

Needed for https://github.com/jump-dev/SumOfSquares.jl/pull/296
Without the fix of this PR, the added tests throws
```julia
test_runtests: Error During Test at /home/blegat/.julia/dev/MathOptInterface/src/Bridges/Bridges.jl:286
Test threw exception
Expression: MOI.get(model, attr, x) ≈ primal_start
MethodError: no method matching zero(::Type{Any})
Closest candidates are:
zero(::Type{Union{Missing, T}}) where T
@ Base missing.jl:105
zero(::Type{Union{}}, Any...)
@ Base number.jl:310
zero(::Type{Missing})
@ Base missing.jl:104
...
Stacktrace:
[1] zero(::Type{Any})
@ Base ./missing.jl:106
[2] norm(itr::Vector{Any}, p::Int64)
@ LinearAlgebra ~/.julia/juliaup/julia-1.10.3+0.x64.linux.gnu/share/julia/stdlib/v1.10/LinearAlgebra/src/generic.jl:596
[3] isapprox(x::Vector{Any}, y::Vector{Float64}; …
```

Fix Bridges.runtests when model has no variable

---

src/Bridges/Constraint/bridges/indicator_sos.jl
test/Bridges/Constraint/indicator_sos.jl

Closes #2506
This now results in the expected:
```julia
julia> using JuMP, HiGHS
julia> model = Model(HiGHS.Optimizer)
A JuMP Model
Variables: 0
Solver name: HiGHS
julia> @variable(model, x)
x
julia> @variable(model, z, Bin)
z
julia> @constraint(model, z --> {x * z == 0})
ERROR: Constraints of type MathOptInterface.VectorQuadraticFunction{Float64}-in-MathOptInterface.Indicator{MathOptInterface.ACTIVATE_ON_ONE, MathOptInterface.EqualTo{Float64}} are not supported by the solver.
If you expected the solver to support your problem, you may have an error in your formulation. Otherwise, consider using a different solver.
The list of available solvers, along with the problem types they support, is available …
```

[Bridges] fix supports_constraint for IndicatorSOS1Bridge

---

src/Bridges/Constraint/bridges/slack.jl

This is needed for https://github.com/jump-dev/SumOfSquares.jl/pull/355

Use dual of equality from slack

---

docs/src/submodules/Bridges/overview.md
docs/src/submodules/FileFormats/overview.md
docs/src/submodules/Utilities/overview.md
src/Bridges/Constraint/map.jl
src/Bridges/Constraint/single_bridge_optimizer.jl
src/Bridges/Objective/map.jl
src/Bridges/Objective/single_bridge_optimizer.jl
src/Bridges/Variable/map.jl
src/Bridges/Variable/single_bridge_optimizer.jl
src/Bridges/bridge_optimizer.jl
src/Bridges/lazy_bridge_optimizer.jl
src/MathOptInterface.jl
src/Test/test_model.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/model.jl
src/Utilities/set_dot.jl
src/Utilities/universalfallback.jl
src/attributes.jl
src/sets.jl
test/Bridges/Constraint/map.jl
test/Bridges/Objective/map.jl
test/Bridges/Variable/map.jl
test/Bridges/bridge_optimizer.jl
test/Bridges/lazy_bridge_optimizer.jl
test/Utilities/cachingoptimizer.jl
test/Utilities/print.jl
test/Utilities/universalfallback.jl

Add default printing for show(io, ::ModelLike)

---

docs/src/submodules/FileFormats/overview.md
docs/src/tutorials/implementing.md
src/FileFormats/CBF/CBF.jl
src/FileFormats/LP/LP.jl
src/FileFormats/MOF/MOF.jl
src/FileFormats/MPS/MPS.jl
src/FileFormats/NL/NL.jl
src/FileFormats/SDPA/SDPA.jl
src/MathOptInterface.jl
test/FileFormats/CBF/CBF.jl
test/FileFormats/LP/LP.jl
test/FileFormats/MOF/MOF.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/NL/NL.jl
test/FileFormats/SDPA/SDPA.jl

[FileFormats] remove show method in favor of summary

---

src/FileFormats/NL/read.jl
test/FileFormats/NL/read.jl

[FileFormats.NL] read ScalarAffineFunction where possible

---

src/Bridges/Constraint/bridges/slack.jl

This reverts commit 6d9378acf11653a1cb2ac6c969f388fa4be59f1e.
x-ref #2513

Revert "[Bridges] use dual of equality in slack bridge (#2508)"

---

src/Bridges/Constraint/bridges/slack.jl
test/Bridges/Constraint/slack.jl

We can take inspiration from https://github.com/jump-dev/MathOptInterface.jl/blob/08d34003cd3d7500379d9440e92445bc4d9a8fa8/src/Bridges/Constraint/bridges/set_dot_scaling.jl#L64-L75
Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2513

[Bridges] use dual of equality in slack bridge (take 2)

---

docs/src/submodules/Bridges/reference.md
src/Bridges/Constraint/set_map.jl
src/Bridges/set_map.jl
test/Bridges/set_map.jl

When I decided that these functions would only depend on the type, it was for consistency for `map_function` because `map_function` clearly cannot depend on anything else given that it is used in `bridge_constraint`. However, you could also have a bridge that implements its own `bridge_constraint`, storing extra information then in the bridge to be able to implement `inverse_map_function`, etc... This is the case of the Sum-of-Squares bridge.
Needed for https://github.com/jump-dev/SumOfSquares.jl/pull/355

Allow SetMapBridge to use bridge value

---

src/Utilities/copy.jl

These were removed in https://github.com/jump-dev/MathOptInterface.jl/pull/2495, but I didn't check that it didn't break downstream. Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2519

Revert removal of _try_constrain_variables_on_creation

---

src/Bridges/Bridges.jl
test/Bridges/Variable/zeros.jl

Some variable bridges don't support `unbridged_variable` and that makes `runtests` fail when getting `ConstraintFunction` or when getting `ConstraintSet` for scalar constraints. For example, `ZerosBridge` does not support it so it cannot use `runtests`.
Another example is the SOS cone: https://github.com/jump-dev/SumOfSquares.jl/pull/353 I could support it in the nonweighted version but if it's weighted by arbitrary polynomials, it seems difficult to unbridge. It might be possible but it's not high priority. By using only vector cones in the tests, it turns out that only this small change is enough to pass the tests. This is still testing the inner model completely.

Add Variable bridges to use runtests without unbridged_variable

---

src/Bridges/Variable/bridges/hermitian.jl

This was written before we had `inverse_trimap` I think

Use inverse_trimap instead of redefining it

---

src/Nonlinear/ReverseAD/reverse_mode.jl
test/Nonlinear/ReverseAD.jl

[Nonlinear.ReverseAD] fix NLPBlock and bridges

---

src/constraints.jl
test/errors.jl

Improve UnsupportedConstraint error

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl

[FileFormats.MPS] fix MAX_SENSE with quadratic objective

---

docs/src/manual/solutions.md

It's making ci fail at the moment
```
[ Info: CheckDocument: running document checks.
┌ Error: linkcheck 'https://www.ibm.com/docs/en/SSSA5P_12.6.1/ilog.odms.cplex.help/refcallablelibrary/macros/CPXMIP_OPTIMAL_INFEAS.html' status: 404.
└ @ Documenter ~/.julia/packages/Documenter/C1XEF/src/utilities/utilities.jl:44
[ Info: Populate: populating indices.
ERROR: LoadError: `makedocs` encountered an error [:linkcheck] -- terminating build before rendering.
```

Fix link to CPLEX's CPXMIP_OPTIMAL_INFEAS

---

src/Nonlinear/ReverseAD/mathoptinterface_api.jl
src/Nonlinear/operators.jl
test/Nonlinear/ReverseAD.jl

[Nonlinear] allow univariate operators with only gradient information

---

docs/src/manual/models.md
docs/src/reference/models.md
docs/src/tutorials/implementing.md
src/Test/test_attribute.jl
src/attributes.jl

This adds a node limit attribute, which seems to make sense given that there is the corresponding termination status. Most MIP solvers have a limit on the number of nodes in the BNB tree. Note that this is in general different from the number of solved LPs, since each node contains its own solve-and-cut loop (at least for SCIP)

Add new attribute NodeLimit

---

src/Test/test_basic_constraint.jl

EAGO was failing this test because it was recoving the dimension of the set from the dimension of the function instead of writing the dimension of the set in the model.
Part of https://github.com/jump-dev/MathOptInterface.jl/issues/2553

Fix dimension of nonlinear function in basic tests

---

.github/workflows/format_check.yml
docs/make.jl
perf/bellman_ford.jl
perf/cachingoptimizer.jl
perf/time_to_first_solve/script.jl

Runs Juliaformatter on the whole repo, and adapts the GH action

format all

---

src/sets.jl

There were three backticks in a row instead of one to close an inline code block.

Fix a typo in the description of `CountDistinct`

---

src/Nonlinear/ReverseAD/Coloring/Coloring.jl

Use eachindex in Coloring

---

src/Nonlinear/ReverseAD/Coloring/Coloring.jl

Just taking notes of my understanding

Add docstring to internal structs in Coloring

---

src/Nonlinear/ReverseAD/Coloring/Coloring.jl

`i` is already used inside the loop so it's best to use `k` for the iteration just like in the previous `for` loop.

[Coloring] avoid index conflict in variable name

---

Project.toml
docs/src/changelog.md

Prep for v1.32.0

---

src/Test/test_nonlinear.jl

Even though `NaN` is a `Float64` literal, `:(NaN)` doesn't do what it looks like.
```julia
julia> dump(:(NaN))
Symbol NaN
julia> dump(:(1.0))
Float64 1.0
julia> dump(:($NaN))
Float64 NaN
```
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/11544744456

[Test] Fix MOI.objective_expr(::InvalidEvaluator)

---

Project.toml
docs/src/changelog.md

I'm going to make a release containing only #2567 because I need it for Uno.

Prep for v1.33.0

---

src/Utilities/model.jl
test/Utilities/model.jl

Closes #2750
Cloess #2751
This PR is an alternative to #2751

[Utilities] fix adding unsupported constraints to AbstractModel

---

src/sets.jl
test/sets.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2576

Promote bound of Interval if they have different types

---

src/Utilities/universalfallback.jl
test/Utilities/universalfallback.jl

x-ref https://github.com/jump-dev/Gurobi.jl/pull/584
We don't have a way to remove attributes once they've been set. We've mostly settled on `nothing` as the resetting to default.
For example
https://github.com/jump-dev/MathOptInterface.jl/blob/278fba5831af37d89bb0faed656e182f260343ff/src/attributes.jl#L329-L331
https://github.com/jump-dev/MathOptInterface.jl/blob/278fba5831af37d89bb0faed656e182f260343ff/src/attributes.jl#L848-L850
https://github.com/jump-dev/MathOptInterface.jl/blob/278fba5831af37d89bb0faed656e182f260343ff/src/attributes.jl#L861-L863

[Utilities] ignore attributes in UniversalFallback if set to nothing

---

src/Test/test_model.jl
src/variables.jl

Alternative fix for https://github.com/jump-dev/MathOptInterface.jl/issues/2564
Actually, this also has the potential to solve another issue.
If you have a variable that belongs to 2 sets, you never know which one should be added at creation as it's solver specific.
When you have a caching optimizer and then a bridge layer it's fine because it will get reordered in `copy_to` but otherwise you have to manually check the bridging cost.
The implementation of this PR could be improved to handle this case as well by doing something like:
```julia
function _cost_of_bridging( # copy pasted from `Utilities/copy.jl`
dest::MOI.ModelLike,
::Type{S},
) where {S<:MOI.AbstractScalarSet}
x = MOI.get(dest, MOI.VariableBridgingCost{S}())
y = MOI.get(dest, MOI.ConstraintBridgingCost{MOI.VariableIndex,S}()) …
```

add_constrained_variable with 2 sets

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/inequality_to_complements.jl
test/Bridges/Constraint/inequality_to_complements.jl

Closes #2581
bridge
the model:

Add Bridges.Constraint.InequalityToComplementsBridge

---

src/Bridges/Constraint/bridges/det.jl
src/Bridges/Constraint/bridges/norm_spec_nuc_to_psd.jl
src/Bridges/Objective/bridges/slack.jl
src/Bridges/Objective/bridges/vector_slack.jl
test/Bridges/Objective/slack.jl
test/Bridges/Objective/vector_slack.jl

x-ref https://github.com/jump-dev/Gurobi.jl/pull/593

[Bridges] fix querying result attributes with result_index != 1

---

src/Test/test_nonlinear.jl

[Test] fix nonlinear tests by adding starting point

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/ExponentialConeToScalarNonlinearFunctionBridge.jl
src/Utilities/parser.jl
test/Bridges/Constraint/ExponentialConeToScalarNonlinearFunctionBridge.jl

This would enable:
```julia
julia> using JuMP, Ipopt
julia> begin
model = Model(Ipopt.Optimizer)
set_silent(model)
@variable(model, x == 1.5)
@variable(model, z)
@objective(model, Min, z)
@constraint(model, [x, 1, z] in MOI.ExponentialCone())
optimize!(model)
@assert is_solved_and_feasible(model)
value(z), exp(1.5)
end
(4.4816890628439685, 4.4816890703380645)
```
Now, it's an open question whether we _should_ do this, but it comes up from time to time.
Latest is https://discourse.julialang.org/t/lazybridgeoptimizer-not-working-with-copy-to/123366
cc @thibault-vignon

[Bridges] add ExponentialConeToScalarNonlinearFunctionBridge

---

src/Bridges/Bridges.jl

Looks like it was just an oversight

Use variable_start in Bridges.runtests

---

src/Test/test_conic.jl

Test taken from https://github.com/jump-dev/MosekTools.jl/pull/140

Add test with multiple PSD variables on same constraint

---

src/Bridges/Variable/Variable.jl
src/Bridges/Variable/bridges/RSOCtoPSDBridge.jl
test/Bridges/lazy_bridge_optimizer.jl

Extracted from #2596 
The behaviour should, where possible, not depend on this somewhat arbitrary order of bridges in this function. That is too brittle and the behaviour is undocumented.

[Bridges.Variable] add bridges in alphabetical order and change weight

---

src/Test/test_basic_constraint.jl

This is, somewhat fairly, causing a test failure in SCIP

[Test] make first variable ZeroOne in test_basic_VectorAffineFunction_Indicator

---

Project.toml
docs/src/changelog.md

https://github.com/jump-dev/MathOptInterface.jl/actions/runs/12622888300

Prep for v1.35.0

---

src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl

All OrderedDicts used are very small. Hence, they allocate unnecessarily. This also creates more GC pressure.

[FileFormats.MOF] replace OrderedDict by NamedTuple when writing

---

src/FileFormats/MOF/MOF.jl
src/FileFormats/MOF/read.jl
src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl

Follow-up to https://github.com/jump-dev/MathOptInterface.jl/pull/2606 to see if we can remove all instances of OrderedDict

[FileFormats.MOF] remove all usage of OrderedDict

---

src/functions.jl
test/functions.jl

Fix Base.copy for ScalarNonlinearFunction

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Objective/Objective.jl
src/Bridges/Variable/Variable.jl

This broke SDDP.jl (and I've seen it somewhere else too): https://github.com/odow/SDDP.jl/actions/runs/13017930580/job/36311572225?pr=827#step:6:412
The issue is that `julia-actions/cache` runs after we have generated the `.cov` files, so if the cache is loaded in a new run, then precompile will attempt to load the `.cov` files. We jus need to skip them.

[Bridges] fix including files which are not .jl files

---

src/Utilities/model.jl

For some reason only indicator less than was added to MOI.Utilities.Model, which prevents copying models with that constraint

Add all linear indicator constraints in the Utilities.Model

---

test/Utilities/model.jl

Follow-up to https://github.com/jump-dev/MathOptInterface.jl/pull/2618

[Utilities] add test for indicator constraints in Model

---

src/Nonlinear/ReverseAD/forward_over_reverse.jl
src/Nonlinear/ReverseAD/reverse_mode.jl
src/Nonlinear/model.jl
src/Nonlinear/operators.jl
test/Nonlinear/Nonlinear.jl

With the energy modeling benchmarking that @joaquimg has been doing, we've been talking about how small things never show up in a flame graph until you look at their aggregate across multiple call sites. 
One thing that shows up is `getindex`
With the only giveaway being the `ht_keyindex(::Dict{Symbol,Int}, ::Symbol)` method.
It's because we're calling `operators.univariate_operators[node.index]` in multiple places, which is a `Dict` lookup.
These calls don't show much because of inlining etc. Even in the code view, you're kinda like "call is expensive. Sure"
```Julia
julia> @benchmark(
MOI.Nonlinear.ReverseAD._reverse_mode($(evaluator.backend), x),
setup=(x=rand(num_variables(model))),
)
BenchmarkTools.Trial: 44 samples with 1 evaluation per sample.
Range (min … max):  112.457 ms … …
```

[Nonlinear] fix performance of evaluating univariate operators

---

src/Nonlinear/ReverseAD/Coloring/Coloring.jl

Fix typos in docstrings added in https://github.com/jump-dev/MathOptInterface.jl/pull/2560
I also say the `collect` method was defined but never used while we could use it at the `sort!` input

[Coloring] Fix docstrings

---

docs/src/submodules/Nonlinear/overview.md

I think we're at the point where this is now pretty solid.

[docs] remove experimental warning from Nonlinear

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl

Closes #2627
I still need better testing for this.
The underlying issue is that Gurobi's QCMATRIX section does not match CPLEX and Mosek (It is missing a /2): https://docs.gurobi.com/projects/optimizer/en/current/reference/fileformats/modelformats.html#qcmatrix-section

[FileFormats.MPS] fix scale factor in Gurobi's QCMATRIX

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Add row-wise constructors for VectorAffine and VectorQuadratic functions

---

src/Utilities/results.jl
test/Utilities/model.jl

Improves code coverage, and reduces the chance for bugs because these now all re-use the same method.

[Utilities] unify how we compute variable dual fallback

---

src/Test/test_basic_constraint.jl

I don't know if this was intentional or a bug.
I'll need to run solver-tests to see if this is disruptive: https://github.com/jump-dev/MathOptInterface.jl/actions/runs/13445063692

[Test] add basic Integer tests

---

src/Test/test_solve.jl

An error in the getter should be NotAllowed, which will skip the test. I think I got confused when I first wrote this because as previously written the error gets wrapped in a `Base.Test.FallbackTestSetException` error, which doesn't trigger the skip logic.

[Test] simplify check for supported conflict status

---

src/FileFormats/LP/LP.jl
src/FileFormats/MPS/MPS.jl
test/FileFormats/CBF/CBF.jl
test/FileFormats/LP/LP.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/NL/NL.jl
test/FileFormats/SDPA/SDPA.jl

[FileFormats] fix writing unsupported variable types

---

test/attributes.jl

We could probably have done without this method, but it's there now.

Add a test for MOI.get!

---

src/Bridges/Bridges.jl
test/Bridges/Constraint/AllDifferentToCountDistinctBridge.jl

We might need to check solver-tests.yml for this one. I don't think it's possible in MOI to return a tuple here if there are 0 constraints.

[Test] improve test coverage

---

src/Bridges/Variable/bridges/ParameterToEqualToBridge.jl
src/Bridges/Variable/map.jl
src/Bridges/Variable/set_map.jl
test/Bridges/Variable/ParameterToEqualToBridge.jl
test/Bridges/Variable/RSOCtoSOCBridge.jl
test/Bridges/Variable/SOCtoRSOCBridge.jl
test/Bridges/bridge_optimizer.jl
test/Bridges/set_map.jl

@blegat it doesn't look like a `SetMapBridge{T,<:MOI.AbstractScalarSet}` bridge was ever implemented or tested?

[Bridges.Variable] change ParameterToEqualToBridge to <: SetMapBridge

---

src/Bridges/Constraint/bridges/IndicatorToMILPBridge.jl
src/Bridges/Constraint/bridges/SOS1ToMILPBridge.jl
src/Bridges/Constraint/bridges/SOS2ToMILPBridge.jl
test/Bridges/Constraint/IndicatorToMILPBridge.jl
test/Bridges/Constraint/SOS1ToMILPBridge.jl
test/Bridges/Constraint/SOS2ToMILPBridge.jl

I broke these bridges in https://github.com/jump-dev/MathOptInterface.jl/pull/2661 because they weren't tested, and I couldn't figure out a way to hit them because I assumed one had to call `final_touch` before we were allowed to delete something, but I guess that is not the case.
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/13639825780

[Bridges] fix deleting bridges before final touch

---

src/Bridges/Bridges.jl

Closes #2677
There are actually multiple existing implementations in the wild that I broke with the "bug fix" https://github.com/jump-dev/MathOptInterface.jl/pull/2665
In addition to SCS and ECOS, there are:
https://github.com/jump-dev/SeDuMi.jl/blob/b69a1a664060216fabf0f101a8c21a3cf2df49f7/src/MOI_wrapper.jl#L69-L71
https://github.com/jump-dev/PolyJuMP.jl/blob/b28143bb2f68ff31b3c34d129ff2f403eb1752b4/src/model.jl#L109-L116
Perhaps we should just relax the type check.

[Bridges] make attribute_value_type(::ListOfNonstandardBridges) less strict

---

docs/make.jl
docs/src/submodules/Nonlinear/SymbolicAD.md
docs/src/submodules/Nonlinear/reference.md
docs/styles/config/vocabularies/JuMP/accept.txt
src/Nonlinear/Nonlinear.jl
src/Nonlinear/SymbolicAD/SymbolicAD.jl
src/Nonlinear/types.jl
test/Nonlinear/SymbolicAD.jl
test/Nonlinear/runtests.jl

Twas prototyped in https://github.com/lanl-ansi/MathOptSymbolicAD.jl/pull/39
I'm open to arguments against adding this. The evaluator could arguably remain in the separate MathOptSymbolicAD.jl package. But the simplification and symbolic derivative stuff is more widely useful. I occasionally get questions on the forum asking how to compute the derivative of a JuMP expression.
This doesn't close any issues directly, but it relates to a number of open and previously closed issues:
* Replaces https://github.com/jump-dev/MathOptInterface.jl/pull/2605
* Contains the features needed for https://github.com/jump-dev/MathOptInterface.jl/issues/2553
* Fixes https://github.com/jump-dev/MathOptInterface.jl/issues/2533 (which was previously closed because I moved work to MathOptSymbolicAD.jl)
* …

[Nonlinear] add SymbolicAD submodule

---

test/Bridges/Constraint/NormOneBridge.jl

The tests of separate bridge were mixed together

[Bridges] refactor NormOneBridge.jl from NormInfinityBridge.jl

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/bridges/SplitHyperRectangleBridge.jl
test/Bridges/Constraint/SplitHyperRectangleBridge.jl

This avoids adding and subtracting 0 to avoid terms like +(-(+(x), 0), 0)
Before
```julia
julia> include("/Users/oscar/.julia/dev/MathOptInterface/test/Bridges/Constraint/SplitHyperRectangleBridge.jl")
WARNING: replacing module TestConstraintHyperRectangle.
test_basic_HyperRectangle: Test Failed at /Users/oscar/.julia/dev/MathOptInterface/src/Test/test_basic_constraint.jl:268
Expression: isapprox(MOI.Utilities.canonical(f), constraint_function, config)
Evaluated: isapprox(┌                                                                                                           ┐
│+(-(+(^(MOI.VariableIndex(1), (2)), ^(MOI.VariableIndex(2), (2)), ^(MOI.VariableIndex(3), (2))), 0.0), 0.0)│
│+(-(+(MOI.VariableIndex(2)), 0.0), 0.0) …
```

[Bridges] improve function getter of SplitHyperRectangleBridge

---

src/Utilities/operate.jl
test/Utilities/test_operate!.jl

https://github.com/jump-dev/MathOptInterface.jl/issues/2553 got complicated to debug because of this :smile:
Without this PR, this code:
https://github.com/jump-dev/MathOptInterface.jl/blob/927c58bb2e157813c3d71de754c8bd07374963b6/src/Bridges/Constraint/bridges/NormInfinityBridge.jl#L61-L68
modifies the user's input function.

[Utilities] fix operate(vcat for VectorNonlinearFunction

---

src/Test/test_basic_constraint.jl
test/Bridges/Constraint/NormInfinityBridge.jl
test/Bridges/Constraint/NormOneBridge.jl

Closes #2553 
I've checked that these now pass with EAGO
https://github.com/PSORLab/EAGO.jl/blob/9f94746c1262bfc650adf867259dbb91a20a1b84/test/moit_tests.jl#L84-L89

[Test] use SymbolicAD.simplify when comparing ConstraintFunction

---

src/FileFormats/MOF/MOF.jl
src/FileFormats/MOF/read.jl
src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2687
The underlying issue is that we supported nonlinear file formats before the introduction of ScalarNonlinearFunction. Thus, `.mof.json` and `.nl` that contain nonlinear get parsed into a `MOI.NLPBlock`. This is the "old" nonlinear interface, and it means that Ipopt etc run into problems if the user wants to read in a file and then do some "new" stuff with it.
The current work-around is to use `read_from_file(model; use_nlp_block = false)`. 
But we could add a tag to the file on write if we detect `MOI.ScalarNonlinearFunction`. This would all "new" stuff to round-trip as new, and "old" stuff to round-trip as old.
The alternative would be to change the default to `use_nlp_block = false`, but this is technically breaking. …

[FileFormats.MOF] make use_nlp_block=false the default if SNF in model

---

src/Test/test_attribute.jl
src/Test/test_conic.jl
src/Test/test_cpsat.jl
src/Test/test_linear.jl
src/Test/test_model.jl
src/Test/test_modification.jl
src/Test/test_multiobjective.jl
src/Test/test_nonlinear.jl
src/Test/test_objective.jl
src/Test/test_solve.jl
src/Test/test_variable.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2689

[Test] update version_added

---

Project.toml
docs/src/changelog.md

Prep for v1.38.0

---

src/Bridges/Constraint/bridges/CircuitToMILPBridge.jl

Phew! This one was confusing to track down. It is the cause of:
https://github.com/jump-dev/MosekTools.jl/blob/bb99faeb4fe2e8632003d299b33503ae1253beac/test/runtests.jl#L383-L387

Remove redundant constraint in CircuitToMILPBridge.jl

---

src/Bridges/Variable/map.jl
src/Bridges/bridge_optimizer.jl
src/Test/test_basic_constraint.jl
src/Test/test_conic.jl
test/Bridges/Variable/NonposToNonnegBridge.jl

There were a number of trivial bugs in MosekTools.jl because we didn't have these tests.
Closes #2693
This needs solver-tests.yml. I think it might break Ipopt: https://github.com/jump-dev/MathOptInterface.jl/actions/runs/14044969174

[Bridges] fix ordering of variables returned by LazyBridgeOptimizer

---

docs/src/reference/models.md
docs/src/reference/standard_form.md
docs/src/submodules/FileFormats/reference.md
docs/src/submodules/Utilities/reference.md
src/FileFormats/FileFormats.jl
src/Utilities/cachingoptimizer.jl
src/attributes.jl
src/sets.jl

Related to #2698, except that this adds docs for some enums that were not given doc strings for the values.

[docs] better document various enums

---

src/MathOptInterface.jl
src/attributes.jl

In relation to https://discourse.julialang.org/t/approaching-a-linear-program-correctly/127354/12?u=odow
I'll post a preview link once it's up: https://jump.dev/MathOptInterface.jl/previews/PR2698/reference/models/#MathOptInterface.TerminationStatusCode

[docs] improve the docstrings of the various enum values

---

src/attributes.jl

x-ref https://discourse.julialang.org/t/approaching-a-linear-program-correctly/127354/15?u=odow

[docs] improve the docstring for DUAL_INFEASIBLE

---

src/attributes.jl

I think our attribute docstrings can be improved. Here are two current bad examples:
it's quite a lot of work, so I'll chip away slowly.
I'll post a preview link once it's ready: https://jump.dev/MathOptInterface.jl/previews/PR2700/reference/models/#Optimizer-attributes

[docs] improve the docstrings of attributes

---

src/Test/test_nonlinear.jl

MAiNGO has trouble with this, and so did EAGO. It seems reasonable to add a lower bound for `log(x)`:

[Test] make variable bounded in test_nonlinear_constraint_log

---

.github/workflows/solver-tests.yml

<s>https://github.com/jump-dev/MathOptInterface.jl/actions/runs/14072138871</s>
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/14210469166

Update solver-tests.yml with new solvers

---

src/Test/test_basic_constraint.jl
test/Bridges/lazy_bridge_optimizer.jl

@blegat I don't understand https://github.com/jump-dev/MathOptInterface.jl/issues/2696.
As far as I can tell, the only issue is that we may return a false positive (`is_valid -> true`) if there is a `VectorOfVariables` constraint on a vector of variables that were bridged, and the bridge happened to add a constraint with the same index.

[Bridges] add a test_broken test for #2696

---

src/Nonlinear/ReverseAD/utils.jl
test/Nonlinear/ReverseAD.jl

ForwardDiff@1 changed to use `CartesianIndex`, which we hadn't supported.
We also never tested this, because we tested only that the operator could be called, but never end-to-end through the ReverseAD system. Nasty.
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/14232574450

[Nonlinear] fix _UnsafeVectorView with ForwardDiff@1.0.0

---

src/sets.jl

Fix constructors of Indicator set and tidy docstring

---

Project.toml
docs/src/changelog.md

Prep for v1.38.1

---

src/Bridges/Variable/map.jl
src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

[Bridges] fix get ListOfVariableIndices when there is a chain of bridges

---

src/Test/Test.jl

Would be useful for https://github.com/blegat/LowRankOpt.jl/pull/6 for instance

Allow using Test.runtests in other packages

---

src/FileFormats/NL/read.jl
test/FileFormats/NL/read.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2717
<s>I still need to add much better tests for this</s>

[FileFormats.NL] add support for reading binary format

---

docs/src/reference/errors.md
src/Bridges/Bridges.jl
test/Bridges/set_map.jl

This is needed for https://github.com/blegat/LowRankOpt.jl/pull/10. The getters for ConstraintFunction and ConstrainPrimalStart are not so important as there is often a cache so bridges corresponding to non-invertible transformations are fine and being able to use these tests for these bridges would be useful.

Fix Bridge test for non-invertible constraint bridge

---

docs/src/submodules/Bridges/implementation.md
src/Bridges/Bridges.jl
src/Test/Test.jl

Add testset to Bridges.runtests

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/HermitianToComplexSymmetricBridge.jl
src/Bridges/Constraint/bridges/HermitianToSymmetricPSDBridge.jl
src/Bridges/Constraint/bridges/SetDotScalingBridge.jl
test/Bridges/Constraint/HermitianToComplexSymmetricBridge.jl

See https://github.com/jump-dev/SeDuMi.jl/pull/28#issuecomment-2804975387
the bridge
named after the type of the bridge
bridge
the model:

Add bridge from Hermitian PSD to complex function in Symmetric PSD

---

src/Nonlinear/ReverseAD/ReverseAD.jl
src/Nonlinear/ReverseAD/forward_over_reverse.jl

A large of code was almost copy-pasted so I think a sub-function is a win for readability.
Doing the `_reinterpret` magic inside `_hessian_slice_inner` along with the other `_reinterpret` calls also allows to simplify logic quite a bit by keeping these contained inside this function only.

Simplify _eval_hessian_inner

---

src/Nonlinear/ReverseAD/forward_over_reverse.jl
src/Nonlinear/ReverseAD/mathoptinterface_api.jl
src/Nonlinear/ReverseAD/types.jl

They seem to only be used internally by `_forward_eval_ϵ` and `reverse_eval_ϵ` so the same vector is sufficient for both forward and reverse as well as for all subexpressions and expressions

[Nonlinear] Merge forward_storage_ϵ with reverse_storage_ϵ

---

src/Nonlinear/ReverseAD/mathoptinterface_api.jl
src/Nonlinear/ReverseAD/types.jl
test/Nonlinear/ReverseAD.jl

This was done for `_FunctionStorage` but not here

Disable linearity detection for subexpression if no hessian

---

test/Nonlinear/ReverseAD.jl

Testing that allocations are below a given threshold can be a bit flaky but when something does not allocate at all, I like tests that verify that this remains the same.

Add allocation tests for ReverseAD

---

src/Nonlinear/ReverseAD/forward_over_reverse.jl
src/Nonlinear/ReverseAD/mathoptinterface_api.jl

They are always the same anyway. I wonder if there is any performance benefit of saving these interpret calls. Is there a standard benchmark used for checking for regressions ?
Maybe https://github.com/lanl-ansi/rosetta-opf/blob/main/jump.jl ?

Remove arguments of _forward_eval_ϵ

---

src/Nonlinear/ReverseAD/forward_over_reverse.jl
src/Nonlinear/ReverseAD/mathoptinterface_api.jl
test/Nonlinear/ReverseAD.jl

As `chunk` is maximum 10, we can reuse the `_create_binary_switch` we use for type-stable evaluation of our list of operators to call `_eval_hessian_inner` in a type-stable way.
On this benchmark https://github.com/jump-dev/MathOptInterface.jl/pull/2739#issuecomment-2833683884
Before this PR
```
5.959426 seconds (158.26 k allocations: 11.273 MiB)
5.973144 seconds (158.26 k allocations: 11.273 MiB)
6.078342 seconds (158.26 k allocations: 11.273 MiB)
6.031799 seconds (158.26 k allocations: 11.273 MiB, 0.23% gc time)
6.022742 seconds (158.26 k allocations: 11.273 MiB)
6.013003 seconds (158.26 k allocations: 11.273 MiB)
6.021324 seconds (158.26 k allocations: 11.273 MiB)
```
After this PR:
```
5.925775 seconds
5.820862 seconds
5.865539 seconds
5.823728 seconds
5.848671 seconds
5.864283 …
```

Remove dynamic dispatch in Hessian evaluation

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/bridges/AbstractFunctionConversionBridge.jl
src/Bridges/Constraint/bridges/InequalityToComplementsBridge.jl
src/Bridges/Constraint/bridges/NormOneBridge.jl
src/Bridges/Constraint/bridges/SetDotScalingBridge.jl
src/Bridges/Constraint/bridges/VectorizeBridge.jl
src/Bridges/Constraint/set_map.jl
test/Bridges/Constraint/SetDotScalingBridge.jl
test/Bridges/lazy_bridge_optimizer.jl

The bridges don't support dealing with a function that is not of coefficient type `T`. So with `ComplexF64`, we had these errors but actually we get the same with `Int` for instance. So we might as well check it with `MOI.is_coefficient_type`
Before the PR
```julia
julia> model = MOI.instantiate(MOI.Utilities.Model{Float64}, with_bridge_type=Float64)
julia> MOI.supports_constraint(model, MOI.VectorAffineFunction{Int}, MOI.Nonnegatives)
ERROR: MethodError: no method matching promote_operation(::typeof(-), ::Type{Float64}, ::Type{MathOptInterface.VectorAffineFunction{Int64}})
The function `promote_operation` exists, but no method is defined for this combination of argument types.
Closest candidates are:
promote_operation(::typeof(-), ::Type{T}, …
```

Fix SetMapBridge with complex type

---

src/Nonlinear/ReverseAD/forward_over_reverse.jl
test/Nonlinear/ReverseAD.jl

Introduced by https://github.com/jump-dev/MathOptInterface.jl/pull/2736, specifically:
https://github.com/jump-dev/MathOptInterface.jl/pull/2736/files#diff-fd2e1ad4a6c5ea5294c6e338afffbb76c837b6c4a868d949007a0229ad846ec0R187
I found the test case by taking the failed Juniper run, and reducing.

[Nonlinear.ReverseAD] Fix use of reinterpret instead _reinterpret_unsafe

---

docs/make.jl
src/Benchmarks/Benchmarks.jl
src/Bridges/Bridges.jl
src/Bridges/Constraint/bridge.jl
src/Bridges/Constraint/single_bridge_optimizer.jl
src/Bridges/Objective/single_bridge_optimizer.jl
src/Bridges/Variable/bridge.jl
src/Bridges/Variable/single_bridge_optimizer.jl
src/Bridges/bridge.jl
src/Bridges/lazy_bridge_optimizer.jl
src/Nonlinear/ReverseAD/utils.jl
src/Nonlinear/SymbolicAD/SymbolicAD.jl
src/Nonlinear/evaluator.jl
src/Nonlinear/model.jl
src/Nonlinear/operators.jl
src/Test/Test.jl
src/Utilities/functions.jl
src/Utilities/model.jl
src/Utilities/parser.jl
src/Utilities/penalty_relaxation.jl
src/Utilities/product_of_sets.jl
src/Utilities/set_dot.jl
src/Utilities/sets.jl
src/attributes.jl
src/constraints.jl
src/functions.jl
src/modifications.jl
src/nlp.jl
src/sets.jl
src/variables.jl

x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2745#discussion_r2069896084

Add import MathOptInterface as MOI to DocTestSetup

---

Project.toml
docs/src/changelog.md

Prep for v1.40.0

---

docs/src/submodules/Bridges/implementation.md
src/Bridges/Bridges.jl

I didn't explicitly verify this, but I think this should hopefully avoid the doctest failure we sometimes see  (https://github.com/JuliaDocs/Documenter.jl/issues/2704).

[docs] filter varying width Time column in doctest

---

src/Bridges/Constraint/bridges/VectorizeBridge.jl
src/Bridges/Variable/bridges/VectorizeBridge.jl
src/FileFormats/MPS/MPS.jl

It requires Julia v1.4 but which is fine since we use Julia v1.6. I find it nicer and more readable than old way.

Use Base.only when appropriate

---

docs/src/submodules/Nonlinear/reference.md
src/Nonlinear/Nonlinear.jl

Follow up from https://github.com/jump-dev/MathOptInterface.jl/pull/2625 for consistency
We actually still have the warning in the docs:
https://jump.dev/MathOptInterface.jl/v1.40/submodules/Nonlinear/reference/#MathOptInterface.Nonlinear

[docs] remove experimental warning from Nonlinear module docstring

---

src/Bridges/Constraint/bridges/VectorizeBridge.jl
src/Utilities/mockoptimizer.jl

I think these lines were written before that helper existed

Use throw_if_scalar_and_constant_not_zero when appropriate

---

src/Utilities/results.jl
test/Utilities/results.jl

Found that bug when working on https://github.com/jump-dev/MathOptInterface.jl/pull/2754

Fix get_fallback of DualObjectiveValue with HyperRectangle

---

Project.toml
docs/make.jl
docs/src/changelog.md

Prep for v1.40.1

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/bridges/BinPackingToMILPBridge.jl
src/Bridges/Constraint/bridges/CountBelongsToMILPBridge.jl
src/Bridges/Constraint/bridges/CountDistinctToMILPBridge.jl
src/Bridges/Constraint/bridges/CountGreaterThanToMILPBridge.jl
src/Bridges/Constraint/bridges/IndicatorToMILPBridge.jl
src/Bridges/Constraint/bridges/ReifiedCountDistinctToMILPBridge.jl
src/Bridges/Constraint/bridges/SOS1ToMILPBridge.jl
src/Bridges/Constraint/bridges/SOS2ToMILPBridge.jl
test/Bridges/Constraint/BinPackingToMILPBridge.jl
test/Bridges/Constraint/CountBelongsToMILPBridge.jl
test/Bridges/Constraint/CountDistinctToMILPBridge.jl
test/Bridges/Constraint/CountGreaterThanToMILPBridge.jl
test/Bridges/Constraint/IndicatorToMILPBridge.jl
test/Bridges/Constraint/ReifiedCountDistinctToMILPBridge.jl
test/Bridges/Constraint/SOS1ToMILPBridge.jl
test/Bridges/Constraint/SOS2ToMILPBridge.jl
test/Bridges/bridge_optimizer.jl

[Bridges] improve error thrown in ToMILPBridge when variable is not bounded

---

src/FileFormats/NL/read.jl
test/FileFormats/NL/read.jl

x-ref https://discourse.julialang.org/t/convert-a-nonlinear-model-defined-by-jumps-legacy-version-to-latest-version/129542

[FileFormats.NL] fix try_scalar_affine_function

---

Project.toml
docs/src/changelog.md

Prep for v1.41.0

---

src/Utilities/penalty_relaxation.jl
test/Utilities/penalty_relaxation.jl

This is a massive pain in:
- https://github.com/jump-dev/ModelAnalyzer.jl
- https://github.com/jump-dev/MathOptConflictSolver.jl
As we keep skipping bounds and such.
The behaviour is opt-out, so users remain with the warning.

Optionally disable warn on `PenaltyRelaxation`

---

test/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/duplicate_coefficient.mps

Closes #2786
It's not obvious what the right thing to do here is.
Gurobi ignores the repeated coefficients:
```
(base) oscar@Oscars-MacBook-Pro MathOptInterface % gurobi_cl test/FileFormats/MPS/duplicate_coefficient.mps
Set parameter LicenseID to value 890341
Set parameter LogFile to value "gurobi.log"
Using license file /Users/oscar/gurobi.lic
Gurobi Optimizer version 11.0.1 build v11.0.1rc0 (mac64[x86] - Darwin 24.1.0 24B83)
Copyright (c) 2024, Gurobi Optimization, LLC
Warning: duplicate nonzeros for column x and row c.
Read MPS format model from file test/FileFormats/MPS/duplicate_coefficient.mps
Reading time = 0.00 seconds
DUPLICATE_COEFFICIENT: 1 rows, 1 columns, 1 nonzeros
CPU model: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
Thread count: 4 physical cores, 8 logical processors, using …
```

[FileFormats.MPS] test that duplicate entries are summed

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/failing_models/rows_malformed.mps

[FileFormats.MPS] fix reading models with extra ROWS fields

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/2797

[FileFormats.MPS] allow any whitespace as a separator between fields

---

src/Utilities/mockoptimizer.jl

JuMP was failing solver-tests: https://github.com/jump-dev/MathOptInterface.jl/pull/2799
We could have fixed this in the JuMP tests, but I'd rather do it here.
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/16738147486

[Utilities] fix backwards compat of ConflictCount in MockOptimizer

---

src/Nonlinear/parse.jl
test/Nonlinear/Nonlinear.jl

Issue raised in https://github.com/PSORLab/EAGO.jl/issues/150
I'll run `solver-tests` to see if there's any impact.
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/16733837980

[Nonlinear] parse x*x as x^2 in Nonlinear.Model

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/IntervalToHyperRectangleBridge.jl
src/Bridges/Constraint/bridges/VectorizeBridge.jl
test/Bridges/Constraint/IntervalToHyperRectangleBridge.jl
test/Bridges/debug.jl
test/Bridges/lazy_bridge_optimizer.jl

Needed to use `MatrixOfConstraints` in the COSMO MOI wrapper (see https://github.com/oxfordcontrol/COSMO.jl/pull/198)
Requires
the bridge
named after the type of the bridge
bridge
the model:

[Bridges] Add Interval to HyperRectangle constraint bridge

---

test/FileFormats/NL/read.jl
test/runtests.jl

x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2804

Add a test that methods are not overwritten in test modules

---

src/Bridges/Constraint/bridges/SplitHyperRectangleBridge.jl

Fix for the issues detected in the SolverTests run of https://github.com/jump-dev/MathOptInterface.jl/pull/2808
I did not add any test since the test is in https://github.com/jump-dev/MathOptInterface.jl/pull/2810
I did https://github.com/jump-dev/MathOptInterface.jl/pull/2810 in a separate PR not only to show in CI that it would have caught this one but also to avoid delaying this PR and hence https://github.com/jump-dev/MathOptInterface.jl/pull/2808 in case https://github.com/jump-dev/MathOptInterface.jl/pull/2810 requires some discussion

Fix ConstraintDual transformation for SplitHyperRectangleBridge

---

src/Bridges/Constraint/bridges/SplitHyperRectangleBridge.jl
test/Bridges/Constraint/SplitHyperRectangleBridge.jl

Fix SplitHyperRectangleBridge with all free rows

---

src/Bridges/Constraint/bridges/SemiToBinaryBridge.jl
src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

Closes #2817 
I don't think this is the proper fix. But passes the test. I want to run `solver-tests` with it if CI is green
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/17026926756

[Bridges] fix deleting variable with constraint bridges

---

Project.toml
docs/src/changelog.md

Prep for v1.43.0

---

src/Utilities/results.jl
test/Utilities/results.jl

[Utililties] fix dual objective value with open intervals

---

src/Utilities/results.jl
test/Bridges/Constraint/NormSpectralBridge.jl
test/Utilities/results.jl

[Utilities] simplify _dual_objective_value

---

src/Bridges/Objective/bridges/FunctionConversionBridge.jl
test/Bridges/Constraint/ScalarFunctionizeBridge.jl
test/Bridges/Objective/FunctionConversionBridge.jl
test/Bridges/Objective/ToScalarNonlinearBridge.jl

Follow-up to #2834
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/17536184058

[Bridges] restrict when ToScalarNonlinearBridge applies and simplify tests

---

src/FileFormats/LP/read.jl

Before
```Julia
julia> import MathOptInterface as MOI
julia> function main()
model = MOI.FileFormats.LP.Model{Float64}()
MOI.read_from_file(model, "/Users/odow/Downloads/QPLIB_10005.lp")
return model
end
main (generic function with 1 method)
julia> @time main();
1.065072 seconds (43.71 M allocations: 1.511 GiB, 22.66% gc time)
```
After
```julia
julia> import MathOptInterface as MOI
julia> function main()
model = MOI.FileFormats.LP.Model{Float64}()
MOI.read_from_file(model, "/Users/odow/Downloads/QPLIB_10005.lp")
return model
end
main (generic function with 1 method)
julia> @time main();
1.062581 seconds (30.88 M allocations: 1.156 GiB, 19.92% gc time)
```

[FileFormats.LP] remove lowercase usage to reduce allocations

---

docs/make.jl
docs/src/submodules/FileFormats/LP.md
docs/styles/config/vocabularies/JuMP/accept.txt
src/FileFormats/LP/read.jl
src/Test/test_conic.jl
test/FileFormats/LP/LP.jl
test/FileFormats/LP/models/model1_tricky.lp

And fall down the rabbit hole with respect to the many differences between solvers.
Now that I've played around with Xpress, I wonder if I need to re-re-think how we go about new line handling. Gurobi's parser is pretty weak in comparison.
My justification for spending so much time on this is that people reading LP files actually happens quite a lot, and historically, we have had many issues related to it (and, I assume, many more that aren't reported).
I think a single, great, open-source implementation that publicly documents all the weird differences in solvers is actually pretty useful.

[FileFormats.LP] add a documentation page and refactor some names

---

docs/Project.toml

x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/12080
Unless this gets fixed upstream with a yank: https://github.com/JuliaRegistries/General/pull/138670

[docs] temporarily pin OpenSSL_jll to work around upstream bug

---

src/Bridges/Constraint/bridges/IndicatorToMILPBridge.jl
test/Bridges/Constraint/IndicatorToMILPBridge.jl

[Bridges] fix IndicatorToMILPBridge when z is not binary

---

src/Bridges/Variable/bridges/ZerosBridge.jl
test/Bridges/Variable/zeros.jl

[Bridges] throw GetAttributeNotAllowed in ZerosBridge

---

src/Bridges/Constraint/bridge.jl
src/Bridges/Constraint/single_bridge_optimizer.jl
src/Bridges/lazy_bridge_optimizer.jl
src/Test/Test.jl
src/Utilities/model.jl
src/constraints.jl

Add nospecialize to some very highly specialized methods
