docs/src/apireference.md
docs/src/index.md
src/MathOptInterface.jl
src/attributes.jl
src/constraints.jl
src/objectives.jl
src/references.jl
src/variables.jl

change model to instance, separate solver and instance attributes

---

src/MathOptInterface.jl
test/contconic.jl
test/contlinear.jl
test/intlinear.jl
test/runtests.jl

lots of tests to add
can also add integer conic tests etc with Pajarito later
will fail tests for now

started on tests

---

docs/src/apimanual.md
docs/src/apireference.md
src/MathOptInterface.jl
src/constraints.jl
src/functions.jl

@joehuchette @ccoffrin @odow @joaquimg @chriscoey @blegat

outline of manual and some initial text

---

test/contlinear.jl

basic interface test ported from MBP linproginterface
(see issue #23)

completed the test basic interface in contlin

---

docs/src/apimanual.md

- Define duality for maximization problems
- Explicitly write out the special case of LP duality
I'd like to think about how to define duality with quadratic terms after this.
@blegat @chriscoey @IssamT @joaquimg

expand on duality

---

test/contconic.jl
test/contlinear.jl
test/contquadratic.jl
test/intlinear.jl

This makes it possible to include the file from another package

Add MOI definition at the beginning of every test file

---

docs/src/apimanual.md
docs/src/apireference.md
src/sets.jl

Add rotated second order cone

---

docs/src/apimanual.md

Closes #58 
Closes #56 
@IssamT

more discussion of variable bounds

---

src/MathOptInterface.jl
src/attributes.jl

Not sure how other solvers passed tests without these?
Note: not a complete set of changes. I may discover more

Fixes needed to get tests to run

---

src/constraints.jl
test/contconic.jl
test/contlinear.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/69

Add shorthand fallbacks for constraints

---

test/contconic.jl

I have added support for SOCRotated to [SOI](https://github.com/JuliaOpt/SemidefiniteOptInterface.jl) and fixed the tests at the same time.
@joaquimg If you agree with the changes, you can merge it (note that I have set up the branch to merge itself in your branch, not on master).

Fix SOCRotated tests

---

test/intconic.jl

adds **conicinterface.jl** 4 from #23

add intconic test

---

src/constraints.jl
test/contlinear.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/89

Transform constraint

---

test/contlinear.jl

@blegat forgot to change test the rebase of https://github.com/JuliaOpt/MathOptInterface.jl/pull/108

fix arguments to linear11test

---

docs/src/apireference.md
src/constraints.jl

add canmodifyconstraint

---

docs/src/apimanual.md

I'm syncing the manual with the current practice by documenting the concept of MOI's instance (which I call a standalone instance). It's open for discussion whether it's worth implementing an abstract class or more formally defining which methods a standalone instance should implement.

clarify concept of standalone instance

---

docs/src/apireference.md
src/MathOptInterface.jl
src/constraints.jl

add canaddconstraint

---

docs/src/apimanual.md
src/MathOptInterface.jl
src/sets.jl

correct use of set parameters in documentation

---

LICENSE.md
docs/src/apimanual.md
docs/src/apireference.md
src/objectives.jl
test/contconic.jl
test/contlinear.jl
test/contquadratic.jl
test/intconic.jl
test/intlinear.jl

Added my employer's copyright. The tests are not themselves tested, so there may be typos.
Closes #110

remove setobjective in favor of objective attributes

---

docs/src/apireference.md
src/attributes.jl

Add variable and constraint names. 

---

docs/src/apireference.md
src/MathOptInterface.jl

writeproblem -> writeinstance

---

test/contconic.jl

Both [CSDP](https://github.com/JuliaOpt/CSDP.jl), [SDPA](https://github.com/blegat/SDPA.jl) and [Mosek](https://github.com/JuliaOpt/MathOptInterfaceMosek.jl) (except the `ConstraintPrimal` call which is not implemented yet) are passing this new test.

Add test SOCRotated1A #23

---

src/constraints.jl

Related to https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/24

Add types to shortcuts for [vector of] variables

---

src/functions.jl

But keep simple names for the functions using VariableReference
https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/pull/22#discussion_r147913099

Make functions generic with respect to variable type

---

src/functions.jl

This reverts commit 971a87de4455a5488df3272a31c234d5aee45112. See https://github.com/JuliaOpt/MathOptInterface.jl/pull/157#issuecomment-341285653.
I think this is a case where we're shooting ourselves in the foot to save a few lines of tedious redefinitions that only need to be written once and are easy to verify, and as a result we're inflicting unnecessary pain on anyone using MOI. I don't like the fact that the `Generic` names will leak through all sorts of error messages. The shortcut definitions don't let you hide the extra cognitive load of the generic types.

Revert "Make functions generic with respect to variable type"

---

docs/src/apimanual.md
src/MathOptInterface.jl
src/attributes.jl
src/constraints.jl
src/objectives.jl
src/references.jl
src/variables.jl
test/contconic.jl
test/contlinear.jl
test/contquadratic.jl
test/intconic.jl
test/intlinear.jl

There was a lot of automation involved, so would help to get a sanity check. MOIU and JuMP/MOI still pass their tests, at least.
Closes #161

s/m/instance/g 

---

docs/src/apimanual.md
docs/src/apireference.md
src/MathOptInterface.jl
src/attributes.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/164

remove the "solver" concept

---

docs/src/apireference.md
src/attributes.jl

Fix AnyAttribute

---

docs/src/apimanual.md
docs/src/apireference.md
src/sets.jl

Remove scaled and add duality note for triangle

---

src/MathOptInterface.jl

Closes #179
Closes #178
Closes #163

copy! returns an index map

---

docs/src/apireference.md
src/MathOptInterface.jl

add cancopy

---

docs/src/apireference.md
src/MathOptInterface.jl

Implement CopyResult and remove cancopy

---

src/attributes.jl
src/constraints.jl

canget on typeof of index instead of index

---

docs/src/apimanual.md
src/MathOptInterface.jl
src/attributes.jl

Let's break the MOI world again \o/
Closes #197

Parametrize ObjectiveFunction

---

docs/src/apireference.md
src/MathOptInterface.jl
src/attributes.jl

See discussion following https://github.com/JuliaOpt/MathOptInterfaceTests.jl/pull/44#issuecomment-359189967

Remove mustcopy and add AbstractSolverParameter

---

src/constraints.jl
src/objectives.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/200

can... functions only use type information

---

docs/src/apireference.md

See https://github.com/JuliaOpt/MathOptInterface.jl/issues/209

Add doc for empty! and isempty

---

src/sets.jl
test/interval.jl
test/runtests.jl

I found these to be useful while writing the OSQP interface.

Add convenience constructors for Interval.

---

docs/src/apimanual.md

Discuss canXXX in manual

---

REQUIRE
src/MathOptInterface.jl
src/Utilities/Utilities.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/copy.jl
src/Utilities/functions.jl
src/Utilities/mockoptimizer.jl
src/Utilities/model.jl
src/Utilities/parser.jl
src/Utilities/sets.jl
test/cachingoptimizer.jl
test/copy.jl
test/functions.jl
test/mockoptimizer.jl
test/model.jl
test/parser.jl
test/runtests.jl
test/sets.jl

I haven't included the bridges yet as they can be decoupled from the rest of MOIU. Bridges requires MOIU but none of MOIU requires bridges. Moreover, bridges are not necessary to test MOI so we have 3 choices:
1. Leave bridges in MOIU
2. Add bridges in a submodule MOI.Bridges
3. Put bridges in a separate package MOIBridges.jl
What do you prefer ?

Add MOIU as a submodule

---

src/Test/contconic.jl
test/mockoptimizer.jl

It helped catch a bug in the tests as can be seen from the changes :)

Test duals

---

docs/src/apimanual.md

I was preparing some slides on MOI and made these improvements to the manual in the process.

improve list of functions and sets in manual

---

src/Test/contconic.jl
test/contconic.jl

Add primal analytic solution of sdp1

---

src/MathOptInterface.jl

Clarify how read! works

---

src/Test/modellike.jl
src/attributes.jl
test/model.jl

I'm a little behind on the whole testing infrastructure so I hope this is the correct way to test it.
Closes #230

Test ordered ListofXXXIndices

---

src/Test/contlinear.jl
src/indextypes.jl
test/contlinear.jl

It wasn't implemented for Mock and `@model` as it is also not tested

Add fallback for delete! with vector of indices

---

src/Test/contlinear.jl

Useful for fixing errors on tests nearby

Add small tests for contlin

---

src/Utilities/Utilities.jl
src/Utilities/universalfallback.jl
test/runtests.jl
test/universalfallback.jl

Add UniversalFallback

---

docs/src/apireference.md
src/nlp.jl

I'd like to make this change throughout MOI (#211). NLP is the easiest since it doesn't break much yet. I have some preliminary NLP work that I'll push after this.
@odow @ccoffrin @tkoolen @blegat

switch to arrays of structs in the NLP interface

---

src/Test/modellike.jl
test/universalfallback.jl

Related to https://github.com/JuliaOpt/JuMP.jl/pull/1211

Rename BadAttributes -> UnknownAttribute

---

src/Test/Test.jl
src/Test/intlinear.jl
src/Test/nlp.jl

I have a local copy of Ipopt/MOI that passes this test.

first NLP test

---

src/Test/contlinear.jl
test/contlinear.jl

Fix dual for contlinear14

---

src/Utilities/model.jl
src/Utilities/universalfallback.jl
test/universalfallback.jl

Implements ListOfAttributesSet for UniversalFallback

---

NEWS.md

create NEWS.md and populate for MOI 0.1 and 0.2

---

src/Test/contquadratic.jl

`@testset` are already added by
https://github.com/JuliaOpt/MathOptInterface.jl/blob/023af29151a1fb9cd6e2d0555b28f9543521bdfe/src/Test/config.jl#L42

Remove @testset in contquadratic

---

src/Bridges/Bridges.jl
src/Bridges/rsocbridge.jl
test/bridge.jl

Closes https://github.com/JuliaOpt/MathOptInterfaceBridges.jl/issues/38

Add RSOC bridge

---

src/Utilities/mockoptimizer.jl
test/mockoptimizer.jl

Implements names for MockOptimizer.

Add name support for mockoptimizer

---

docs/src/apimanual.md

Some wrapper may loose readability if everything is stuffed into a large file, what do you think ?

Allow MOIWrapper folder

---

test/runtests.jl

Requires Compat v0.33 so no bump required

Use Compat.Test

---

src/indextypes.jl

Document uniqueness of constraintindexes

---

src/Test/contconic.jl

It's not all of them but it's a first step :)

[array_of_tuples] don't broadcast monoterms

---

docs/src/apimanual.md

Closes #371. Please proofread!
I'm ready to tag MOI 0.3 after this, let me know if you think anything else should go in first.

update the manual for new function definitions

---

src/functions.jl
test/functions.jl

Fix #377, Likely persistent annoyances with 32 bit support due to explicit Int64s

---

REQUIRE
src/Utilities/functions.jl

Related to https://github.com/JuliaOpt/MathOptInterface.jl/issues/378, the next failure is https://github.com/JuliaOpt/MathOptInterface.jl/issues/317

coalesce -> something

---

docs/src/apimanual.md

Brief guidance on using CachingOptimizer in solver wrappers

---

src/Bridges/detbridge.jl
src/sets.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/412.

dimension -> side_dimension where it makes sense

---

NEWS.md

Please take a look and let me know if there's any reason not to tag 0.5 tomorrow morning.
@odow @blegat @joaquimg

prepare news for MOI 0.5

---

src/MathOptInterface.jl
src/Utilities/functions.jl

Blocked by until https://github.com/JuliaLang/Compat.jl/pull/602 is merged and released

Fixes for Julia v0.7-rc2

---

src/Bridges/bridgeoptimizer.jl
test/bridge.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/453

Fix bug in bridges querying index via string

---

appveyor.yml

Replace the appveyor script with [the new one](https://discourse.julialang.org/t/ann-improved-appveyor-scripts/12754)

Update appveyor script

---

NEWS.md

x-ref https://github.com/oxfordcontrol/OSQP.jl/pull/25#discussion_r208277285

clarify the different kinds of errors in NEWS.md

---

docs/src/apireference.md
src/MathOptInterface.jl
src/Test/nlp.jl
src/nlp.jl

Related to https://github.com/JuliaOpt/MathOptInterface.jl/issues/475

Rename read, write and initialize

---

docs/src/apimanual.md
docs/src/apireference.md
src/Bridges/bridgeoptimizer.jl
src/Bridges/intervalbridge.jl
src/Test/UnitTests/modifications.jl
src/Test/contlinear.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/mockoptimizer.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
src/constraints.jl
src/modifications.jl
test/cachingoptimizer.jl

Related to https://github.com/JuliaOpt/MathOptInterface.jl/issues/475

Rename modify! -> modify

---

docs/src/apimanual.md

Closes https://github.com/JuliaOpt/GLPK.jl/issues/77.

fix the knapsack example

---

NEWS.md

Add missing points to NEWS

---

src/indextypes.jl

@IainNZ found that this improved variable creation time by 20%

implement hash() for VariableIndex

---

src/Test/modellike.jl
src/Utilities/universalfallback.jl

Closes https://github.com/JuliaOpt/JuMP.jl/issues/1556

Fix universall fallback w/ ObjectiveFunctionType

---

NEWS.md

I have used unicode symbols to help the user distinguish between bug fixes (🐛), performance improvements (⚡️), usability improvements (🚸) and new features (✨).

Prepare NEWS for MOI v0.6.2

---

README.md
docs/Project.toml
docs/make.jl

<strike>It is currently DNMY because there is an issue with crosslinks: https://github.com/JuliaDocs/Documenter.jl/issues/868</strike>
See https://discourse.julialang.org/t/ann-documenter-0-20-with-breaking-changes-released/16907

Update to Documenter v0.20

---

.travis.yml

See https://discourse.julialang.org/t/coverage-generation-on-travis/14138/2

👷 Update coverage script

---

src/Test/modellike.jl
src/Utilities/copy.jl
src/Utilities/universalfallback.jl
src/attributes.jl
test/universalfallback.jl

Closes #545
Closes https://github.com/JuliaOpt/JuMP.jl/issues/1460

✨ Add support for copying attributes not set to all indices

---

src/Utilities/cachingoptimizer.jl
src/Utilities/mockoptimizer.jl
test/Utilities/cachingoptimizer.jl

And implement SolverName for MockOptimizer
Closes #435

allow accessing optimizer attributes through CachingOptimizer

---

docs/src/apimanual.md

Add guideline for naming solvers.

---

docs/src/apimanual.md

Document solver-specific attributes.

---

src/Bridges/singlebridgeoptimizer.jl
src/Utilities/model.jl
test/Utilities/model.jl
test/bridge.jl
test/hygiene.jl

Fix error with external functions and sets.

---

NEWS.md
src/Test/contconic.jl
src/Test/contlinear.jl
src/Test/contquadratic.jl
src/Test/intconic.jl
src/Test/intlinear.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/583

✅ Test Status before optimize!

---

NEWS.md
docs/src/apimanual.md
src/Bridges/detbridge.jl
src/Test/UnitTests/basic_constraint_tests.jl
src/Test/contconic.jl
src/Utilities/results.jl
src/sets.jl
test/Test/contconic.jl
test/Utilities/sets.jl
test/bridge.jl

Rebased #553 and made the change suggested in https://github.com/JuliaOpt/MathOptInterface.jl/pull/553#discussion_r229964953
Closes #546 
Closes #553

Add perspective in log-det cone

---

src/Test/UnitTests/unit_tests.jl
src/Test/config.jl
src/Test/contconic.jl
src/Test/contlinear.jl
src/Test/contquadratic.jl
src/Test/intconic.jl
src/Test/intlinear.jl
src/Test/nlp.jl

So that local solvers can pass tests.
Closes #597.

Add config.optimal_status

---

NEWS.md
src/attributes.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/601

Add AlmostDualInfeasible

---

src/Test/nlp.jl
src/attributes.jl
src/nlp.jl

See https://github.com/JuliaOpt/JuMP.jl/pull/1741.

NLP objectives override ObjectiveFunction()

---

src/Bridges/Bridges.jl
src/Bridges/bridgeoptimizer.jl
src/Bridges/lazybridgeoptimizer.jl
src/Test/modellike.jl
src/Utilities/model.jl
src/Utilities/universalfallback.jl
test/bridge.jl

This is required by https://github.com/JuliaOpt/JuMP.jl/pull/1733 as it needs to be able to hold `Nonnegative`

Use UniversalFallback in fullbridgeoptimizer

---

src/Test/contlinear.jl
test/Test/contlinear.jl
test/Utilities/cachingoptimizer.jl
test/Utilities/model.jl
test/bridge.jl

Ref https://github.com/JuliaOpt/Ipopt.jl/issues/155

add test for solving with a partial starting point

---

docs/src/apireference.md
src/attributes.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/99

✨ Add SpecificTerminationStatus

---

src/Test/UnitTests/constraints.jl
test/Test/unit.jl

Inspired from @rdeits test in https://github.com/JuliaOpt/MathOptInterfaceMosek.jl/issues/41

✅ Add tests with constraint with duplicates

---

src/Utilities/functions.jl
test/Utilities/functions.jl

✨ Add func * constant

---

src/Utilities/functions.jl
test/Utilities/functions.jl

🐛 Fix affine / constant

---

src/Utilities/functions.jl
test/Utilities/functions.jl

✨ Add unary +

---

src/functions.jl
test/functions.jl

✨ Makes scalar MOI functions broadcastable

---

src/Utilities/functions.jl

See https://github.com/JuliaOpt/MathOptInterface.jl/pull/644#discussion_r251182144

📝 [ci skip] Specify meaning of T in operate

---

src/Bridges/Bridges.jl
src/Bridges/flip_sign_bridge.jl
src/Utilities/functions.jl
test/Utilities/functions.jl
test/bridge.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/516

✨ Add FlipSign bridges

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Implements the division operation for ScalarQuadraticFunction.
I still need to add tests but had a hard time finding where to add them...
Closes #672.

✨ Add / for ScalarQuadraticFunction

---

src/sets.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/588

Fix mapping of matrix indices

---

src/Utilities/functions.jl

It is implemented but was just missing in the docstring

Add quadratic function to doc of canonical

---

src/Test/UnitTests/modifications.jl
src/Utilities/functions.jl
test/Test/unit.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/676

Remove variable with SingleVariable objective

---

src/constraints.jl
test/errors.jl

The current error message is "... constraints is"

constraints is -> constraint is

---

.travis.yml
Project.toml
appveyor.yml

Motivated by https://github.com/JuliaOpt/MathOptInterface.jl/pull/715#issuecomment-487265932
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/661

Drop Julia v0.7

---

docs/src/apimanual.md

The manual could use some doc on indicators

add indicator documentation

---

src/attributes.jl

In accordance to the JuMP style guide

resultindex -> result_index

---

docs/src/apireference.md
src/attributes.jl

See https://github.com/JuliaOpt/MathOptInterface.jl/pull/387#issuecomment-466648208

Add RawParameter

---

src/Bridges/Constraint/soc_to_psd.jl
test/Bridges/Constraint/soc_to_psd.jl
test/Bridges/lazy_bridge_optimizer.jl

See https://github.com/JuliaOpt/MathOptInterface.jl/issues/750

Implement getters for RSOCtoPSD

---

src/Utilities/functions.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/774

Fix type piracy with MOIU.operate

---

NEWS.md

Many more PRs were merged for updating the solvers since https://github.com/JuliaOpt/MathOptInterface.jl/pull/737.
This PR adds them to the `NEWS.md`.

Complete NEWS of MOI v0.9

---

.travis.yml

See https://docs.travis-ci.com/user/languages/julia/#coverage

Simplify coverage upload in .travis.yml

---

src/Utilities/copy.jl

Update  implementations with add_constraint_variable(s)

---

src/attributes.jl

Closes #814 
This change makes it more clear for me. Is that so for native English speaker?

Change ObjectiveSense() doc

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/slack.jl
src/Bridges/Variable/Variable.jl
test/Bridges/Constraint/slack.jl
test/Bridges/lazy_bridge_optimizer.jl
test/Bridges/utilities.jl

Update Constraint.SlackBridge and add variable bridges in full_bridge_optimizer

---

src/Utilities/copy.jl
test/Utilities/copy.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/843

Implement show for IndexMap

---

src/Bridges/bridge_optimizer.jl
src/Utilities/functions.jl
src/Utilities/mockoptimizer.jl
test/Bridges/bridge_optimizer.jl
test/Utilities/cachingoptimizer.jl

Add standalone mapping and substitution tests that allowed me to find a few bugs.
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/844

Test and fix mapping and substitution of variables

---

docs/src/apireference.md

Add NormOneCone and NormInfinityCone to doc

---

src/Utilities/model.jl
test/Utilities/model.jl

Fix supports_constraint for Semiinteger and Semicontinuous and supports for ObjectiveFunction

---

docs/src/apireference.md
src/Bridges/Bridges.jl
src/Bridges/Objective/slack.jl
src/Bridges/bridge_optimizer.jl
src/Test/contquadratic.jl
test/Bridges/Objective/map.jl
test/Bridges/Objective/slack.jl
test/Bridges/lazy_bridge_optimizer.jl

A few fixes to make sure conic solvers can now pass tests with convex quadratic objective.

Add more objective bridges docs and tests

---

src/Test/modellike.jl

Ref https://github.com/JuliaOpt/GLPK.jl/pull/118, https://github.com/JuliaOpt/Gurobi.jl/pull/251

Add more comprehensive tests for names

---

src/Test/UnitTests/solve.jl
test/Test/unit.jl

Ref: https://github.com/JuliaOpt/GLPK.jl/pull/119, https://github.com/JuliaOpt/Gurobi.jl/issues/250

Add tests for SingleVariable duals

---

docs/src/apimanual.md

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/874

Update doc for SingleVariable indices and bridges

---

src/Bridges/Constraint/geomean.jl
src/Test/UnitTests/basic_constraint_tests.jl
src/Utilities/functions.jl
test/Bridges/Constraint/geomean.jl

See https://github.com/JuliaOpt/MathOptInterface.jl/issues/750

Implement get for function and set for geomean bridge

---

src/Bridges/Constraint/functionize.jl
src/Bridges/Constraint/scalarize.jl
src/Bridges/bridge_optimizer.jl
src/Bridges/lazy_bridge_optimizer.jl
src/Utilities/functions.jl
test/Bridges/lazy_bridge_optimizer.jl

Needed for https://github.com/JuliaOpt/MathOptInterface.jl/issues/841

Automatic selection of Constraint.FunctionizeBridge

---

src/Utilities/copy.jl
test/Utilities/copy.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/875

Fix copy with VectorOfVariables with duplicate indices

---

docs/src/apimanual.md

Add note on duplicate coefficients.

---

src/Bridges/Constraint/square.jl
src/Test/UnitTests/basic_constraint_tests.jl
test/Bridges/Constraint/square.jl

See https://github.com/JuliaOpt/MathOptInterface.jl/issues/750

Implement MOI.get for function/set for SquareBridge

---

src/Test/modellike.jl
test/Bridges/lazy_bridge_optimizer.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/851

Implement shift_constraint for UnknownScalarSet

---

docs/src/apireference.md
src/Utilities/Utilities.jl
src/Utilities/variables.jl
test/Utilities/Utilities.jl
test/Utilities/variables.jl

Computes variable lower/upper bounds set on a MOI variable

Add get_bounds to Utilities

---

src/attributes.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/11

Add result index in ConstraintBasisStatus

---

docs/src/apireference.md
src/Test/UnitTests/attributes.jl
src/Utilities/cachingoptimizer.jl
src/attributes.jl
test/Test/unit.jl
test/Utilities/cachingoptimizer.jl

I realized afterwards that I didn't need this feature. Since it's done I open this PR anyway in case you think that can be useful.

Add NumberOfThreads

---

src/Bridges/Objective/functionize.jl
src/Bridges/Objective/slack.jl
src/Bridges/bridge_optimizer.jl
test/Bridges/Objective/functionize.jl

Found while trying to make @odow's new `solve_result_index` test for SDPT3.

Fix result_index with objective bridges

---

docs/src/apireference.md
src/Bridges/Bridges.jl
src/Bridges/debug.jl
src/Bridges/lazy_bridge_optimizer.jl
test/Bridges/lazy_bridge_optimizer.jl

See https://github.com/JuliaOpt/MathOptInterface.jl/issues/680

Add debug utilities for unsupported variable/constraint/objective

---

src/Test/UnitTests/solve.jl

For Mosek, the value of `ResultCount` is 2

Use ResultCount + 1 instead of 2 for out of bound result_index

---

NEWS.md

Cbc is working with MOI v0.9.5: https://github.com/JuliaOpt/Cbc.jl/pull/126

NEWS for v0.9.5

---

src/Test/UnitTests/basic_constraint_tests.jl

This would have caught https://github.com/JuliaOpt/GLPK.jl/pull/121

Add InvalidIndex tests in basic_constraint_tests

---

src/Utilities/model.jl
test/Utilities/model.jl

Caught when testing MOI master against Cbc master:
https://travis-ci.com/blegat/SolverTests/jobs/249637416

Throw InvalidIndex when getting function/set

---

src/nlp.jl

- should fix failure for MINLPTests with Ipopt:
https://travis-ci.org/JuliaOpt/MINLPTests.jl/builds/603635262

implement _result_index_field for NLPBlockDual

---

src/Bridges/Constraint/vectorize.jl
test/Bridges/Constraint/vectorize.jl

Implement starting values for Bridges.Constraint.VectorizeBridge

---

src/Bridges/Constraint/scalarize.jl
test/Bridges/Constraint/scalarize.jl

Implement starting values for Bridges.Constraint.ScalarizeBridge

---

src/Bridges/Constraint/interval.jl
test/Bridges/Constraint/interval.jl

Add support for starting values for interval bridge

---

src/Test/modellike.jl
src/Utilities/functions.jl

Fix of the bug reported in https://gist.github.com/ericphanson/9ab9f8460bbe5200be82d0b0cb55ecd5 by @ericphanson

Fix copy of model with starting values for vector constraint

---

src/Bridges/Variable/bridge.jl
src/Bridges/Variable/flip_sign.jl
src/Bridges/Variable/free.jl
src/Bridges/Variable/vectorize.jl
test/Bridges/Variable/flip_sign.jl
test/Bridges/Variable/free.jl
test/Bridges/Variable/vectorize.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/943

Implement variable start for Variable.VectorizeBridge

---

perf/bellman_ford.jl

Add a benchmark of Bellman-Ford on the two examples I usually use in my presentations.

Add Bellman-Ford benchmark

---

src/sets.jl
test/sets.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/947

Fix dimension of Complements

---

docs/src/apireference.md
src/Utilities/sets.jl
test/Utilities/sets.jl

See https://github.com/JuliaOpt/SCS.jl/pull/165

Add is_diagonal_vectorized_index utility

---

.travis.yml
Project.toml
src/Utilities/Utilities.jl
src/Utilities/functions.jl
src/Utilities/mutable_arithmetics.jl
src/functions.jl
test/Utilities/Utilities.jl
test/Utilities/functions.jl
test/Utilities/mutable_arithmetics.jl

cc @tweisser @Peiffap @saschatimme

Implement MutableArithmetics

---

src/Utilities/mockoptimizer.jl
src/variables.jl

Add fallback for add_variables

---

src/Utilities/functions.jl
test/issue980.jl
test/runtests.jl

Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/980

Workaround for issue #980

---

docs/make.jl

Switches back to MathJax. Closes #988.

Fix broken equations in docs

---

docs/src/apireference.md
src/MathOptInterface.jl
src/instantiate.jl
test/instantiate.jl
test/runtests.jl

See https://github.com/JuliaOpt/JuMP.jl/issues/2138#issuecomment-575680880
We might consider the name `ParametrizedOptimizer` instead of `UninstantiatedOptimizer`.

Add OptimizerWithAttributes

---

src/Bridges/Constraint/geomean.jl

The tests were added in https://github.com/JuliaOpt/MathOptInterface.jl/pull/1021

Implement ConstraintDual for Constraint.GeoMeanBridge

---

src/Test/nlp.jl
test/Test/nlp.jl

Add tests for using ExprGraphs from NLP evaluators

---

src/Bridges/bridge_optimizer.jl

I think there  is a missing "bridge" in this line.

Adding missing term in docs

---

src/sets.jl

I think the documentation showed the wrong variables and coefficients. Hope the changes are correct.

IndicatorSet documentation

---

src/Utilities/functions.jl

Fix is_canonical for SQF, VQF

---

src/Utilities/Utilities.jl
src/Utilities/universalfallback.jl
test/Utilities/universalfallback.jl

Fixes https://github.com/JuliaOpt/JuMP.jl/issues/2238
Uses idea by @odow 
Thanks again for pointing me where the randomness happens

deterministic ordering of constraints -> variable indices

---

src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

A few issues remained after https://github.com/jump-dev/MathOptInterface.jl/pull/1084:
* `supports_add_constrained_variable(s)` still needed to be defined
* It should also add constrained variables to the cache in case it is needed

Fix constrained variables for caching optimizer

---

docs/src/apimanual.md
src/Test/config.jl

Solves [#1029](https://github.com/JuliaOpt/MathOptInterface.jl/issues/1029)

Updating docs for MOI.Test.unittest

---

.travis.yml

Following the lead of https://github.com/jump-dev/JuMP.jl/pull/2269

Modify .travis.yml to reduce CI load

---

src/FileFormats/LP/LP.jl
src/FileFormats/MPS/MPS.jl
src/Utilities/model.jl
test/FileFormats/LP/LP.jl
test/FileFormats/MPS/MPS.jl

Fixed unsupported objectives in FileFormats

---

docs/src/apimanual.md
docs/src/apireference.md
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/interval.jl
src/Bridges/Constraint/slack.jl
src/Bridges/Constraint/zero_one.jl
test/Bridges/Constraint/zero_one.jl
test/Bridges/utilities.jl

Add ZeroOneBridge

---

docs/src/apimanual.md
src/Bridges/Constraint/rsoc.jl

in reference to #1098 
though i didn't change in lemma/proofs

uniform norms in docs

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1138

Fix convert_approx with multiple nonzero terms

---

.travis.yml
src/FileFormats/MOF/read.jl
src/Utilities/CleverDicts.jl
src/Utilities/DoubleDicts.jl
test/Utilities/CleverDicts.jl

Fix support for 32-bit

---

src/Utilities/Utilities.jl
src/Utilities/functions.jl
src/Utilities/mutable_arithmetics.jl
test/Utilities/functions.jl

Taken from https://github.com/blegat/ComplexOptInterface.jl/blob/7a90ad8a43f01f0d0ca6e4c2addfcfc900b2d96b/src/Bridges/Constraint/split_zero.jl#L1-L12

Support for complex operations: real, imag and conj

---

docs/src/apireference.md

Doctests work on both julia 1.5.2 and 1.0.5

---

.JuliaFormatter.toml
src/FileFormats/CBF/CBF.jl
src/FileFormats/FileFormats.jl
src/FileFormats/LP/LP.jl
src/FileFormats/MOF/MOF.jl
src/FileFormats/MOF/nonlinear.jl
src/FileFormats/MOF/read.jl
src/FileFormats/MOF/write.jl
src/FileFormats/MPS/MPS.jl
src/FileFormats/SDPA/SDPA.jl
src/FileFormats/utils.jl

A quick scan suggests no real issues. The `/src/Utilities/` diff is much scarier (longer).

Use JuliaFormatter to format /src/FileFormats

---

src/Benchmarks/Benchmarks.jl

Breaking these down into (semi-)manageable PRs, instead of one gigantic one that touches every line in MOI.

Use JuliaFormatter to format /src/Benchmarks

---

src/MathOptInterface.jl
src/attributes.jl
src/constraints.jl
src/error.jl
src/functions.jl
src/indextypes.jl
src/instantiate.jl
src/modifications.jl
src/nlp.jl
src/sets.jl
src/variables.jl

Breaking these down into (semi-)manageable PRs, instead of one gigantic one that touches every line in MOI.

Use JuliaFormatter to format /src/*.jl

---

src/Test/UnitTests/attributes.jl
src/Test/UnitTests/basic_constraint_tests.jl
src/Test/UnitTests/constraints.jl
src/Test/UnitTests/modifications.jl
src/Test/UnitTests/objectives.jl
src/Test/UnitTests/solve.jl
src/Test/UnitTests/unit_tests.jl
src/Test/UnitTests/variables.jl
src/Test/config.jl
src/Test/contconic.jl
src/Test/contlinear.jl
src/Test/contquadratic.jl
src/Test/intconic.jl
src/Test/intlinear.jl
src/Test/modellike.jl
src/Test/nlp.jl

Breaking these down into (semi-)manageable PRs, instead of one gigantic one that touches every line in MOI.

Use JuliaFormatter to format /src/Test

---

src/Utilities/CleverDicts.jl
src/Utilities/DoubleDicts.jl
src/Utilities/Utilities.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/constraints.jl
src/Utilities/copy.jl
src/Utilities/functions.jl
src/Utilities/lazy_iterators.jl
src/Utilities/mockoptimizer.jl
src/Utilities/model.jl
src/Utilities/mutable_arithmetics.jl
src/Utilities/parser.jl
src/Utilities/results.jl
src/Utilities/sets.jl
src/Utilities/universalfallback.jl
src/Utilities/variables.jl

Breaking these down into (semi-)manageable PRs, instead of one gigantic one that touches every line in MOI.

Use JuliaFormatter to format /src/Utilities

---

src/attributes.jl

[docs] Clarify BasisStatusCode

---

src/Utilities/functions.jl
test/Utilities/functions.jl

[Utilities] fix bug in function modification

---

src/Bridges/lazy_bridge_optimizer.jl
src/Utilities/cachingoptimizer.jl
src/Utilities/mockoptimizer.jl
test/attributes.jl

Closes #1203 
Still needs a test for the `is_bridged` branch.

Fix integration of compute_conflict through layers

---

.github/workflows/documentation.yml

See https://discourse.julialang.org/t/tip-use-julia-as-custom-shell-in-github-actions/53377

Simplify documentation GH action with custom shell

---

CITATION.bib
README.md

Add citation for MathOptInterface

---

src/Bridges/bridge_optimizer.jl
src/Utilities/lazy_iterators.jl
test/Bridges/bridge_optimizer.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1231

Fix double deletion of nested bridged SingleVariable constraint

---

docs/src/manual/constraints.md
docs/src/manual/implementing.md
docs/src/submodules/Test/overview.md
docs/src/submodules/Utilities/overview.md
docs/src/submodules/Utilities/reference.md

I have a feeling this could get rather long...
Issues that this PR should cover

Document how to implement a solver interface

---

src/Bridges/Constraint/indicator_sos.jl
src/Bridges/Constraint/semi_to_binary.jl
src/Bridges/Constraint/soc_to_nonconvex_quad.jl
src/Bridges/Constraint/vectorize.jl
src/Bridges/Variable/vectorize.jl
src/MathOptInterface.jl
src/Test/UnitTests/basic_constraint_tests.jl
src/Utilities/mockoptimizer.jl
src/Utilities/results.jl
src/attributes.jl
src/deprecate.jl
src/nlp.jl
test/deprecate.jl
test/runtests.jl

[breaking] Replace N field with result_index

---

src/Utilities/parser.jl

Fix ordering of objective setting in parser

---

src/Utilities/copy.jl

I started making more changes to Utilities/copy.jl, but the formatting changes were getting in the way.

Formatting fixes to copy.jl

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/failing_models/parse_items_single_1.mps
test/FileFormats/MPS/failing_models/parse_items_single_2.mps
test/FileFormats/MPS/failing_models/parse_items_single_3.mps
test/FileFormats/MPS/failing_models/rhs_objective.mps
test/FileFormats/MPS/stacked_data.mps

[FileFormats.MPS] Add support for objective constant

---

src/Test/test_modification.jl

[Test] add test_modification.jl

---

src/Test/test_solve.jl

[Test] add test_solve.jl

---

src/Test/test_constraint.jl
src/Test/test_modification.jl

[Test] add test_constraint.jl

---

src/Test/test_objective.jl

[Test] add test_objective.jl

---

src/Test/test_nonlinear.jl

[Test] add test_nonlinear.jl

---

src/Test/test_linear.jl

Part of #1398
This is the old `intlinear.jl` file.

[Test] add test_linear.jl

---

src/Test/test_quadratic.jl

Part of #1398 
This was contquadratic.jl and intconic.jl

[Test] add test_quadratic.jl

---

src/Test/test_linear.jl

[Test] add content from contlinear.jl

---

src/Test/test_conic.jl

[Test] add test_conic

---

src/Utilities/universalfallback.jl

I was updating the tests in universalfallback to #1398 and found a few bugs. But the lack of spacing between functions was annoying me, so I did this first. (And I ran into #1438 and #1439)

[Utilities] style updates for UniversalFallback

---

test/Utilities/model.jl

[Test] migrate Utilities/model.jl to new MOI.Test

---

test/Utilities/copy.jl

Part of #1398 
@blegat there's a lot going on in this file. Not sure if defining lots of new types is the most efficient way to test copy? It's something to come back to once we're finished the MatrixOfConstraints stuff.

[Utilities] migrate copy.jl to the new MOI.Test

---

test/Utilities/functions.jl

Part of #1398 
This file was a bit of a mess. There was a lot of state mixed up in the different test sets.

Migrate functions.jl to modular test

---

docs/Project.toml

This was done automatically by Pkg

For ordering in docs/Project.toml

---

src/Test/test_quadratic.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/307

[Test] document quadratic SOC test

---

src/Test/test_basic_constraint.jl
test/Bridges/Constraint/bridge.jl
test/Bridges/Constraint/det.jl
test/Bridges/Constraint/flip_sign.jl
test/Bridges/Constraint/functionize.jl
test/Bridges/Constraint/geomean.jl
test/Bridges/Constraint/geomean_to_relentr.jl
test/Bridges/Constraint/indicator_activate_on_zero.jl
test/Bridges/Constraint/indicator_sos.jl
test/Bridges/Constraint/interval.jl
test/Bridges/Constraint/ltgt_to_interval.jl
test/Bridges/Constraint/map.jl
test/Bridges/Constraint/norm_spec_nuc_to_psd.jl
test/Bridges/Constraint/norm_to_lp.jl
test/Bridges/Constraint/quad_to_soc.jl
test/Bridges/Constraint/relentr_to_exp.jl
test/Bridges/Constraint/rsoc.jl
test/Bridges/Constraint/scalarize.jl
test/Bridges/Constraint/semi_to_binary.jl
test/Bridges/Constraint/slack.jl
test/Bridges/Constraint/soc_to_nonconvex_quad.jl
test/Bridges/Constraint/soc_to_psd.jl
test/Bridges/Constraint/square.jl
test/Bridges/Constraint/vectorize.jl
test/Bridges/Constraint/zero_one.jl

Migrate Bridge/Constraint tests to new Test

---

test/Bridges/lazy_bridge_optimizer.jl

Migrate lazy_bridge_optimizer to new tests

---

src/Utilities/print.jl
test/Utilities/print.jl

The `if` statements weren't needed and aren't extensible.

Improve test coverage of print.jl

---

src/Bridges/Constraint/function_conversion.jl
src/Bridges/Constraint/functionize.jl
src/Test/test_basic_constraint.jl

Test getting CanonicalConstraintFunction

---

docs/src/submodules/Bridges/implementation.md
docs/src/tutorials/bridging_constraint.md
src/Bridges/Constraint/bridge.jl

Follows https://github.com/jump-dev/MathOptInterface.jl/issues/1504#issuecomment-893245720
@odow 
@blegat

Difference between added_constraint_types and added_constrained_variable_types

---

src/Test/test_nonlinear.jl

[Test] Add test for NLP without objective

---

src/Bridges/Constraint/quad_to_soc.jl
test/Bridges/Constraint/quad_to_soc.jl

Closes #538
In addition, I better documented the function and fixed some inference issues. Julia doesn't like splatting, so let's avoid it if at all possible.

[Bridges] tidy quad_to_soc.jl

---

docs/src/reference/standard_form.md
src/attributes.jl

Clarify ConstraintPrimal for conic solvers

---

docs/make.jl
docs/src/tutorials/latency.md

[docs] add tutorial on latency

---

Project.toml

Any objections to tagging once this is merged? There are still some bugs like #1572, but they can be worked around in the solvers by excluding tests. It's not a breaking change.

Change version to 0.10.0

---

src/DeprecatedTest/modellike.jl

This is needed by NLopt: https://github.com/JuliaOpt/NLopt.jl/pull/175

Fix DeprecatedTest in modellike that were using copy_names

---

docs/src/submodules/FileFormats/overview.md
src/FileFormats/MOF/MOF.jl
src/FileFormats/MOF/mof.1.0.schema.json
src/FileFormats/MOF/read.jl
src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl
test/FileFormats/MOF/empty_model.mof.json
test/FileFormats/MOF/failing_models/blank_variable_name.mof.json
test/FileFormats/MOF/failing_models/missing_variable_name.mof.json
test/FileFormats/MOF/failing_models/unsupported_constraint_function.mof.json
test/FileFormats/MOF/failing_models/unsupported_constraint_set.mof.json
test/FileFormats/MOF/failing_models/unsupported_objective_function.mof.json
test/FileFormats/MOF/failing_models/unsupported_objective_sense.mof.json
test/FileFormats/MOF/nlp.mof.json
test/FileFormats/MOF/v0.4.mof.json

[FileFormats] Update to MathOptFormat v1.0

---

src/Bridges/Constraint/det.jl
test/Bridges/Constraint/det.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1605

Implement function and set getters for det bridges

---

src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

Another bug found by https://github.com/jump-dev/SCS.jl/pull/219

[Bridges] Fix ListOfConstraintAttributesSet

---

src/Bridges/Constraint/functionize.jl
src/Bridges/bridge_optimizer.jl
src/Test/test_modification.jl
src/Test/test_objective.jl
test/Bridges/Constraint/functionize.jl
test/Bridges/bridge_optimizer.jl

Fix modifications in bridge_optimizer

---

src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

Found by https://github.com/jump-dev/SCS.jl/pull/219#issuecomment-920460637

[Utilities] fix emptying of CachingOptimizer

---

src/Test/test_model.jl

Found while updating Ipopt. No test because I want to see what happens (I assume it's not covered). I'll add a test once CI finishes.

[Test] fix ListOfConstraintAttributesSet for BadModel

---

CITATION.bib
docs/src/index.md

Update the entry now that the article is published.

Update BibTeX entry

---

src/Bridges/Constraint/quad_to_soc.jl
test/Bridges/Constraint/quad_to_soc.jl

[Bridges] throw better error for nonconvex quadratic constraints

---

docs/src/submodules/Utilities/reference.md
src/Utilities/product_of_sets.jl
test/Utilities/product_of_sets.jl

This would be useful for
* ECOS: https://github.com/jump-dev/ECOS.jl/blob/b4074b777132b947d7f85749fb6a49bf68d72284/src/MOI_wrapper.jl#L203
* SCS: https://github.com/jump-dev/SCS.jl/blob/20d8521f5a2f4dd366beaea64550014630f5e6d1/src/MOI_wrapper/MOI_wrapper.jl#L265-L270
* SeDuMI: https://github.com/jump-dev/SeDuMi.jl/blob/1b93571a5d9e7a870688c7a5479fdbbc83196be5/src/MOI_wrapper.jl#L189-L190

Export num_rows

---

src/Test/test_constraint.jl
src/Test/test_variable.jl
test/Test/Test.jl

[Test] add generic number types in test_constraint

---

src/Test/test_infeasibility_certificates.jl
src/Test/test_nonlinear.jl
src/Test/test_objective.jl
src/Test/test_quadratic.jl
src/Test/test_solve.jl
test/Test/Test.jl

[Test] add generic number types in test_solve

---

src/Test/test_model.jl
src/Test/test_modification.jl
test/Test/Test.jl

[Test] add more generic number type support

---

src/Test/test_conic.jl
test/Test/Test.jl

Part of #841 
I still have the PSD ones to go. They had a lot of Float numerics.

[Test] add generic number types in test_conic

---

src/Test/test_infeasibility_certificates.jl

I missed adding this when the two PRs crossed over.

Fix version_added for infeasibility tests

---

src/MathOptInterface.jl
test/errors.jl

Add fallback error for compute_conflict

---

src/Test/test_modification.jl

[Test] add modification for Zeros constraint

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Needed by https://github.com/jump-dev/DiffOpt.jl/pull/187

Fix operate vcat with numbers

---

src/DeprecatedTest/config.jl
src/Utilities/copy.jl
src/attributes.jl
src/deprecate.jl

Stop exporting deprecated symbols

---

Project.toml
docs/src/release_notes.md

Prep for v0.10.8

---

src/Utilities/constraints.jl
src/Utilities/universalfallback.jl

[Utilities] remove extra type parameters

---

src/Utilities/struct_of_constraints.jl

[Utilities] move StructOfConstraints to inner constructor

---

Project.toml
docs/src/release_notes.md

This should be the last release before we make a v1.0.0 release.

Prep for v0.10.9

---

src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

Detected by https://github.com/jump-dev/ECOS.jl/pull/137

Fix modify scalar constants with bridged variables

---

src/Bridges/Constraint/function_conversion.jl
test/Bridges/Constraint/functionize.jl

[Bridges] fix UnsupportedAttribute in function_conversion.jl

---

src/Test/test_conic.jl

[Test] add a test for empty conic problem

---

Project.toml
docs/src/release_notes.md

Prep for v1.1.2

---

Project.toml
docs/src/release_notes.md

Making a release before we merge the nonlinear PRs.

Prep for v1.2.0 release

---

docs/src/manual/constraints.md

Suggested by @guilhermebodin on Gitter.

[docs] clarify quadratic constraints have 0.5 factor

---

src/Utilities/DoubleDicts.jl

follow up from #1821 - should not affect the benchmarks

The other get! in DoubleDict

---

docs/src/submodules/Nonlinear/overview.md

cc @matbesancon does this close #1823?

[docs] clarify usage of NLPBlockData

---

docs/src/reference/standard_form.md
src/Test/test_basic_constraint.jl
src/Test/test_cpsat.jl
src/Utilities/model.jl
src/sets.jl
test/sets.jl

Part of #1805
Stacked on #1828 to avoid conflicts.

Add CountGreaterThan set

---

docs/src/submodules/Nonlinear/overview.md

Found during this morning's call.

[docs] Fix typos in Nonlinear docs

---

docs/src/reference/standard_form.md
src/Test/test_basic_constraint.jl
src/Test/test_cpsat.jl
src/Utilities/model.jl
src/sets.jl
test/sets.jl

Part of #1805
Stacked on #1827 to avoid conflicts.

Add CountAtLeast set

---

docs/src/reference/standard_form.md
src/Test/test_basic_constraint.jl
src/Test/test_cpsat.jl
src/Utilities/model.jl
src/sets.jl
test/sets.jl

Part of #1805 
Stacked on #1825 to avoid conflicts.

Add CountDistinct set

---

src/Bridges/Variable/zeros.jl
test/Bridges/Variable/zeros.jl

Part of #1831 
cc @guilhermebodin

[Bridges] improve error message for ZerosBridge and ConstraintDual

---

docs/src/manual/constraints.md

I get this question often...
I even considered adding the very same text of the functions docs in the manual.

Docs for quadratic representation

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Variable/Variable.jl

Testing to see if this is still needed.

[Bridges] remove old hack for Julia 1.2

---

docs/src/submodules/Bridges/implementation.md
src/Bridges/Bridges.jl
src/Bridges/Constraint/bridge.jl
src/Bridges/Constraint/set_map.jl
src/Bridges/Objective/bridge.jl
src/Bridges/Variable/bridge.jl
src/Bridges/Variable/set_map.jl
src/Bridges/bridge.jl

In the spirit of #1504, this PR tidies up various docstrings in `Bridges`.

[Bridges] improve formatting and content of docstrings

---

src/FileFormats/LP/LP.jl
src/FileFormats/MPS/MPS.jl
src/FileFormats/NL/NL.jl
test/FileFormats/LP/LP.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/NL/NL.jl

[FileFormats] fix support of infinite constraint bounds

---

src/Bridges/Objective/Objective.jl
src/Bridges/Objective/bridge.jl
src/Bridges/Objective/bridges/functionize.jl
src/Bridges/Objective/bridges/slack.jl
src/Bridges/Objective/map.jl
src/Bridges/Objective/single_bridge_optimizer.jl

My quest continues to nit-pick and understand the code in Bridges.
<s>Oops. Needs #1859 first</s>

[Bridges] style and doc fixes for Bridges.Objective

---

docs/src/submodules/Bridges/reference.md
src/Bridges/Variable/bridge.jl
src/Bridges/Variable/bridges/flip_sign.jl
src/Bridges/Variable/bridges/free.jl
src/Bridges/Variable/bridges/vectorize.jl
src/Bridges/Variable/bridges/zeros.jl
src/Bridges/Variable/single_bridge_optimizer.jl

I didn't touch 
because they're a bit complicated and can be handled in a stand-alone PR.

[Bridges] improvements to Variable bridge docstrings

---

docs/src/submodules/Bridges/reference.md
perf/bellman_ford.jl
src/Bridges/Constraint/single_bridge_optimizer.jl
src/Bridges/bridge_optimizer.jl
src/Bridges/lazy_bridge_optimizer.jl

The `bridge_optimizer.jl` file is ... complicated.

[Bridges] more improvements to docstrings

---

src/Bridges/Objective/bridges/slack.jl

[Bridges] fix use of ConstraintSet in Objective.SlackBridge

---

src/Bridges/Constraint/bridges/flip_sign.jl
src/Bridges/Constraint/bridges/geomean_to_relentr.jl
src/Bridges/Constraint/bridges/indicator_activate_on_zero.jl
src/Bridges/Constraint/bridges/indicator_sos.jl

[Bridges] tidy various Constraint bridges

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/bridges/geomean.jl
src/Bridges/Constraint/bridges/geomean_to_relentr.jl
src/Bridges/Constraint/bridges/semi_to_binary.jl
src/Bridges/Constraint/bridges/slack.jl
src/Bridges/Constraint/bridges/vectorize.jl
src/Bridges/Constraint/set_map.jl
test/Bridges/Constraint/flip_sign.jl
test/Bridges/Constraint/functionize.jl
test/Bridges/Constraint/geomean.jl
test/Bridges/Constraint/geomean_to_relentr.jl
test/Bridges/Constraint/rsoc.jl
test/Bridges/Constraint/semi_to_binary.jl
test/Bridges/Constraint/slack.jl
test/Bridges/Constraint/soc_to_nonconvex_quad.jl
test/Bridges/Constraint/soc_to_psd.jl
test/Bridges/Constraint/vectorize.jl
test/Bridges/Constraint/zero_one.jl
test/Bridges/Objective/functionize.jl
test/Bridges/Objective/slack.jl

This is the start of an exploration to see if we can simplify how we test bridges. 
Alternative to #820
Alternative to #750 
Things that aren't addressed:
Out of scope
- Variable bridges
- VariablePrimalStart
- Modifications
- Updates

[Bridges] add unified testing infrastructure

---

docs/src/reference/standard_form.md
src/Test/test_basic_constraint.jl
src/Test/test_cpsat.jl
src/Utilities/model.jl
src/sets.jl
test/sets.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/1805

Add support for Constraint Programming

---

src/Bridges/Bridges.jl

As seen in https://github.com/jump-dev/MathOptInterface.jl/pull/1884, the new tests are missing a few methods.

[Bridges] add more tests for uncovered methods

---

src/FileFormats/NL/NLExpr.jl
test/FileFormats/NL/NL.jl

[FileFormats.NL] fix univariate OPMULT

---

src/Utilities/cachingoptimizer.jl
test/Utilities/cachingoptimizer.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1759
But we should wait for #1892 and then rebase this on top with the new error.

[Utilities] add get_fallback support in CachingOptimizer

---

src/Bridges/Constraint/bridges/indicator_sos.jl
src/Bridges/Constraint/bridges/interval.jl
src/Bridges/Constraint/bridges/norm_one.jl
test/Bridges/Constraint/indicator_sos.jl
test/Bridges/Constraint/interval.jl
test/Bridges/Constraint/ltgt_to_interval.jl
test/Bridges/Constraint/norm_to_lp.jl
test/Bridges/Constraint/scalarize.jl

Most of the remaining tests from https://github.com/jump-dev/MathOptInterface.jl/issues/820

[Bridges] add more runtests

---

src/Bridges/Constraint/bridges/det.jl
src/Bridges/Constraint/bridges/geomean.jl
src/Bridges/Constraint/bridges/indicator_activate_on_zero.jl
src/Bridges/Constraint/bridges/norm_spec_nuc_to_psd.jl
src/Bridges/Constraint/bridges/relentr_to_exp.jl
src/Bridges/Constraint/bridges/rsoc_soc.jl
src/Bridges/Constraint/bridges/semi_to_binary.jl
src/Bridges/Constraint/bridges/soc_rsoc.jl
src/Bridges/Constraint/bridges/soc_to_nonconvex_quad.jl
src/Bridges/Constraint/bridges/soc_to_psd.jl
src/Bridges/Variable/bridges/rsoc_soc.jl

Just a few small fixes and tweaks.

[Bridges] fix typos in bridge docstrings

---

src/Bridges/Bridges.jl
src/Utilities/parser.jl
test/Bridges/Variable/flip_sign.jl
test/Bridges/Variable/free.jl
test/Bridges/Variable/rsoc_to_psd.jl
test/Bridges/Variable/rsoc_to_soc.jl
test/Bridges/Variable/soc_to_rsoc.jl
test/Bridges/Variable/vectorize.jl
test/Utilities/parser.jl

This is soooo nice. I feel a lot more confident about the bridges now.

[Bridges] add tests for Variable bridges

---

src/Utilities/copy.jl

Finally an (hopefully) uncontroversial PR

typo in doc

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/bin_packing.jl
src/sets.jl

x-ref: https://github.com/jump-dev/MathOptInterface.jl/pull/1884#issuecomment-1157002608

Remove BinPackingToMILPBridge from add_all_bridges

---

src/nlp.jl

[docs] improve documentation of nonlinear API

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl

[FileFormats.LP] fix error on malformed line

---

src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

Part of #1504 
For reasons I don't fully understand, @martinbiel uses some of this API, so we can't make it private: https://github.com/martinbiel/StochasticPrograms.jl/blob/6a5b16d7c681271f103d2d98c35354c6ddd53dca/src/types/decisions/bridges/bridges.jl#L147-L156

[Bridges] begin commenting bridge_optimizer.jl

---

docs/src/background/duality.md
src/Bridges/Constraint/bridges/square.jl

Mainly a formatted version of @blegat's comment. Did I get it right?

[docs] Document square PSD duality convention

---

src/Bridges/Constraint/bridges/square.jl
test/Bridges/Constraint/square.jl

Back by popular demand.
Closes #1899

[Bridges] bring back square warning

---

Project.toml
docs/src/release_notes.md

Needed for https://github.com/jump-dev/CPLEX.jl/issues/403#issuecomment-1166642822

Prep for v1.5.0

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/count_at_least.jl
test/Bridges/Constraint/count_at_least.jl

Continues #1919 and #1901
Part of #1905

[Bridges] add CountAtLeastToCountBelongsBridge

---

src/Bridges/Constraint/bridges/count_at_least.jl
test/Bridges/Constraint/count_at_least.jl

This is what happens when I don't read my notes carefully enough...
Found by running HiGHS over the new tests.

[Bridges] fix CountAtLeastToCountBelongsBridge

---

src/Bridges/Constraint/bridges/semi_to_binary.jl
test/Bridges/Constraint/semi_to_binary.jl

I screwed up the rebase in #1919 and included these changes by mistake.
Needed for #1924

[Bridges] revert changes included in #1919 by mistake

---

src/Bridges/Constraint/bridges/semi_to_binary.jl
test/Bridges/Constraint/semi_to_binary.jl

Refactored from #1901. I'll link to @blegat's previous comments inline.
Closes #1095

[Bridges] update SemiToBinaryBridge using final_touch

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/circuit.jl
test/Bridges/Constraint/circuit.jl

Part of #1805 
I checked against MiniZinc, and this is the same formulation they use.

[Bridges] add CircuitToMILPBridge

---

test/Bridges/Constraint/bin_packing.jl
test/Bridges/Constraint/count_belongs.jl
test/Bridges/Constraint/count_distinct.jl

There were a couple of methods not tested. We need some binary variables in the original problem so that we can check the bridge correctly filters out the introduced binary variables.

[Bridges] improve code coverage

---

src/Nonlinear/ReverseAD/reverse_mode.jl
test/Nonlinear/ReverseAD.jl

Closes #1933 
I added a small test related to the issue as well.

Change Vector{T} to AbstractVector{T} in _extract_reverse_pass and add test

---

src/Utilities/matrix_of_constraints.jl
test/Utilities/matrix_of_constraints.jl

[Utilities] add ExponentialCone to set_with_dimension

---

src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/split_zeros.jl
src/Test/test_linear.jl
test/Bridges/Constraint/split_zeros.jl
test/Bridges/lazy_bridge_optimizer.jl

Refactored from https://github.com/jump-dev/ComplexOptInterface.jl

Add bridge from complex in Zeros to real/imag in Zeros

---

docs/src/tutorials/bridging_constraint.md

See https://github.com/jump-dev/MathOptInterface.jl/pull/1951#discussion_r920778838

Clarify how to implement the ConstraintFunction getter

---

src/Bridges/Constraint/bridges/split_complex_zeros.jl

See https://github.com/jump-dev/MathOptInterface.jl/pull/1952

[Bridges] fix ConstraintFunction getter of SplitComplexZerosBridge

---

docs/src/submodules/FileFormats/overview.md
src/FileFormats/MOF/MOF.jl
src/FileFormats/MOF/mof.1.1.schema.json
src/FileFormats/MOF/read.jl
src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl
test/FileFormats/MOF/empty_model.mof.json
test/FileFormats/MOF/nlp.mof.json

[FileFormats.MOF] update to MOF@v1.1

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/failing_models/malformed_qcmatrix.mps
test/FileFormats/MPS/failing_models/malformed_qmatrix.mps
test/FileFormats/MPS/failing_models/malformed_qsection.mps
test/FileFormats/MPS/failing_models/malformed_quadobj.mps

Closes #1390
<s>Still need to add readers.</s>

[FileFormats.MPS] add writers for quadratic models

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/failing_models/malformed_indicator.mps

[FileFormats.MPS] add Indicator support

---

src/Test/test_linear.jl

See https://github.com/jump-dev/SolverTests/runs/7483984523?check_suite_focus=true#step:4:386

Fix complex tests for local solver

---

docs/src/release_notes.md

Since we never ended up tagging this release for JuMP-dev.

[docs] Update v1.7.0 release notes

---

docs/src/release_notes.md

There's a lot of stuff building up, so let's get a release.

Prep for v1.7.0

---

src/FileFormats/NL/NLExpr.jl
src/Nonlinear/operators.jl
test/FileFormats/NL/NL.jl
test/FileFormats/NL/read.jl
test/Nonlinear/Nonlinear.jl

Closes #1986
I think this is another win for the work that has gone into nonlinear. It was pretty trivial to add support for a new multivariate function.
cc @a6a3uh

[Nonlinear] add support for atan2

---

Project.toml
docs/src/release_notes.md

Running SolverTests: https://github.com/jump-dev/SolverTests/actions/runs/2968721746
We potentially want to wait for #1990

Prep for v1.8.0

---

docs/src/background/motivation.md
docs/src/manual/models.md
docs/src/manual/solutions.md
docs/src/manual/standard_form.md
docs/src/manual/variables.md
docs/src/release_notes.md
docs/src/submodules/Bridges/list_of_bridges.md
docs/src/submodules/Bridges/overview.md
docs/src/submodules/FileFormats/overview.md
docs/src/submodules/Nonlinear/overview.md
docs/src/submodules/Test/overview.md
docs/src/submodules/Utilities/overview.md
docs/src/tutorials/implementing.md

[docs] fix typos in docs

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl

[FileFormats.MPS] fix parsing of OBJSENSE

---

src/Nonlinear/parse.jl
test/Nonlinear/Nonlinear.jl

x-ref https://github.com/jump-dev/JuMP.jl/pull/3106#issuecomment-1278174179

[Nonlinear] remove recursion when parsing expressions

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl

[FileFormats.MPS] add support for Indicator with EqualTo constraints

---

src/MathOptInterface.jl
test/FileFormats/FileFormats.jl

Closes #2028
cc @matbesancon is this what you had in mind?

[FileFormats] add default fallback for read_from_file and write_to_file

---

src/Nonlinear/operators.jl

Closes #2031
@mpirke is this better?

[Nonlinear] add Vector argument as possible cause to FORWARD_DIFF_METHOD_ERROR

---

src/Bridges/Objective/bridges/slack.jl
test/Bridges/Objective/slack.jl

[Bridges] fix slack bridge with complex-valued objective

---

src/Test/Test.jl

x-ref https://github.com/jump-dev/MathOptInterface.jl/issues/2026#issuecomment-1301172646

[Test] update docstring of runtests

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl

[FileFormats.LP] fix reading of free variables

---

src/instantiate.jl
test/instantiate.jl

x-ref: https://github.com/jump-dev/JuMP.jl/issues/3128
cc @ccoffrin

Support get/set of attributes in OptimizerWithAttributes

---

Project.toml
docs/src/release_notes.md

There are still a few open PRs that could go in, but a bunch of fixes have been building up.

Prep for v1.10.0

---

Project.toml
docs/src/changelog.md

Prep for v1.11.0

---

src/FileFormats/MOF/read.jl
test/FileFormats/MOF/MOF.jl

[FileFormats.MOF] fix parsing of functions with Int coefficients

---

src/FileFormats/MOF/read.jl
test/FileFormats/MOF/MOF.jl

[FileFormats] fix reading ConstraintName of VariableIndex constraints

---

src/FileFormats/MOF/read.jl
test/FileFormats/MOF/MOF.jl

[FileFormats.MOF] fix reading nonlinear objectives only

---

src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2071
x-ref: https://github.com/jump-dev/HiGHS.jl/pull/144
x-ref: https://discourse.julialang.org/t/jump-delete-is-slower-than-building-a-new-model/92597/5

[Bridges] fix deletion of a vector of constraints

---

docs/src/reference/models.md
docs/src/tutorials/implementing.md
src/MathOptInterface.jl

[docs] Document the two-argument version of optimize

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl

[FileFormats.LP] fix reading file with variable-coefficient-variable

---

src/FileFormats/LP/LP.jl
test/FileFormats/LP/LP.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2081
cc @chriscoey does this fix it?

[FileFormats.LP] fix writing of off-diag quadratic elements

---

src/Test/test_objective.jl

Add tests that setting an objective appears in ListOfModelAttributesSet

---

src/sets.jl

Raised on discourse: https://discourse.julialang.org/t/mathoptinterface-documentation/93544

[docs] fix correctness of docstrings in src/sets.jl

---

Project.toml
docs/src/changelog.md

Prep for v1.12.0

---

docs/src/submodules/Bridges/list_of_bridges.md
src/Bridges/Constraint/Constraint.jl
src/Bridges/Constraint/bridges/number_conversion.jl
src/Utilities/functions.jl
src/Utilities/sets.jl
src/functions.jl
test/Bridges/Constraint/number_conversion.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/1694
@blegat is this what you had in mind?

[Bridges] add NumberConversionBridge

---

docs/src/reference/standard_form.md
src/Bridges/Variable/Variable.jl
src/Bridges/Variable/bridges/parameter.jl
src/Test/test_basic_constraint.jl
src/Test/test_variable.jl
src/Utilities/model.jl
src/Utilities/variables_container.jl
src/sets.jl
test/Bridges/Variable/parameter.jl
test/Utilities/universalfallback.jl

Add Parameter set

---

src/instantiate.jl
test/instantiate.jl

This is useful when creating optimizers which do not support the incremental interface, or which only partially implement it.
This change is motivated by some recent examples in which it was necessary for the user to hard-code the caching logic to work-around the lack of deletion in a solver, and the caching logic is confusing to even advanced users. See:
* https://discourse.julialang.org/t/jump-scip-error/93958
* https://github.com/jump-dev/MultiObjectiveAlgorithms.jl/pull/46

[Utilities] add with_cache_type to instantiate

---

src/Utilities/sets.jl
test/Utilities/sets.jl

[Utilities] add shift_constant for Parameter set

---

src/Bridges/debug.jl
test/Bridges/debug.jl

[Bridges] support debugging variable bridges with AbstractScalarSet

---

src/Test/test_variable.jl

[Test] fix test_add_parameter

---

Project.toml
docs/src/changelog.md

Prep for v1.13.0

---

src/Bridges/Constraint/Constraint.jl
test/Bridges/lazy_bridge_optimizer.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2124

Add Bridges.Constraint.HermitiantoSymmetricPSDBridge by default

---

docs/src/submodules/FileFormats/overview.md
src/Utilities/print.jl
src/functions.jl
src/sets.jl
test/Bridges/Variable/vectorize.jl
test/Utilities/print.jl
test/errors.jl

[Utilities] add default MIME for printing

---

src/FileFormats/NL/sol.jl
test/FileFormats/NL/sol.jl

Closes https://github.com/jump-dev/AmplNLWriter.jl/issues/166

[FileFormats.NL] make ResultCount more permissive in when it returns 1

---

Project.toml
docs/src/changelog.md

Checking https://github.com/jump-dev/SolverTests/actions/runs/4602400287

Prep for v1.14.0

---

src/Test/Test.jl
test/Test/Test.jl

Closes #2127 
@blegat is this what you had in mind?

[Test] warn on ambiguous string in exclude

---

src/Bridges/Bridges.jl
src/Bridges/Constraint/bridges/interval.jl
test/Bridges/Constraint/interval.jl

Closes #2134 
@blegat was this what you meant?

[Bridges] fix support for Rational in SplitIntervalBridge

---

src/Test/test_linear.jl

That would have caught https://github.com/jump-dev/MosekTools.jl/issues/122

Add test for infinite bounds on variable

---

src/Utilities/print.jl
test/Utilities/print.jl

[Utilities] fix printing of LaTeX model

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/failing_models/name_spaces.mps

[FileFormats.MPS] allow spaces in NAME row

---

src/Bridges/Objective/bridges/vector_slack.jl
test/Bridges/Objective/vector_slack.jl

x-ref https://github.com/jump-dev/SolverTests/pull/23

[Bridges] fix modify in Bridges.Objective.VectorSlack

---

Project.toml
docs/src/changelog.md

Prep for v1.15.0

---

docs/src/submodules/FileFormats/overview.md
src/FileFormats/MOF/MOF.jl
src/FileFormats/MOF/mof.1.3.schema.json
src/FileFormats/MOF/read.jl
src/FileFormats/MOF/write.jl
test/FileFormats/MOF/MOF.jl
test/FileFormats/MOF/nlp.mof.json

Updates to this schema: https://github.com/jump-dev/MathOptFormat/pull/24

[FileFormats.MOF] update to v1.3

---

src/Utilities/universalfallback.jl

Work around regression in nightly by adding new method

---

src/Utilities/universalfallback.jl

x-ref https://github.com/JuliaLang/julia/issues/49578

Alternative fix for #2161

---

docs/make.jl
docs/src/developer/checklists.md

Closes #2165 
I didn't realize there were so many steps.
Should potentially also add:
https://jump.dev/MathOptInterface.jl/previews/PR2167/developer/checklists/

[docs] add checklist for adding a new set

---

Project.toml
docs/src/changelog.md

https://github.com/jump-dev/MathOptInterface.jl/actions/runs/5139327574

Prep for v1.17.0

---

src/constraints.jl
test/errors.jl

Fix comparison of ScalarFunctionConstantNotZero

---

.github/workflows/documentation.yml
docs/src/submodules/Bridges/overview.md

Required for https://github.com/jump-dev/JuMP.jl/pull/3398

[docs] build on Julia v1.9

---

Project.toml
docs/src/changelog.md

https://github.com/jump-dev/MathOptInterface.jl/actions/runs/5184409345

Prep for v1.17.1

---

test/runtests.jl

Let's see if this makes a difference for https://github.com/jump-dev/MathOptInterface.jl/issues/2183

Reduce memory requirement for tests

---

docs/src/reference/nonlinear.md
src/Nonlinear/ReverseAD/mathoptinterface_api.jl
src/Nonlinear/evaluator.jl
src/Nonlinear/types.jl
src/nlp.jl
test/Nonlinear/ReverseAD.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2193.
@blegat is this what you had in mind?

Add constraint_gradient_structure and eval_constraint_gradient

---

src/Utilities/functions.jl
test/Utilities/functions.jl

Continuing work related to https://github.com/jump-dev/MathOptInterface.jl/issues/2203

[Utilities] tidy methods in functions.jl

---

src/Utilities/functions.jl
src/Utilities/operate.jl
test/Utilities/test_operate!.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/2203.
I'm a lot more confident writing these now that I've tidied things up.

[Utilities] add operate for ScalarNonlinearFunction

---

src/Nonlinear/parse.jl
test/Nonlinear/Nonlinear.jl

Closes #2220 
cc @franckgaga I guess I never considered splatting a univariate operator :smile:

[Nonlinear] fix splatting with a univariate operator

---

src/Test/test_nonlinear.jl

This is causing Juniper to fail tests

[Test] add require for ConstraintDual in test_nonlinear_duals

---

src/Bridges/Constraint/bridges/quad_to_soc.jl
test/Bridges/Constraint/quad_to_soc.jl

[Bridges] fix bug in QuadToSOCBridge getting ConstraintPrimal

---

src/Utilities/print.jl

Changes from https://github.com/jump-dev/MathOptInterface.jl/pull/2201

[Utilities] fix print for upcoming VectorNonlinearFunction

---

src/Bridges/Constraint/bridges/scalarize.jl
src/Bridges/Constraint/bridges/soc_to_psd.jl
src/Bridges/Constraint/bridges/vectorize.jl

Changes from https://github.com/jump-dev/MathOptInterface.jl/pull/2201

[Bridges] various updates based on VectorNonlinearFunction changes

---

.github/workflows/ci.yml

Let's see if this is more stable

Change to test x86 on latest release instead of LTS

---

src/Bridges/Constraint/set_map.jl
src/functions.jl

Extracted from https://github.com/jump-dev/MathOptInterface.jl/pull/2237

Minor fix to docstring of SetMapBridge

---

Project.toml
docs/src/changelog.md

Prep for v1.20.0

---

src/Utilities/operate.jl
test/Utilities/test_operate!.jl

[Utilities] fix stackoverflow in operate(+,...) with many arguments

---

docs/src/submodules/Utilities/reference.md
src/Utilities/matrix_of_constraints.jl
test/Utilities/matrix_of_constraints.jl

[Utilities] add modify_constants for MOI.modify in MatrixOfConstraints

---

src/Test/test_modification.jl

Caught by https://github.com/jump-dev/MathOptInterface.jl/pull/2319

Fix test_modification_objective_scalarquadraticcoefficientchange

---

src/functions.jl

[docs] fix docstring of ScalarAffineFunction

---

src/Bridges/Constraint/bridges/norm_infinity.jl
src/Bridges/Constraint/bridges/norm_one.jl
test/Bridges/Constraint/norm_to_lp.jl

[Bridges] fix VectorNonlinearFunction support in NormOne and NormInfinty bridges

---

.github/workflows/solver-tests.yml

I think this is right, but we'll need to run to confirm

Add Gurobi to solver-tests.yml

---

src/Bridges/Variable/bridges/hermitian.jl
src/Utilities/sets.jl
test/Utilities/sets.jl

Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2327

Implement starting values for Variable.Hermitian bridge

---

src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

Closes #2342 
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/6763666707

Fix ListOfConstraintsWithAttributeSet for AbstractBridgeOptimizer

---

src/Test/test_model.jl

Fix requirees for test_model_Name_VariableName_ConstraintName

---

Project.toml
docs/src/changelog.md

A pretty quite month here really.

Prep for v1.23.0

---

src/Bridges/Constraint/bridges/slack.jl
test/Bridges/lazy_bridge_optimizer.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/pull/2357

[Bridges] Throw in Constraint.SlackBridge if scalar constant is nonzero

---

src/Nonlinear/types.jl
test/Nonlinear/Nonlinear.jl

Fix map_indices for AbstractAutomaticDifferentiation

---

src/Test/test_modification.jl
src/Utilities/functions.jl

x-ref https://github.com/jump-dev/JuMP.jl/pull/3658

[Utilities] fix modify_function! for ScalarQuadraticCoefficientChange

---

src/Utilities/results.jl

I was looking into https://github.com/jump-dev/MathOptInterface.jl/pull/2410#issuecomment-1907199988 and I wanted to make some changes, but this first.

Tidy src/Utilities/results.jl

---

src/FileFormats/MPS/MPS.jl
src/FileFormats/utils.jl
test/FileFormats/MPS/MPS.jl

Oops. 
Cherry-picked from #2418 because I'd actually rebased it onto #2419 instead of `master`.

[FileFormats.MPS] improve performance of MPS writer

---

src/Bridges/Variable/map.jl
src/Bridges/bridge_optimizer.jl
test/Bridges/Variable/map.jl
test/Bridges/Variable/zeros.jl
test/Bridges/bridge_optimizer.jl

Replacement for https://github.com/jump-dev/MathOptInterface.jl/pull/2413

[Bridges] throw better error when variable cannot be unbridged

---

test/Bridges/lazy_bridge_optimizer.jl

Cause of the failure in https://github.com/jump-dev/MathOptInterface.jl/actions/runs/7895863289/job/21586910228

Fix tests for Julia master

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/MPS.jl

[FileFormats.MPS] fix writing duplicate bounds for binary variables

---

test/FileFormats/MPS/MPS.jl

[FileFormats.MPS] tidy and refactor test/FileFormats/MPS/MPS.jl

---

src/FileFormats/NL/NL.jl
test/FileFormats/NL/NL.jl

[FileFormats.NL] fix writing free nonlinear constraint

---

src/Nonlinear/evaluator.jl
src/Nonlinear/types.jl
test/Nonlinear/ReverseAD.jl

[Nonlinear] add timer to Evaluator for MOI.initialize

---

src/Nonlinear/ReverseAD/forward_over_reverse.jl
test/Nonlinear/ReverseAD.jl

Closes #2440 
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/7993862307

[Nonlinear] throw error if Hessian storage is insufficient

---

Project.toml
docs/src/changelog.md

Prep for v1.26.0

---

Project.toml
docs/src/changelog.md

Prep for v1.27.0

---

.github/workflows/solver-tests.yml

x-ref https://github.com/jump-dev/Xpress.jl/pull/221
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/8181867191

Add Xpress to solver-tests.yml

---

src/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/stacked_data.mps

Fix MPS reader with * in start of name, not as a comment

---

docs/src/developer/checklists.md
docs/src/submodules/Bridges/list_of_bridges.md
docs/src/submodules/Bridges/reference.md

Manually maintaining these lists is a chore, and it's easy to miss adding a bridge.

[docs] automatically build the list of bridges

---

src/FileFormats/CBF/read.jl

The reading part of https://github.com/jump-dev/MathOptInterface.jl/issues/2457

[FileFormats.CBF] use add_constrained_variables when reading

---

Project.toml
docs/src/changelog.md

Prep for v1.28.1

---

Project.toml
docs/src/changelog.md

Prep for v1.29.0

---

Project.toml
docs/src/changelog.md

Prep for v1.30.0

---

.github/workflows/solver-tests.yml

x-ref: https://github.com/jump-dev/Xpress.jl/pull/267
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/9637594799

Update solver-tests.yml to fix Xpress

---

Project.toml
docs/src/changelog.md

Prep for v1.31.0

---

Project.toml
docs/src/changelog.md

Prep for v1.31.1

---

Project.toml
docs/src/changelog.md

Prep for v1.31.2

---

src/Bridges/Constraint/bridges/table.jl
test/Bridges/Constraint/table.jl

I tried it with HiGHS and HiGHS complained that the constant of the function was not zero.

Fix table MILP bridge with constants in function

---

src/Test/test_nonlinear.jl

[Test] fix domain of variables in hs110 test

---

src/Utilities/functions.jl
test/Bridges/Constraint/slack.jl
test/Utilities/functions.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/2553

Implement filter_variables for VectorNonlinearFunction

---

Project.toml
docs/src/changelog.md

Prep for v1.34.0

---

src/Bridges/Constraint/Constraint.jl

[Bridges] s/bridged_model/model

---

Project.toml
docs/src/changelog.md

Prep for v1.35.1

---

Project.toml
docs/src/changelog.md

- If adding bug fixes documentation changes, increment the PATCH field

Prep for v1.35.2

---

Project.toml
docs/src/changelog.md
docs/src/submodules/Nonlinear/reference.md

Prep for v1.36.0

---

src/FileFormats/MPS/MPS.jl

This code goes back to https://github.com/odow/MathOptFormat.jl/pull/61 and seems to have stuck around even though it's now superfluous.

[FileFormats.MPS] remove unused code for detecting N lines

---

README.md

Time to say goodbye to this?
MOI is so much bigger than MPB at this point.

Remove MPB from readme

---

src/Nonlinear/model.jl

[Nonlinear] remove null branch

---

src/FileFormats/MOF/read.jl
test/FileFormats/MOF/MOF.jl

[FileFormats.MOF] fix reading type of PrimalStart and DualStart

---

Project.toml
docs/src/changelog.md

Prep for v1.37.0

---

src/Test/Test.jl

Not sure why I did it like that

[Test] simplify import Base.Test workaround

---

Project.toml
docs/src/changelog.md

Prep for v1.37.2

---

docs/src/developer/checklists.md

x-ref https://github.com/jump-dev/MathOptInterface.jl/issues/2689

Add a check item for Test.version_added when making a release

---

Project.toml

Replaces #2702. (Because I don't know why CI didn't run in that PR...)

Add support for ForwardDiff@1

---

.github/workflows/solver-tests.yml

x-ref https://github.com/jump-dev/MathOptInterface.jl/issues/2714#issuecomment-2784724724
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/14320427465
https://github.com/jump-dev/MathOptInterface.jl/actions/runs/14324633266

Add FrankWolfe.jl to solver-tests.yml

---

.github/workflows/solver-tests.yml

https://github.com/jump-dev/MathOptInterface.jl/actions/runs/14391068832

Add more packages to solver-tests.yml

---

src/Bridges/Constraint/bridges/SOS1ToMILPBridge.jl
src/Bridges/Constraint/bridges/SOS2ToMILPBridge.jl
test/Bridges/Constraint/SOS1ToMILPBridge.jl
test/Bridges/Constraint/SOS2ToMILPBridge.jl

[Bridges] fix bridge weights for SOS(1|2)ToMILPBridge

---

test/Utilities/mockoptimizer.jl

Dates back to https://github.com/jump-dev/MathOptInterface.jl/pull/1039

Remove @show from test of MockOptimizer

---

.github/workflows/documentation.yml

Julia v1.9 is not supported anymore

Bump Julia version to v1.10 for documentation

---

test/Nonlinear/Nonlinear.jl

Fix tests on nightly

---

src/sets.jl
test/General/sets.jl

It's needed for it to work with Dualization.jl

Implement dual for Hermitian PSD cone

---

Project.toml
docs/src/changelog.md

Prep for v1.40.2

---

src/Utilities/sets.jl

Fix docstring of inverse_trimap

---

Project.toml
docs/src/changelog.md

- DiffOpt failure is https://github.com/jump-dev/DiffOpt.jl/pull/295

Prep for v1.42.1

---

src/Utilities/operate.jl
test/Utilities/test_operate!.jl

Found while working on https://github.com/jump-dev/JuMP.jl/issues/4048

[Utilities] fix quadratic operate with non-Int coefficient

---

src/Bridges/Variable/bridges/ParameterToEqualToBridge.jl
src/Bridges/bridge_optimizer.jl
test/Bridges/bridge_optimizer.jl

Alternative to https://github.com/jump-dev/MathOptInterface.jl/pull/2821

[Bridges] add support for VariableName in variable bridges

---

Project.toml
docs/src/changelog.md

Prep for v1.44.0

---

src/FileFormats/MPS/read.jl
test/FileFormats/MPS/MPS.jl
test/FileFormats/MPS/failing_models/bad_objective_sense.mps
test/FileFormats/MPS/failing_models/bad_objective_sense_newline.mps
test/FileFormats/MPS/failing_models/malformed_indicator_value.mps
test/FileFormats/MPS/failing_models/malformed_qcmatrix_header.mps

[FileFormats.MPS] throw a proper ParseError on read failure

---

docs/Project.toml

x-ref #2850 
x-ref https://github.com/JuliaRegistries/General/pull/138737

Revert #2850
